### ISSUE TITLE
Please replace references from "lodash" to "lodash-es"

### ISSUE THREAD

**Issue by prabashn** [Microsoft/fast-dna#1001]
**Describe the bug**
Found some references to "lodash" instead of "lodash-es" in few FAST files

**To Reproduce**

For example: 
- https://github.com/Microsoft/fast-dna/blob/master/packages/fast-components-styles-msft/src/progress/index.ts

Contains:
- `import { get } from "lodash";`

Note that this is not the only reference. I found a few more references (not an exhaustive nor an accurate search - I just did a grep and found few under FAST packages. So not all of these maybe meaningful)
- fast-components-react-msft/www/main.js
- fast-components-styles-msft/dist/toggle/index.js
- fast-components-styles-msft/src/toggle/index.ts
- fast-development-site-react/www/app.js
- fast-layouts-react/www/app.js

**Expected behavior**
I believe referencing "lodash" will likely bloat up the ultimate package size as we're using both "lodash" and "lodash-es". Also AFAIK "lodash-es" is the more modular package that breaks down each function to individual exports (unlike "lodash" which is monolithic(?)

Please do a search in all component FAST repos to make sure we're not accidentally importing both.

**Comment by nicholasrice** [comment]
Good catch - the rest of our packages use `lodash-es`. Not sure how that got in there but it shouldn't be there!

**Comment by prabashn** [comment]
I don't believe we're using any of these in the app package (toggle, progress). So shouldn't be a problem... yet. You can de-pri to pick it up when you have the time.

**Comment by chrisdholt** [comment]
I was only able to find this in "Progress" from a search. There are a few references as mentioned in various www folders, but those aren't technically part of the distributed packages. In the process of this though, I did find that in certain places we aren't ignoring the www/ folder from npm publish. Created #1004 to address that seperately.

**Comment by prabashn** [comment]
was the fast-components-styles-msft/dist/toggle/index.jsfalse hit a false positive on my end?

**Comment by chrisdholt** [comment]
I *think* so, but I'm going to do one more scrub. It's also possible that we caught this in a previous version and made the update already. I'm actually surprised that there wasn't an error on our end resolving this as "lodash" is not actually a dependency of any of the packages.
