### ISSUE TITLE
MSFT button's rendered CSS contains invalid CSS values

### ISSUE THREAD

**Issue by janechu** [Microsoft/fast-dna#1013]
**Describe the bug**
Button in fast-components-react-msft is missing some values as defaults without the design system provider.

**To Reproduce**
Import Button and use it, inspect the Button in browser and look at the CSS in dev tools.

**Expected behavior**
Default styles should be enabled so that the design system provider is not a dependency.

**Screenshots**
<img width="190" alt="screen shot 2018-10-11 at 9 58 47 am" src="https://user-images.githubusercontent.com/7559015/46793024-9ff27900-cd3c-11e8-9bfa-fa1424958a95.png">

**Comment by chrisdholt** [comment]
Can no longer repro this in master. It appears that #931 addressed the issue stated here.

Closing as fixed by #931
