### ISSUE TITLE
@microsoft/fast-sketch-library does not exist in npm

### ISSUE THREAD

**Issue by connorjsmith** [Microsoft/fast-dna#1017]
**Describe the bug**
It appears npm no longer has a listing for `@microsoft/fast-sketch-library`, making some packages in `fast-dna` not be able to complete `npm install` properly.

**To Reproduce**
1. Install any package that requires `@microsoft/fast-sketch-library` or just run `npm install --save @microsoft/fast-sketch-library`
2. npm returns an error saying the package cannot be found.

**Expected behavior**
The package installs correctly

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by nicholasrice** [comment]
`fast-sketch-library` is private right now - it never have been on `npm` (we definitely need to update the readme).

Are you seeing this error in `@microsoft/fast-components-react-msft`?

**Comment by chrisdholt** [comment]
+1 this is listed as a dev dependency, so it shouldn't be required when installing the package via npm.

**Comment by connorjsmith** [comment]
Hm seems that I can't repro the issue anymore... Weird. Will re-open if I see the problem again
