### ISSUE TITLE
include bugs attribute to the package.json file

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#1046]
**What is your feature request? Please describe.**
Improve the visibility on NPM and GitHub by updating package.json file with bugs attribute as described [here](https://docs.npmjs.com/files/package.json#bugs)

**Describe the solution you'd like**
The 'url' field should link to [here](https://github.com/Microsoft/fast-dna/issues/new/choose)

for example
```node
"bugs": {
    "url": "https://github.com/Microsoft/fast-dna/issues/new/choose"
},
```
**Describe alternatives you've considered**
n/a
**Additional context**
n/a

**Comment by mptap** [comment]
@awentzel Have raised PR for this: https://github.com/Microsoft/fast-dna/pull/1047
