### ISSUE TITLE
Proposal: Add a `z-index` ramp to fast MSFT styles

### ISSUE THREAD

**Issue by chrisdholt** [Microsoft/fast-dna#1085]
We should provide a global config variable to set standardized z-index values.

Providing a ramp ensures that z-index usage is not arbitrary. We should consider leaving room for additional levels to be added if needed.

Potential values (semantic name):
- 900's (dialog): Use for Dialog component stack.
- 700's (flyout): Use for all other flyout elements.
- 500's (nav): Use for navigational elements.
- 300's (over): Use for elements that need to be raised more out of the normal flow.
- 100's (above): Use for elements that need to be raised out of the normal flow.
- 1 (neutral): Common z-index value for elements that need to be above baseline.
- 0 (default): Default browser element z-index (baseline).
- -1 (below): Use for elements that need to live below the normal flow of the document.
- -2 (buried): Reserved for lowest elements in the stack.

**Comment by nicholasrice** [comment]
The problem I've always had with this approach is that it doesn't really align to how z-index actually works. It's *so* easy to get into a situation where these named z-index are utterly meaningless.

What problems do we have today that this solves?
