### ISSUE TITLE
Components should set an empty string as the className if it is undefined

### ISSUE THREAD

**Issue by janechu** [Microsoft/fast-dna#1098]
For components in the fast-components-react-base and fast-components-react-msft there are instances where we are doing string manipulation in the generateClassNames method. Since all classes are optional, anywhere we are doing this where we are also adding additional classes we should be setting it to an empty string if lodash get is coming back as undefined, otherwise classes could be set (for example) as class="undefined button__disabled" or "button undefined".

**Comment by fmamic** [comment]
@chrisdholt Can you assign this issue to me? Thanks!

**Comment by awentzel** [comment]
@fmamic your name isn't resolving for me when trying to assign to you.  Are you able to assign to yourself?  If so feel free.

**Comment by janechu** [comment]
Closed with https://github.com/Microsoft/fast-dna/pull/1197
