### ISSUE TITLE
Form items should be able to be disabled

### ISSUE THREAD

**Issue by janechu** [Microsoft/fast-dna#1105]
The fast-form-generator-react should be able to show but disable a form item via the JSON schema supplied.

The `disabled` property should come from the schema in the same way the `title` does and should be applied to the form element (such as input).

## Requirements
- disabled should be optional
- disabled should be `true` or `false`

## Example

JSON schema partial:
```
{
    "title": "My checkbox",
    "type": "boolean",
    "disabled": true
}
```

Input render:
```
<input ... disabled="true" />
```

Be sure to test for each form-item:
- test for true results in an attribute of disabled="true"
- test for false results in an attribute of disabled="false"
- test for false results in an attribute of disabled="false"

**Comment by fmamic** [comment]
Pull request created:
https://github.com/Microsoft/fast-dna/pull/1251
