### ISSUE TITLE
Form should have validation derived from the JSON schema

### ISSUE THREAD

**Issue by janechu** [Microsoft/fast-dna#1106]
The validation that can be derived from the JSON schema includes:
- required
- patterns

See: https://json-schema.org/understanding-json-schema/reference/regular_expressions.html

Form items should be able to take advantage of this facet of JSON schemas and show an inline error and red error outline for form items not meeting patterns.

Things to consider:
Should the form have a submittal state where errors do not show up until that happens vs the constant data updating state. If they should a new task may need to be created for this scenario.

**Comment by fmamic** [comment]
Hi @janechu, 
So idea is to validate the schema before generating form by checking type/pattern in JSON. 
Should I display error list in case of failure and should I render any components (that are valid) if schema is not valid?
