### ISSUE TITLE
Adjust values for code climate to account to reduce reporting on known issues

### ISSUE THREAD

**Issue by janechu** [microsoft/fast-dna#1132]
Code climate currently reports on too many issues that are a fact of life when using a mono repository. Namely "duplicate code" which arises for the most part in React components due to the duplicate nature of props and various render functions.

Identify and remove or modify any of these configuration options to reduce the reporting on necessary code implementations.

**Comment by chrisdholt** [comment]
I haven't seen an issue here in awhile - if this is still a valid issue we can reopen, but for now this seems obsolete as I haven't seen code climate issues for awhile and there's been no progress on this task for months. Closing as obsolete.
