### ISSUE TITLE
Create `text action` as a new MSFT component

### ISSUE THREAD

**Issue by chrisdholt** [Microsoft/fast-dna#1135]
Text action allows the user to apply an action to a specific text entry. For instance, typing in an email address and then adding that to a list of other addresses. The glyph informs the user what the expected action will be.

**Comment by chrisdholt** [comment]
@nalogiudice instead of "slots", let's look at using render props for these: https://reactjs.org/docs/render-props.html

**Example:**
```
button?: (className?: string) => React.ReactNode;
```

This allows us to tell a user:
1.  That we expect a function that returns a react node
2. That we will be passing data to them

**Implementation:**
```
this.props.button(this.props.managedClasses.textAction_button)
```

**Comment by nalogiudice** [comment]
The slot implementation proposal was for the `glyph` usage - like we currently do in MSFT [button](https://github.com/Microsoft/fast-dna/blob/master/packages/fast-components-react-msft/src/button/button.tsx). Are you suggesting to _not_ do this?

**Comment by chrisdholt** [comment]
> The slot implementation proposal was for the `glyph` usage - like we currently do in MSFT [button](https://github.com/Microsoft/fast-dna/blob/master/packages/fast-components-react-msft/src/button/button.tsx). Are you suggesting to _not_ do this?

Yes; suggest we move to render props. It's a more transparent and "react" way of implementing things like this. These will show up in `action trigger` and `breadcrumb` which are currently in process.

**Comment by nalogiudice** [comment]
Got it - I'll reference those components for usage.

**Comment by nalogiudice** [comment]
@chrisdholt it doesn't look like they are using this yet, and reading the documentation, it seems like there are some caveats with this approach and pure components (which I believe we will be moving to eventually). 

Where is this direction coming from? Do @nicholasrice or/and @janechu also agree with this new approach?

**Comment by chrisdholt** [comment]
@nalogiudice these are a common pattern and @nicholasrice and @janechu are on board. Where are you seeing that "they are not using them"? This has been a pattern in the community for awhile, and now has first class documentation.

**Comment by nalogiudice** [comment]
Not talking about the react community, talking about our current PRs (breadcrumb and action trigger). Action trigger uses slots and it looks like breadcrumb has not been updated yet.

The caveat still stands (see documentation). I just don't want to start using a pattern we will have to rip out anyway - just making sure we want to go this route.

Currently, it looks like the only place with a similar pattern is within `breakpoint tracker`

**Comment by chrisdholt** [comment]
The JSS manager is using this as well, and the spec included "render props" for parts of each of those components. IE, action trigger should include a render prop for glyph. If they don't include it - they aren't complete, but that should not determine our net-new work here.

**Comment by nalogiudice** [comment]
Not saying it was determining new work, just trying to understand usage. Everything was slots before and now we are changing direction so I am just trying to wrap my head around it.

**Comment by nicholasrice** [comment]
The idea behind *slots* was to map a required feature (essentially special children) to an implementation detail. The initial approach mapped to web component's implementation in an effort to align APIs across both web component and react implementations.

The reality is that the two technologies are very different in implementation. Both technologies have this idea of exposing special children to a component to do special things with or put in special places, but by trying to align the implementation details across both technologies we end up with APIs that are not idiomatic. In React, we can simply accept a component or a function that renders a component as props - and in turn comprehensively document that API and provide strict type contracts. With slot attributes, we end up in a place where our components accept magic attributes and magic values that are loosely typed and prone to falling out of sync with component updates. While using functions that render elements as part of the prop API for a component makes tooling more difficult, it makes the actual component API more intuitive so I think it is net benefit.

**Comment by nicholasrice** [comment]
> @nalogiudice instead of "slots", let's look at using render props for these: https://reactjs.org/docs/render-props.html
> 
> **Example:**
> 
> ```
> button?: (className?: string) => React.ReactNode;
> ```
> This allows us to tell a user:
> 
> 1. That we expect a function that returns a react node
> 2. That we will be passing data to them
> 
> **Implementation:**
> 
> ```
> this.props.button(this.props.managedClasses.textAction_button)
> ```

Regarding the proposed parameter though, I'm wondering if we should expose a prop object instead of a string? That API will be more resilient over time if we ever need to add additional data to that render function.

Thoughts?

**Comment by chrisdholt** [comment]
@nicholasrice I'm up for it; the example was less of a param proposal and more of an example. Do we want to treat *all* render props params as "config" objects, or should we go case by case?

**Comment by nalogiudice** [comment]
@chrisdholt on more thought, wouldn't this only allow the before glyph if there was a button? I can't see having two glyphs and a button making sense...

**Comment by chrisdholt** [comment]
I think that makes sense - how do we prioritize which one renders in the case that both exist or are provided?

C

**Comment by nalogiudice** [comment]
@chrisdholt my initial thought is that we would only allow the `before` glyph if the button is present. I'm having a hard time imagining something that looks like this:
<img width="485" alt="screen shot 2018-11-28 at 3 09 42 pm" src="https://user-images.githubusercontent.com/22480660/49188445-abffbd80-f31f-11e8-9321-6b15bcb01149.png">

**Comment by bekell** [comment]
@chrisdholt would request that the right aligned glyph remains visible when the text field doesn't have focus. Currently the glyph disappears when focus is lost.
