### ISSUE TITLE
Import Order of React in fast-components-react-base

### ISSUE THREAD

**Issue by eljefe223** [Microsoft/fast-dna#1141]
**Describe the bug**
If the first component alphabetically does not import React before other imports type errors occur.

**To Reproduce**
Move import of react below other imports in first alphabetical component

**Expected behavior**
order of imports should not matter.

**Comment by nicholasrice** [comment]
This seems to be related to returning `React.ReactElement`s from component render functions instead of `React.ReactNode`s as specced by react's Component class

**Comment by chrisdholt** [comment]
@eljefe223 can you see if this repros with the suggestion from @nicholasrice?

**Comment by eljefe223** [comment]
That will fix it.  We need to update every components return type.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
