### ISSUE TITLE
Hypertext hover and focus do not work in Edge

### ISSUE THREAD

**Issue by eljefe223** [Microsoft/fast-dna#1158]
**Describe the bug**
When viewing hypertext in edge hover and focus styles do not work

**To Reproduce**
1. implement hypertext
2. hover or focus hypertext

**Expected behavior**
hypertext should have a 2px border bottom in brand color

**Screenshots**
![image](https://user-images.githubusercontent.com/37851214/48861821-65d3b880-ed79-11e8-9984-b8bd52053531.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge

**Comment by chrisdholt** [comment]
closed with #1159
