### ISSUE TITLE
Documentation using Docusaurus

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#1172]
There have been some internal conversations recently regarding ways to improve our documentation, as well as external feedback and requests. Some of those are gathered below into feedback regarding the documentation itself as well as potential gaps, and functional requirements of a new documentation "site".

**Documentation specific feedback:**
- Where can I find out the best ways I can leverage packages together?
- More robust guidance/tutorials (creating components, styling components, overriding styles, patterns, etc)
- API documentation
- Would be great to have everything in a single place that is searchable (don't have to dig through the repo, across packages, or in the wiki)

**Functional requirements:**
- Documentation should be managed from the repository
- Should support publishing to an external platform
- Searchable
- Markdown support
- Analytics/usage data
- Embedded content
- **New**: Ability to move content and pages around easily.
- **New**: Unlimited versioning

Docusaurus is a modern documentation platform where teams can document everything from products, to APIs and internal knowledge-bases.

**Benefits**:
- Open Source
- Github integration which allows documentation to live in source control and leverages webhooks to auto-update the documentation site
- Supports Embedded content
- Supports Rich content
- Supports limited custom theming/branding
- Supports searching
- Strong community
- React Based
- Feature rich and fully customizable
- Search capability
**Possible IA for the documentation:**

```
- What is FAST-DNA
- Concepts
    - Base components
    - Design System
    - Slots
    - Etc.
- Guides (we can bucket these over time)
    - Creating a simple app
    - Creating a base component
    - Styling a base component
    - Theming
        - Basic
        - Advanced
    - Etc…
- Contributing
- Packages
    - JSS Manager
        - About
        - Typedoc / API docs
        - Glossary
    - Base Components
        - About
        - Typedoc / API docs
        - Glossary
    - MSFT Components
        - About
        - Typedoc / API docs
        - Glossary
- Changelog
    - Not the actual changeling, but about our versioning and where to find them.
- Contact
    - Discord
    - Github issues
    - Etc
```
Resources:
https://docusaurus.io/docs/en/installation

**Comment by chrisdholt** [comment]
Good with docusaurus, it was second to gitbook before they decided to move away form OSS. We should close #941
