### ISSUE TITLE
Remove dependency on Chroma

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#1185]
fast-colors currently takes a dependency on [Chromajs](https://github.com/gka/chroma.js).  There are concerns this could be impacting performance.  Request has been made to remove as a dependency.

**Problem:**
14kb zipped dependency added to projects.

**Solution:**
Upgrade to latest ChromaJS where we can take advantage of newly release package with ES6 Support and tree shake away unused modules.

**Cost:**
1 day

**Comment by chrisdholt** [comment]
@awentzel RE: Problem

Chroma includes quite a bit of code we don't use. We can't tree shake or eliminate dead code from the file so we are always including more code than we use and more code than consumers of our package need. This leads to increased costs for package download as well as scripting costs such as parsing and execution.

From a quick look Polychrome, it appears to include things we don't need but is missing core functionality we currently use from Chroma such as some of the fns to adjust luminance, etc.

I think the best path forward is to drop any dependencies and simply create the functions we need in fast-colors; we can export them for use throughout the project if need be as well.

**Comment by awentzel** [comment]
For sure.  @nicholasrice and I discussed the same thing.  Writing our own library that suites only our needs would be the most optimized, but, does also have incur a development cost of estimate 13 days.  It's worth considering in day 1 all options and determining best path forward.

Polychrome is just an example that there are other libraries that exist.  It would be part of the resolution to see if there is something smaller that can be used or whether we just create what we need ourselves.  It's been year since ChromaJS was picked so there likely are new developments out there we may be able to leverage.

**Comment by awentzel** [comment]
Chroma has released an update that adds ES6 support. We don't have to fork, we just have to tree shake away drastically reducing effort on this issue.

**Comment by chrisdholt** [comment]
closing in favor of #1318

**Comment by chrisdholt** [comment]
Reopening as Chroma is not actually ES6 and we should just remove the dependency.

**Comment by nicholasrice** [comment]
closed by #1562
