### ISSUE TITLE
Investigate and document recommended practice for vertical scrolling with virtualization

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast-dna#1186]
**What is your feature request? Please describe.**
Want to be able to scroll large amounts of data virtually where as you scroll down the page more data will dynamically load.

**Describe the solution you'd like**
The goals is to investigate options and then document what our recommended implementation would be.  

**Describe alternatives you've considered**
It's possible this could be completed using React Virtualization. Though we should investigate other libraries as well with eye on performance to pick the lightest solution that meets the requirements.

**Additional context**
It's been requested for this work to be completed in January anytime.

**Comment by nicholasrice** [comment]
@awentzel There isn't a clear ask here - what is the deliverable? To prescribe a recommended approach for somthing we really need more details on the requirements and considerations of the implementation.

**Comment by awentzel** [comment]
This came out of a meeting we had with a few people back in December who were requesting this feature. The idea was to collaborate with those people to determine the requirements and build a software pattern to accomodate.  I'll try and find the contacts in email if we might still want this.  @chrisdholt  or @janechu may know more if anyone is still asking for this.  If not, it's possible we could tag this as Help wanted or unassign.
