### ISSUE TITLE
Action trigger examples broken

### ISSUE THREAD

**Issue by scomea** [Microsoft/fast-dna#1193]
Action trigger examples in fast-react-msft are broken and don't render

**To Reproduce**
See samples page for action-trigger on dev site - https://msft-docs.fast-dna.net/pattern/action-trigger/examples/

![image](https://user-images.githubusercontent.com/7649425/49662763-923a3680-fa01-11e8-8b5f-fb3af161f968.png)

**Expected behavior**
examples show properly

**Comment by awentzel** [comment]
@scomea please provde additional details on how they are broken, steps to reproduce, screen shot of the issue and how they should behave.  

What dev site?  Can you provide a link?
If there you know where examples are shown properly it would be helpful to attach a screen shot for this as well.

Thanks,
