### ISSUE TITLE
Add publishing of docusaurus to Circle CI Pipeline

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast-dna#1219]
Link to page can be found on https://docusaurus.io/docs/en/publishing#deploying-to-github-pages describing how to do this.

**Comment by awentzel** [comment]
We are considering non Docusaurus solutions. Until that is resolved this will be pushed out.

**Comment by chrisdholt** [comment]
@awentzel is this still a valid open issue?

**Comment by awentzel** [comment]
@chrisdholt - yes, this is valid. Publishing of documentation and packages should be a single npm task and this was the start of hooking CircleCI up to that task.  Requirements to be determined

**Comment by awentzel** [comment]
Work has been completed.  Azure DevOps now builds documentation on every successful merge into master.
