### ISSUE TITLE
Update NPM configuration to automatically bump packages on commits

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#125]
1. Create documentation for publishing internally
2. Email to Aaron
3. Update circle ci configuration for any required changes
4. Update Circle CI Settings to enable Git to use an SSH User token to checkout and commit published changes back into master.
5. Keys can be found on https://github.com/Microsoft/fast-dna/settings/keys

**Comment by chrisdholt** [comment]
@nicholasrice @janechu @awentzel with #850 do we still want to do this? I don't think this aligns with our current versioning strategy

**Comment by janechu** [comment]
@chrisdholt agreed, lets close this issue out.

**Comment by chrisdholt** [comment]
closing in favor of #850
