### ISSUE TITLE
Private build agents for Windows fails on png-async nul issue

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#1258]
**Describe the bug; what happened?**
Building on windows is failing, due to dependency issue on png-async used by Applitools.  We use the module Eyes.Utils which depends on png-async.  This package/module should be upgraded by Applitools team in order for us to take these new dependencies and this issue go away.  Until then, private windows build agents have been disabled.

**What are the steps to reproduce the issue?**
Run any build from Azure DevOps on a Windows agent and a 'nul' file error will occur preventing build from succeeding.

**What behavior did you expect?**

**If applicable, provide screenshots:**

**In what environment did you see the issue?**
windows only

* OS & Device: [e.g. MacOS, iOS, **Windows**, Linux] on [iPhone 7, PC]

**Is there any additional context?**
Provider has fixed on their end. Just waiting on others to rebuild using the fixed version. https://github.com/kanreisa/node-png-async/issues/3#event-2049220464

**Comment by chrisdholt** [comment]
@awentzel super confused by the title of this PR - can you update if not accurate?

**Comment by awentzel** [comment]
This has been resolved by application updates and new windows agents
