### ISSUE TITLE
Update changelog to auto generate on CI

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#126]
This can now be managed on https://circleci.com/gh/Microsoft and configured on `.circleci/config.yml`

Also, there are local bash files that should be updated for testing changes to CircleCI

**Comment by chrisdholt** [comment]
@awentzel @nicholasrice @janechu I don't think we want to do this with our latest publishing strategy in #850 do we?

**Comment by janechu** [comment]
@chrisdholt I agree, I think we should close this issue in reference to #850.

**Comment by chrisdholt** [comment]
closing in favor of #850
