### ISSUE TITLE
onClick is getting eaten in context-menu-item

### ISSUE THREAD

**Issue by marjonlynch** [Microsoft/fast-dna#1260]
**Description**
When using the ContextMenuItem component if a dev specifies onClick that event handler is never invoked

**Repro steps**
create an instance of ContextMenuItem and attempt to set an onClick handler:
                 
```
<ContextMenuItem
                        className={this.props.managedClasses.contextMenuItem}
                        onClick={(event: React.MouseEvent<HTMLDivElement>): void => {
                            console.log("test");
                        }}
>Test
</ContextMenuItem>
```

In the code below from context-menu-item.tsx the dev's onClick is passed in as unhandledProps and then an onClick is specified on the div effectively eating the dev's onClick.

```
public render(): React.ReactElement<HTMLDivElement> {
        return (
            <div
                {...this.unhandledProps()}
                className={this.generateClassNames()}
                role={this.props.role}
                aria-disabled={this.props.disabled || undefined}
                onKeyDown={this.handleMenuItemKeyDown}
                onClick={this.handleMenuItemClick}
            >
                {this.props.children}
            </div>
        );
    }
```

**Comment by chrisdholt** [comment]
@marjonlynch have you passed the onInvoke prop which is meant to handle the context menu item being invoked?

**Comment by marjonlynch** [comment]
Yes, we are using onInvoke and that works great. This bug was entered on the assumption that we don't want to eat the onClick if the dev specifies it.

**Comment by nicholasrice** [comment]
@chrisdholt I'm of two minds here, but I think I'd recommend leaving as unhandled - we aren't doing anything special with those props, simply ensuring that they work as expected. The benefit to leaving as unhandled is it doesn't muddy the prop documentation with props that aren't special.

There is actually precedent for this approach. We don't currently enumerate `className` as a handled prop but we do perform operations on it.

**Comment by chrisdholt** [comment]
@nicholasrice className is enumerated as a prop on the base class, I think we would be setting new precedent here. I'm not opposed, but it technically is enumerated on the base class prop contract itself from what I can see.

**Comment by nicholasrice** [comment]
All `handledProp` interfaces are divorced from the Foundation's prop interface - they make no references to each-other.

**Comment by chrisdholt** [comment]
Ok, that's what I was missing. So your suggestion would be something along the lines of:

```
if (typeof get(this.props, "onClick") === "function") {
  // fire onClick
}
```

**Comment by nicholasrice** [comment]
Yep, we simply fire the `onClick` prop directly if it exists, simply because we're occupying that key on the prop object of the root element.
