### ISSUE TITLE
form-item.align-horizontal should be renamed to form-item.text-align in Fast Tooling

### ISSUE THREAD

**Issue by eljefe223** [Microsoft/fast-dna#1276]
**Describe the bug; what happened?**
Currently in Fast Tooling has a `form-item.align-vertical` and a `form-item.align-horizontal`.  `form-item.align-horizontal` uses icons that are for paragraph aligning while `form-item.align-vertical` uses icons that are used for object aligning. This is confusing. 

**Proposal**
form-item.align-horizontal should be renamed to form-item.text-align. This pertains to text not objects.

**Example from Design**
![image](https://user-images.githubusercontent.com/37851214/50865309-0c8c0c80-135a-11e9-9f16-ba74b8d2a2c7.png)

**Comment by janechu** [comment]
This will be resolved by #551
