### ISSUE TITLE
form-item.align-vertical should be renamed to form-item.object-align in Fast Tooling

### ISSUE THREAD

**Issue by eljefe223** [Microsoft/fast-dna#1277]
**Describe the bug; what happened?**
Currently in Fast Tooling has a `form-item.align-vertical` and a `form-item.align-horizontal`.  `form-item.align-horizontal` uses icons that are for paragraph aligning while `form-item.align-vertical` uses icons that are used for object aligning. This is confusing. 

**Proposal**
`form-item.align-vertical` should be renamed to `form-item.object-align` in Fast Tooling. This should be about aligning objects.

**Example from Figma**
![image](https://user-images.githubusercontent.com/37851214/50864622-7a830480-1357-11e9-900a-7f1d15b6dbff.png)

**Comment by chrisdholt** [comment]
Can we provide more context to this?

**Comment by janechu** [comment]
This will be resolved by #551
