### ISSUE TITLE
Breadcrumb hypertext component can't add text on doc site

### ISSUE THREAD

**Issue by Falkicon** [Microsoft/fast-dna#1287]
**Describe the bug; what happened?**

When I add an additional hypertext component to breadcrumb, it won't let me add text.

**What are the steps to reproduce the issue?**

Go into breadcrumb, add a hypertext or delete text from hypertext then try to add text.

**What behavior did you expect?**

I can add text.

**In what environment did you see the issue?**

Chrome on Windows

**Comment by Falkicon** [comment]
This appears to be the case for other components as well. For example, if I remove the selected content from action toggle, I can't re-add it.

**Comment by chrisdholt** [comment]
This appears to be fixed by #1323
