### ISSUE TITLE
Icon does not dim when disabled prop is set on action toggle component

### ISSUE THREAD

**Issue by Falkicon** [Microsoft/fast-dna#1288]
**Describe the bug; what happened?**

When using the disabled prop on action toggle, the icon does not dim, only the text.

**What are the steps to reproduce the issue?**

Choose the disabled prop, notice the icon does not dim.

**What behavior did you expect?**

Dim the icon the same as the text.

**If applicable, provide screenshots:**

![image](https://user-images.githubusercontent.com/943328/51070259-2b590000-15f3-11e9-95a8-80538759f668.png)

**In what environment did you see the issue?**

Chrome on Windows.

**Comment by scomea** [comment]
Fixed by the following PR:
fix: update disabled action toggle/trigger glyph color #1298
