### ISSUE TITLE
Add new style to context menu item component

### ISSUE THREAD

**Issue by Falkicon** [Microsoft/fast-dna#1293]
**What feature are you requesting?**

Update the style of menu item to match the latest design guidance.

**What would be the benefit of adding this feature?**

Menu will match design.
Current: 
![image](https://user-images.githubusercontent.com/943328/51080705-a07d1180-1695-11e9-8c7a-0db6978c31e9.png)

After:
**Attach screenshots or images add detail to your request:**
![image](https://user-images.githubusercontent.com/943328/51080702-91965f00-1695-11e9-819d-06fbd25f2c4d.png)

**Comment by chrisdholt** [comment]
closed with #1355
