### ISSUE TITLE
Keyframes animation too fast in horizontal indeterminate progress bar

### ISSUE THREAD

**Issue by parkerwyoung** [Microsoft/fast-dna#1302]
The animation for the indeterminate horizontal progress bar is too fast. Reference the updated @ keyframes percentages from this Codepen and see if that helps:
https://codepen.io/anon/pen/aQeVOm

Changes are located on lines 53, 57, 71, and 74 of the CSS in the above codepen. If it's still too fast, we can look at extending the length to 3 seconds.

**Comment by nicholasrice** [comment]
Thanks @parkerwyoung!

**Comment by chrisdholt** [comment]
@parkerwyoung want to send a PR ;)

Kidding - or not if you want to...
