### ISSUE TITLE
Focus-visible support

### ISSUE THREAD

**Issue by nicholasrice** [Microsoft/fast-dna#1308]
# Focus-visible support

## Goals
- only display focus-rings when the user is explicitly navigating by keyboard
- easy deprecation story when `:focus-visible` gains traction in major browsers
- progressively enhance to use `:focus-visible` if it is available

## Implementation details
To support `focus-visible`, our components would make two assumptions to facilitate focus-visible support in browsers without native selector support:

1. `.js-focus-visible` class is added to the `<body>` element of the HTML document. 
2. the element being focused has a `.focus-visible` class applied when the element has focus and should appear to have focus. 

These requirements map directly to the behavior provided by the open-source [focus-visible](https://github.com/WICG/focus-visible) utility, and that utility would be our recommend approach for implementing the requirements. We would not, however, preclude other implementations from fulfilling the requirements if a solution other than the above is desired.

Our library would provide a small utility to simplify applying focus styles in a backwards compatible way and would perform the following:

1. remove the default outline on the `&:focus` selector
2. Determine if `:focus-visible` is supported by the browser.
   1. If it is, apply the focus styles to the `&:focus-visible` selector
   2. If it is not, apply the focus styles to the following selectors
      1. `body:not(.js-focus-visible) &:focus` - support default focus for apps without the focus-visible utility
      2. `.js-focus-visible &.focus-visible` - support focus-visible for apps with the focus-visible utility

## Notes
- size of [focus-visible](https://github.com/WICG/focus-visible) comes in at 1.17kb minified/gzipped

**Comment by chrisdholt** [comment]
@nicholasrice confirming we can close this has been added and deployed to NPM.
