### ISSUE TITLE
Foundation component assumes handled props property on class is available 

### ISSUE THREAD

**Issue by eljefe223** [Microsoft/fast-dna#1329]
**Describe the bug; what happened?**
We don't check if this.handledprops exists before we check hasOwnProperty causing a runTime error.

**What are the steps to reproduce the issue?**

Example:

1. Create a foundation component
2. Pass unhandled props without setting handledprops

**What behavior did you expect?**
We should check if this.handledprops exist before we check hasOwnProperty

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Edge, Chrome, Safari, FireFox]
* Version [e.g. 1.8.0]

**Is there any additional context?**

**Comment by jkmdev** [comment]
Hi @eljefe223, would it be okay with you if I worked on this one?

**Comment by eljefe223** [comment]
@jkmdev please, go for it.

**Comment by nicholasrice** [comment]
closed by #1547
