### ISSUE TITLE
Broken 404 page when returning to refresh the page a few days later

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#1343]
**Describe the bug; what happened?**
I had https://explore-stage.edgewebui.net/fast-components/action-toggle/ sitting in my browser tab and refreshed after a few days the same page and received a 404 on the inner part of the page as shown in attached image.

**What are the steps to reproduce the issue?**
1. Let a page site dormant for a day or two
2. refresh page
3. notice issue

**What behavior did you expect?**
page reloads content entirely.

**If applicable, provide screenshots:**
![screen shot 2019-01-28 at 11 27 30 am](https://user-images.githubusercontent.com/16669785/51858113-25e8fe80-22f1-11e9-9fdf-7cc5f1c7c64c.png)

**In what environment did you see the issue?**
MacOS Edge/Chromium v73.0.66.0

**Comment by nicholasrice** [comment]
@awentzel That URL doesn't actually exist anymore, so I think 404 is appropriate. Closing this issue.
