### ISSUE TITLE
Broken Link to Components page in Documentation

### ISSUE THREAD

**Issue by shauntc** [Microsoft/fast-dna#1379]
Components link leads to an error page "Error 403 - This web app is stopped"

1) go to https://microsoft.github.io/fast-dna/docs/en/contributing/install (dev documentation link from the readme)
2) click the components link in the top right corner

![image](https://user-images.githubusercontent.com/4647935/52750504-4a0b3780-2fa1-11e9-8520-444389602410.png)

**Comment by chrisdholt** [comment]
@awentzel can you take a look at this?
