### ISSUE TITLE
Refactor form generator documentation with hackme session

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#1384]
**What feature are you requesting?**
Currently there are two readme.md files for fast-form-generator-react.  We should look to combine both of these into the same readme.md at the root of that package.

This section was removed to eliminate compiler warnings from Docusaurus.

```md
Each special component is listed in the form component [README.md](https://github.com/Microsoft/fast-dna/blob/master/packages/fast-form-generator-react/src/form/README.md)
```
This should be added back in as makes best sense for the specified content.

This is the markdown file that should be reviewed as a team.
`/packages/fast-form-generator-react/README.md`

**What would be the benefit of adding this feature?**
1. This would enable content to be found on npmjs.org
2. This would enable content to be found on github
3. This would include improvement over content with team hackme.md session

**Comment by janechu** [comment]
Closed as part of #1423
