### ISSUE TITLE
'expandedGlyph' prop not recognized by React in TreeViewItem

### ISSUE THREAD

**Issue by bekell** [Microsoft/fast-dna#1389]
React does not recognize the 'expandedGlyph' prop on the TreeViewItem and throws the below warning in the console.

_Warning: React does not recognize the `expandedGlyph` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `expandedglyph` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by TreeViewItem)
    in TreeViewItem (created by withJSS(TreeViewItem))
    in withJSS(TreeViewItem) (created by SidePaneLayout)
    in div (created by TreeView)
    in TreeView (created by withJSS(TreeView))_

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
Win 10, PC

* Browser [e.g. Edge, Chrome, Safari, FireFox]
Chrome

**Comment by chrisdholt** [comment]
@bekell I think this is intended for a different repo - FAST doesn't have a TreeViewItem.
