### ISSUE TITLE
Should package readme titles follow Chicago Manual of Style headline-style?

### ISSUE THREAD

**Issue by chrisdholt** [Microsoft/fast-dna#1393]
While there is a pattern of style in our package readme titles, it appears inconsistent.

Examples below:
* FAST Breakpoint tracker React
* Fast Colors
* Fast Components React base
* Fast Components class name contracts
* Fast Components foundation React

From what I've seen in the Chicago manual of style which is the preferred writing guidelines per the style guide (https://microsoft.github.io/fast-dna/docs/en/contributing/writing-style-guide), for consistency regarding titles of works, headline-style is preferred.

Per the Chicago Manual of Style, regarding "Names, Terms, and Tile of Works" (emphasis mine):

> The term “down style” may also refer to sentence-style capitalization for titles of works (see 8.158); in most contexts, **Chicago prefers headline-style capitalization (sometimes called “up style”; see 8.159)**.

Regarding headline-style capitalization of titles specifically:

> The conventions of headline style are governed mainly by emphasis and grammar. The following rules, though occasionally arbitrary, are intended primarily to facilitate the consistent styling of titles mentioned or cited in text and notes:
> 1. Capitalize the first and last words in titles and subtitles (but see rule 7), and capitalize all other major words (nouns, pronouns, verbs, adjectives, adverbs, and some conjunctions—but see rule 4).
> 2. Lowercase the articles the, a, and an.
> 3. Lowercase prepositions, regardless of length, except when they are used adverbially or adjectivally (up in Look Up, down in Turn Down, on in The On Button, to in Come To, etc.) or when they compose part of a Latin expression used adjectivally or adverbially (De Facto, In Vitro, etc.).
> 4. Lowercase the common coordinating conjunctions and, but, for, or, and nor.
> 5. Lowercase to not only as a preposition (rule 3) but also as part of an infinitive (to Run, to Hide, etc.), and lowercase as in any grammatical function.
> 6. Lowercase the part of a proper name that would be lowercased in text, such as de or von.
> 7. Lowercase the second part of a species name, such as fulvescens in Acipenser fulvescens, even if it is the last word in a title or subtitle.
> 8. For examples, see 8.160. For hyphenated compounds in titles, see 8.161.

Examples from the guide:

> The following examples illustrate the numbered rules in 8.159. All of them demonstrate the first rule; the numbers in parentheses refer to rules 2–7.
> Mnemonics That Work Are Better Than Rules That Do Not
> Singing While You Work
> A Little Learning Is a Dangerous Thing (2)
> Four Theories concerning the Gospel according to Matthew (2, 3)
> Taking Down Names, Spelling Them Out, and Typing Them Up (3, 4)
> Tired but Happy (4)
> The Editor as Anonymous Assistant (5)
> From Homo erectus to Homo sapiens: A Brief History (3, 7)
> Defenders of da Vinci Fail the Test: The Name Is Leonardo (2, 3, 6)
> Sitting on the Floor in an Empty Room (2, 3), but Turn On, Tune In, and Enjoy (3, 4)
> Ten Hectares per Capita, but Landownership and Per Capita Income (3)
> Progress in In Vitro Fertilization (3)

Based simply on rule 1, does it make sense to follow headline-style for our package names which would be reflected as:

* FAST Breakpoint Tracker React
* Fast Colors
* Fast Components React Base
* Fast Components Class Name Contracts
* Fast Components Foundation React

**Comment by awentzel** [comment]
I'm not seeing inconsistencies. All packages use "FAST" in upper case because it's an acronym and React is capitalized because is a proper name. There is a future task that will be completed that will ensure the left navigation and the pages do not use FAST in the title. So when "FAST" is removed the titles will all be accurate. If you are still seeing inconsistencies please file an issue. For guidance on naming refer to https://microsoft.github.io/fast-dna/docs/en/contributing/writing-style-guide

**Comment by chrisdholt** [comment]
@awentzel this issue was created based on your verbatim request from *the PR I approved*. I've set this issue as a question and not a bug so that we can work through it. Please re-read this issue which references the Chicago manual of style which is referenced as our north star:

From our writing style guide:
> Most writing guidelines used for this project come from the Chicago Manual of Style and The Associated Press Stylebook. When these two publications have conflicting guidance, the Chicago Manual of Style is usually preferred.

**Comment by awentzel** [comment]
@Falkicon provided requirements so he can provide guidance to future direction.

**Comment by nicholasrice** [comment]
@awentzel @chrisdholt Can this be closed since there is a issue tracked to address this?

**Comment by chrisdholt** [comment]
@nicholasrice I'd prefer to move these comments over to that issue and close here instead. Does that address this specific instance? From what I'm seeing that issue appears to be tracking that the current readme file naming is correct. This question is asking if that should be the case.

**Comment by awentzel** [comment]
@chrisdholt @nicholasrice The current readme file names are correct and so this can be closed I think without moving any comments.  I've updated notes in https://github.com/Microsoft/fast-dna/issues/1394 to specify rational and decision.
