### ISSUE TITLE
fast-components-react-base should not depends on fast-jss-manager-react

### ISSUE THREAD

**Issue by K05-MSFT** [Microsoft/fast-dna#141]
fast-components-react-base should be an agnostic on JSS usage, the only thing it defined is to have a managedClasses prop which follows IButtonClassNameContract  contract. In other word, the user of base components can use them w/ or w/o JSS (fast-jss-manager-react). @nicholasrice @awentzel.

https://github.com/Microsoft/fast-dna/blob/f666c238ce6d952896a6543f8ed60830a908b1de/packages/fast-components-react-base/src/button/Button.tsx#L5

**Comment by nicholasrice** [comment]
That makes sense to me. Each component will still need to expect `managedClasses` to exist and conform to an expressed interface, but we can internalize the typings to this package so there is no dependency on `fast-react-jss-manager-react`.
