### ISSUE TITLE
TextAction inner TextField draws a border on focus when it shouldn't

### ISSUE THREAD

**Issue by connorjsmith** [Microsoft/fast-dna#1418]
**Describe the bug; what happened?**
Seems like the focus-visible changes introduced focus outline borders on TextFields that are used within other components which looks incorrect.

**What are the steps to reproduce the issue?**
Focus a TextAction object, though this bug is probably present in any component that uses a textfield internally.

![image](https://user-images.githubusercontent.com/5892363/53194770-15af0100-35c9-11e9-81b2-4a816485f8c4.png)
**What behavior did you expect?**
Never show an outline on the inner textfield, even on keyboard navigation

**In what environment did you see the issue?**

* OS & Device: Windows 10
* Browser: Chrome

**Comment by chrisdholt** [comment]
Thanks @connorjsmith!
