### ISSUE TITLE
Create a unified package for tooling

### ISSUE THREAD

**Issue by janechu** [Microsoft/fast-dna#1423]
# Abstract

Combine packages using the same or similar APIs which are intended to work together into a single package.

## Description

There are packages in the repository that are meant to work together to create applications, as a group referred to as the "tooling".

These packages are:
- `fast-form-generator-react`
- `fast-navigation-generator-react`
- `fast-viewer-react`
- `fast-css-editor-react`
- `fast-data-utilities-react`

Combining these packages would result in a new package named `fast-tools-react` with all exports as secondary exports for example `Form`, `Navigation`, `Viewer`, `CSSEditor`.

## Benefit for consumers

Consumers will only need to install a single package and import whichever relevant exports they are using, since these exports are ES6 everything should be able to be tree shaken. It will also aide in the concept of how FAST tooling works together since it will be in one place, there can be several working examples and documentation examples.

## Benefit for contributors

This will enable contributors to create a system of testing these tools together as they rely on the same API (JSON schemas, data and plugin systems) as well as styles.

**Comment by janechu** [comment]
Requesting feedback from @nicholasrice @chrisdholt @Falkicon @awentzel

**Comment by eljefe223** [comment]
Sounds good to me.
