### ISSUE TITLE
Box shadow on content items is clipped in horizontal overflow

### ISSUE THREAD

**Issue by hchokshi** [microsoft/fast-dna#1429]
**Describe the bug; what happened?**
When horizontal overflow items have `box-shadow`, this is clipping at the bottom. This is because it doesn't increase the `clientRect.height`, so the height of the overflow container isn't increased to show the shadow.

**What are the steps to reproduce the issue?**
Create a horizontal overflow, add items with a `box-shadow` (e.g. `box-shadow: 0px 2px 4px rgba(0,0,0,0.25)`) - notice the shadow at the bottom will not be visible.

**What behavior did you expect?**
Overflow height increases to compensate.

**If applicable, provide screenshots:**
Overflow with box shadow (default, note clipping):
![image](https://user-images.githubusercontent.com/10136407/53264394-54f45500-3690-11e9-91fc-e399e61d2366.png)

Overflow with box shadow (height increased by 4px through browser inspector, expected behaviour):
![image](https://user-images.githubusercontent.com/10136407/53264422-650c3480-3690-11e9-9899-191b3bbbb4aa.png)

**In what environment did you see the issue?**
* OS & Device:
Windows 10 Enterprise 1809

* Browser
Chrome 72.0.3626.109 (Official Build) (64-bit)
Firefox Developer Edition 66.0b9 (64-bit)
Edge 44.17763.1.0

* Version
v3.7.0

**Is there any additional context?**
One possible solution may be to get rid of `getItemMaxHeight()` and use the browser height with `overflow-y` visible, and instead hide the scrollbar using CSS (example SASS below).

```sass
.contentRegion {
    scrollbar-width: none; /* Firefox */
    -ms-overflow-style: none;  /* IE/Edge */

    &::-webkit-scrollbar { /* Chrome/Safari */
      display: none;
    }
}
```

**Comment by chrisdholt** [comment]
Thanks @hchokshi! We'll investigate this.

**Comment by hchokshi** [comment]
Refresh stale status - bug is still present.
