### ISSUE TITLE
width in Pane works differently in the description in pane.props.ts.

### ISSUE THREAD

**Issue by yongkimin** [Microsoft/fast-dna#1433]
**Describe the bug; what happened?**
If I set width in <Pane> with resizable, the Pane has fixed width and isn't resizable.

**What are the steps to reproduce the issue?**
create pane with resizable and width.
ex) <Pane resizable={true} width={200}>

**What behavior did you expect?**
width should be initial width and Pane should be resizable when dragging resizing bar.

**Is there any additional context?**
it seems width() in (fast-dna/packages/fast-layouts-react/src/pane/pane.tsx) checks this.props.width first. As a result, width isn't changed even though this.state.width is changed by dragging.
it would be better to have another property to set initial width or use width for initial width.

**Comment by nicholasrice** [comment]
I would support adding an `initialWidth` property.

I think the current comment for the `width` property is incorrect. What seems intuitive to me is that if a width property is supplied, the component will be always be that width (unless that width is less than `minWidth`). This maps to CSS behavior.

**Comment by chrisdholt** [comment]
I agree with @nicholasrice - I think the comment should be updated and a new prop should be created to handle this scenario.

**Comment by nicholasrice** [comment]
Created work item with implementation details here: https://github.com/Microsoft/fast-dna/issues/1437

Closing this issue.

**Comment by chrisdholt** [comment]
#1437 has been merged and will likely ship in 3.2.0
