### ISSUE TITLE
JSSManager should enable assigning a ref to the managed component

### ISSUE THREAD

**Issue by nicholasrice** [Microsoft/fast-dna#1435]
Because the `ref` prop is treated specially by React, there is currently no way to obtain a React Reference to a component managed by the `JSSManager`. 

Adding a new prop to the `JSSManager` - `jssManagedRef` - would allow ref forwarding without being a breaking change, and allow access to managed components instances. This will allow authors to access public properties and methods of classes (as is required by https://github.com/Microsoft/fast-dna/issues/1398)

**Comment by chrisdholt** [comment]
@nicholasrice I think this is well thought out; would recommend moving this to a task.

**Comment by nicholasrice** [comment]
@chrisdholt any feedback on the prop name? I know some libraries use `innerRef` but I thought name-spacing might be prudent for a minor change. I also toyed with `jssManagedComponentRef` which seemed descriptive but long.

**Comment by chrisdholt** [comment]
I like `jssManagedRef` but perhaps that's because I understand that these are "jssManaged" components? I personally think we can leave "component" off as that at least seems intuitive.

**Comment by awentzel** [comment]
Is there a class name for which this `Ref` would already be part of?  I'm a fan of not duplicating names.  For example, if we already are in the context of JSSManager because that is the class name I would not use JSSManager internally for any props names.

**Comment by nicholasrice** [comment]
@awentzel This doesn't really have anything to do with class names - it concerns core React capabilities and the public prop interface exposed by the `JSSManager` - which essentially extends the prop interface of any component it wraps.

**Comment by nicholasrice** [comment]
Pushing this out to 4.0 -  then we can implement this feature using the `innerRef` name - which is more common for HOCs
