### ISSUE TITLE
Update typings in JSS Manager

### ISSUE THREAD

**Issue by janechu** [Microsoft/fast-dna#144]
The current JSS Manager uses typings that aren't always correct, investigate and find better typings for the TODO items in both the React and Angular JSS Manager packages.

**Comment by Falkicon** [comment]
@nicholasrice, can you please update this with more detail.

**Comment by nicholasrice** [comment]
Without more specifics this isn't actionable - JSS manager typings are robust and accurate so I don't think there is work here.
