### ISSUE TITLE
Ensure passing custom managed classes to Pivot and Carousel is working properly

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast-dna#1442]
**Describe the bug; what happened?**
In `<Carousel/>` and `<Pivot/>` we are mapping classNames to the `tabsClassNameContract` we want to make sure that if one of the custom mappings is not passed the component can handle it properly.

**Comment by nicholasrice** [comment]
@eljefe223 can you be a little more specific? Is there something that is happing that shouldn't be? Can you format this with more detailed repro steps - by your description I'm not sure what the ask is.

**Comment by eljefe223** [comment]
@nicholasrice yeah this isn't very specific from the description it almost sounds like the classNames are required. But they are all optional. @nalogiudice made this change in January: https://github.com/microsoft/fast-dna/pull/1345 Maybe they were related?

**Comment by chrisdholt** [comment]
Closing this as obsolete for now. Happy to dig back in if more detail is provided.
