### ISSUE TITLE
The 'dependencies' which is not published by FAST-DNA should be 'peerDependencies' instead.

### ISSUE THREAD

**Issue by K05-MSFT** [Microsoft/fast-dna#145]
The final production bundle size will matter for all the users in terms of performance (PLT), so, would be reasonable to let user pick the compatible version for its production instead, and, yes, all user needs to test by itself in terms of version choice, as long as we follow the semantic version syntax. @nicholasrice 

https://github.com/Microsoft/fast-dna/blob/f666c238ce6d952896a6543f8ed60830a908b1de/packages/fast-components-react-base/package.json#L82

**Comment by nicholasrice** [comment]
Yep, good call Knight - I'll make updates.
