### ISSUE TITLE
Update Badge appearance options

### ISSUE THREAD

**Issue by nicholasrice** [Microsoft/fast-dna#1452]
Badge's appearance prop doesn't really solve our needs - badge's colors are highly variable so having named appearance colors doesn't help most consumers.

We should remove the `appearance` prop entirely, and introduce a `filled` prop. If `filled` is false, the badge will take the non-backplate styling. If `filled` is true, the yellow backplate will be applied with a text color of accent-foreground-cut. 

Our recommended approach for changing badge's backplate color would be to apply CSS `color` and `background` via `jssStyleSheet` props, or otherwise overriding defaults with CSS.

**Comment by nalogiudice** [comment]
This is something we struggled with solving initially. The original idea was pretty similar to what you are outlining, but with more appearance options - the user was always able to override via JSS. Is the idea that this API is too much?

**Comment by nalogiudice** [comment]
Simplifying API as @nicholasrice described above.
