### ISSUE TITLE
Update JSS Manager property names

### ISSUE THREAD

**Issue by janechu** [Microsoft/fast-dna#147]
There are differences between property names between the React and Angular JSS manager, these should be consolidated:

- React uses `designSystem` for the design system and Angular uses `config`
- React uses `design system provider` and Angular (due to naming restrictions) uses `design system`

There is also a difference between the other open source JSS Manager where it uses `classes` and we are using `managedClasses` for the sake of parity we should bring this into alignment as well.

**Comment by nicholasrice** [comment]
I think we're far enough along that we shouldn't do this - marking wontfix.
