### ISSUE TITLE
Focus does not remain locked in Context Menus

### ISSUE THREAD

**Issue by bekell** [Microsoft/fast-dna#1483]
**Describe the bug; what happened?**
Focus can leave the context menu when it is open and travel to other components on the page.

**What are the steps to reproduce the issue?**
Open a context menu and press tab multiple times. Notice that you can navigate outside of the context menu and interact with other elements.

**What behavior did you expect?**
- Focus should remained locked within the context menu
- Tabbing should not cause any navigation
- Arrow keys should navigate through the context menu (already working)
- ESC should close the context menu (already working)

This aligns to other context-menu implementations within the Chromium browser.

**Comment by nicholasrice** [comment]
This I think needs an investigation - I could see the argument where it *shouldn't* lock focus, but it would need to notify the auther that the user has taken an action that should close the menu. 

Either way I think the component story is incomplete but we need to look into context-menu keyboard behvaiors to see what should really happen in this case.

**Comment by nicholasrice** [comment]
I wasn't able to find documentation to support that the menu role should lock keyboard focus to the menu,
and these examples all bring focus away from the menu on tab:
- https://www.w3.org/TR/wai-aria-practices/examples/menu-button/menu-button-links.html
- https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-1/menubar-1.html
- https://www.w3.org/TR/wai-aria-practices/examples/menubar/menubar-2/menubar-2.html

If we can find good examples and specifications on the requirements for this behavior I think we can implement it, but for now I think the best approach is to facilitate this by allowing custom `onKeyDown` handlers to be registered with the ContextMenu component
