### ISSUE TITLE
404 Error when clicking on Next

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#1497]
**Describe the bug; what happened?**
On [this page](https://microsoft.github.io/fast-dna/docs/en/contributing/status) when clicking on the Next button at the bottom right corner of the page itself user is taken to a 404 page.

**What behavior did you expect?**
Next page should load in web browser.

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/16669785/53926882-e58c4700-4039-11e9-9a48-e0c30e4c5511.png)

**In what environment did you see the issue?**
Production all browsers

**Is there any additional context?**
Yes, this is a Docusaurus page so I have suspiction there is either a missed configuration in `/website/` in our code or a bug on Docusaurus.

**Comment by macarva** [comment]
I just started trying to solve this one, clonned and went through initial setup.
After a executed npm run-script docs:build and restarted the local server, links where functional again, so my gues this was a problem with Docusaurus and it was fixed.

**Comment by awentzel** [comment]
Thanks @macarva, I have a couple style issues to fix, 1 PR in the queue by @jkmdev and then I'll publish.

**Comment by awentzel** [comment]
Confirmed on my end that a rebuild fixes this issue.

**Comment by awentzel** [comment]
Should have auto-closed with the merged pr above. work has been resolved and deployed
