### ISSUE TITLE
Need a solution for none theming color values

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast-dna#1502]
**Describe the bug; what happened?**
In some cases we need none themeing colors that ignore theme changing but should be managed by the design system.

For instance each slide in `<Carousel />` can be individually themed. Meaning that theme change is ignored and the components inside should "lock" to the specified theme regardless of the overall selected theme.

Some ideas for naming:
`AlwaysDark` `AlwaysLight` `NonThemingDark` `NonThemingLight` `AlwaysForeground` `AlwaysBackground` `NonThemingForeground` `NonThemingBackground` etc.

**Comment by nicholasrice** [comment]
I think a solution that maps to our current utilities would be to expose two new color functions: `neutralSwatch` and `accentSwatch`. Both functions would accept one or two index values. If one index value is supplied, that index would always be returned from the appropriate palette. If two indexs are supplied, the first would be considered the "light mode" index while the second would be considered the "dark mode" index. Which index is used would be determined by the same logic we use to determine `neutralForegroundRest`
