### ISSUE TITLE
ResizeObserver is never disengaged in Horizontal Overflow

### ISSUE THREAD

**Issue by hchokshi** [Microsoft/fast-dna#1515]
**Describe the bug; what happened?**
In Chrome, console logs show resize events being fired, and access to members of `undefined` once a horizontal overflow is unmounted. This is due to the resize observer not being removed in `componentWillUnmount`.

**What are the steps to reproduce the issue?**
1. Create a `HorizontalOverflow` and a button that removes it.
2. Click the button to remove the overflow component in Chrome.

**What behavior did you expect?**
Observer is cleaned up on component dismount.

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/10136407/54054624-8e07eb80-419f-11e9-9ecc-7b38a027600d.png)

**In what environment did you see the issue?**

* OS & Device
Windows 10 Enterprise 1809

* Browser [e.g. Edge, Chrome, Safari, FireFox]
Chrome 72

* Version [e.g. 1.8.0]
fast-components-react-base 3.9.1

**Is there any additional context?**
Resize observer object reference should be kept at init time, and `.disconnect()` called on `componentWillUnmount`. 
https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver#Methods

**Comment by nicholasrice** [comment]
Thanks @hchokshi - looks like a bug, thanks for filing the issue.

**Comment by shauntc** [comment]
@nicholasrice I think this can be closed now

**Comment by chrisdholt** [comment]
closed by #1529
