### ISSUE TITLE
Create a icons next to labels

### ISSUE THREAD

**Issue by janechu** [Microsoft/fast-dna#1522]
Currently we have no way to express additional information on a field, in order to make this a more freeform experience we should have icons to the right of the field label for indication that there is something different about this field.

Icons to include:
- Info (more information is available for this field)
- Warning (there is an issue with this field the user may wish to know about)
- Locked (this field is locked and cannot be edited)

There may also be an instance where a custom badge may be added, this should require some additional investigation.

In addition to the badges, information should be provided to them that will show text when hovered.

In total two new fields (at least) will need to be added to the JSON schema, `badgeTitle` and `badgeDescription`.

Example:
```json
{
    "title": "Example",
    "description": "This is an example",
    "badge": "info",
    "badgeDescription": "This is further information about this field",
    "type": "string"
}
```

**Comment by bheston** [comment]
![Label + Icon](https://user-images.githubusercontent.com/47367562/54152773-4087ba80-43fb-11e9-8a2f-556ccf6a3546.png)
