### ISSUE TITLE
Evaluate JSON schema with plugins anytime it changes

### ISSUE THREAD

**Issue by janechu** [microsoft/fast-dna#1540]
This should allow the user to not have to use `onSchemaChange` in order to pass the schema back in if it has been modified by plugins. This will simplify the implementation of the `Form` and safeguard against multiple render cycles.

**Comment by stirlaf** [comment]
I think that it would be better to not store the schema in state at all.  Neither in the form's react state nor in some external state. Instead I believe it is better if the plugins get re-evaluated for every render, an updated schema get's generated for every render, and then discarded at the end of the render cycle.

The reason for this is that a plugin may rely on external state to update the schema.  If that state changes there is no way for the form to know that it needs to re-run the plugin.  That means that the form needs to run the plugin every time anyway to check if it's output has changed, which removes the value of storing an updated schema in state at all.

**Comment by janechu** [comment]
This issue is now redundant as schema related plugins are being deprecated in v2.0.0
