### ISSUE TITLE
RTL next/previous is reversed in Edge in horizontal overflow

### ISSUE THREAD

**Issue by hchokshi** [microsoft/fast-dna#1558]
**Describe the bug; what happened?**
RTL horizontal overflow with `previous` on right and `next` on left works as expected in Chromium browsers (`previous` scrolls right towards start of line, `next` scrolls left towards end of line). In Edge, however, they scroll in their LTR directions (previous goes left, next goes right).

**What are the steps to reproduce the issue?**
Create RTL horizontal overflow - previous button on right, next button on left. Open in Edge, press buttons. Their directions are reversed.

```
<HorizontalOverflow dir="rtl">
    <Button slot="next">Next</Button>
    {this.props.content.map(...)}
    <Button slot="previous">Previous<Button>
</HorizontalOverflow>
```

**What behavior did you expect?**
Same as Chrome.

**In what environment did you see the issue?**

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
Windows 10 Enterprise 1809

* Browser [e.g. Edge, Chrome, Safari, FireFox]
Microsoft Edge 44.17763.1.0

* Version [e.g. 1.8.0]
Fast components react base 3.9.1

**Comment by stercomp** [comment]
Verified issue is still present.
