### ISSUE TITLE
RTL overflow state is broken in Firefox in horizontal overflow

### ISSUE THREAD

**Issue by hchokshi** [microsoft/fast-dna#1559]
**Describe the bug; what happened?**
Created RTL horizontal overflow in Firefox, with next button on left and previous button on right. Previous/next buttons are disabled when there is no overflow in that direction. This does not work as expected.

**What are the steps to reproduce the issue?**
Created RTL horizontal overflow. Created OverflowChange listener for Next button is set to be disabled when overflowEnd is false, and Previous button to be disabled when overflowStart is false. When scrolled fully to the right (start), next button is disabled and previous button is not.

Add a `console.log` overflow change handler. The event on page load is
```js
{
    overflowEnd: false,
    overflowStart: true
}
```

Scroll to the far left. No overflow change event is fired when scrolled to the left end.

**What behavior did you expect?**
Next button should be enabled in the start position, previous button should be disabled. The overflow change event on load should be
```js
{
    overflowEnd: true,
    overflowStart: false
}
```

Scrolling to the left end should fire an overflow event with overflowEnd false.

**In what environment did you see the issue?**

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
Windows 10 Enterprise 1809

* Browser [e.g. Edge, Chrome, Safari, FireFox]
Firefox Developer Edition 67.0b2 (64-bit)

* Version [e.g. 1.8.0]
Fast components react base 3.9.1

**Comment by stercomp** [comment]
verified issue is still present

**Comment by scomea** [comment]
A bunch of these horizontal overflow bugs are related to this issue, working on a fix: http://lists.w3.org/Archives/Public/www-style/2014Apr/0438.html
