### ISSUE TITLE
RTL next/previous both go in same direction in Firefox in horizontal overflow

### ISSUE THREAD

**Issue by hchokshi** [microsoft/fast-dna#1560]
**Describe the bug; what happened?**
Created RTL horizontal overflow in Firefox, with next button on left and previous button on right. In the start position, neither button does anything. After scrolling a bit, pressing either button will go right (towards start position).

**What are the steps to reproduce the issue?**
Created RTL horizontal overflow. Scroll a bit towards the left. Click next button. Scroll again, click previous button. Both buttons travel towards right of screen (start of line).

**What behavior did you expect?**
In RTL, next button should go left, previous button should go right.

**In what environment did you see the issue?**

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
Windows 10 Enterprise 1809

* Browser [e.g. Edge, Chrome, Safari, FireFox]
Firefox Developer Edition 67.0b2 (64-bit)

* Version [e.g. 1.8.0]
Fast components react base 3.9.1

**Comment by hchokshi** [comment]
Might be related with #1559

**Comment by scomea** [comment]
A bunch of these horizontal overflow bugs are related to this issue, working on a fix: http://lists.w3.org/Archives/Public/www-style/2014Apr/0438.html
