### ISSUE TITLE
Add the ability to set an initial height for the "Row" component when it's resizable

### ISSUE THREAD

**Issue by stirlaf** [Microsoft/fast-dna#1593]
I want to be able to set an initial height for the "Row" component that is different to the minimum height when I make it resizable.  This is because the default height that most users will want is bigger than the minimum I want to allow.

While "Row" does have a height property already, when I set it, it stops resizing from working.

**Comment by nicholasrice** [comment]
I would purpose the same approach we took with `Pane` - https://github.com/Microsoft/fast-dna/issues/1437

**Comment by chrisdholt** [comment]
I'll take this
