### ISSUE TITLE
Add "stealth" appearance to MSFT button

### ISSUE THREAD

**Issue by eljefe223** [Microsoft/fast-dna#1598]
**What feature are you requesting?**
We should add a `stealth` option to the `<Button/>` `appearance` prop.

**What would be the benefit of adding this feature?**
Stealth buttons are a common design pattern throughout Microsoft's UI. Currently we need to implement CSS properties to mimic this pattern every time we want a stealth button.

**Comment by nicholasrice** [comment]
I'm wondering if we want to separate button appearances into separate controls.

The `Button` stylesheet is already pretty large, and adding another appearance option only adds to it. In general, I don't think changing between appearances is a common use-case, so in most cases we're compiling style rules that don't ever get used (for the other appearances)

**Comment by chrisdholt** [comment]
@nicholasrice I love that idea. I think it may require us revisiting the need for our button derivatives, which would be good as well.
