### ISSUE TITLE
Form inheritance use case

### ISSUE THREAD

**Issue by janechu** [microsoft/fast-dna#1612]
This is an open discussion regarding the `Form` export from the `@microsoft/fast-tooling-react` package. Due to the nature of the `Form` it can be used in a myriad of ways and there should be methods for providing hooks/indicators to best communicate additional information to the user.

## Inheritance use cases

If data conforming to a JSON schema uses inherited values this presents a few issues that would need to be addressed:

1. The user needs to be informed that the value displayed is an override - this can be achieved via the additional metadata `badge` and `badgeDescription` which results in an icon and native tooltip. This should be added/removed if data is defined.
2. The JSON schema should validate the new data even though it is a subset of the data. An example would be that the JSON schema is an object that required property "foo", dataset A specifies this property and is inherited from dataset B. This means that the required property should be removed from the list of required properties. The best solution would be to have this controlled by the FormPlugin and can be addressed by #1611

Are there any other non-captured issues regarding an inheritance scenario?

**Comment by stirlaf** [comment]
A valuable feature for inheritance would be if the form can show the values that are being inherited to the user, when they are editing the child dataset.  This would require showing a mixture of inherited and local values and even whole inherited objects that do not exist locally.

E.g. Assuming two datasets A and B exist where A inherits from B, and they contain the below contents.  It would be useful for the user to see that they are inheriting p2 and also o2 with both of it's properties.  The user should then also be allowed to navigate to e.g. p4, where they could observe that its inherited value is v4 and then override it with a different value.  In this case, dataset B should have property p4 added to it with the new value, but p2 and p3 should still only be defined in Dataset A and therefore inherited from it.

Dataset A

    {
        o1: {
            p1: "v1",
            p2: "v2"
        },
        o2: {
            p3: "v3",
            p4: "v4"
        }
    }

Dataset B

    {
        o1: {
            p1: "I'm overridden"
        }
    }

**Comment by janechu** [comment]
@stirlaf I think this is a valid scenario, we currently have a PR to address this here: https://github.com/Microsoft/fast-dna/pull/1619

What that means for the schema in the example you presented is this:

```json
{
    "type": "object",
    "properties": {
        "o1": {
            "type": "object",
            "properties": {
                "p1" : {
                    "type": "string",
                    "default": "v1"
                },
                "p2" : {
                    "type": "string",
                    "default": "v2"
                },
            }
        },
        "o2": {
            "type": "object",
            "properties": {
                "p3" : {
                    "type": "string",
                    "default": "v3"
                },
                "p4" : {
                    "type": "string",
                    "default": "v4"
                },
            }
        }
    }
}
```

If a default is available and the data has not been set then it will show as an indicator and the default value will be present.

I think one of the more difficult questions might be how would we handle arrays? They could have a myriad of merging options. With the PR above what will happen is that you will be shown a list of items and will not be able to navigate to them to see their internal values. As an initial strategy I'm considering having an additional action that lets you "set" the default values as the current values in the dataset. This could also be used for other items, so if your string value is default "foo" you would have an interaction to just set it to "foo", this wouldn't prevent you from editing the value further, but it would essentially start you off with the default.

**Comment by stirlaf** [comment]
@janechu, thanks for sending the update.  I have one more scenario.  I'm not sure if the change addresses it or not, but I'll share it here so that we can verify.  It is where a dictionary of objects needs to be represented, and the inheriting dataset may override a subset of the values in the dictionary.

Below is an example where Dataset B overrides Dataset A.  The tricky thing is that there are two keys in the dictionary, so it's not possible to specify a default at the additional properties level of the schema, because at that level there's only one entry in the schema, but multiple entries in Dataset A.  Another option is to specify the entire Dataset A as a default at the root level.  However, in this case the expectation is that k1.p2 should still have a default of v12 and k2 a default of { "p1: "v21", "p2": "v22" }, even though a root value is specified in Dataset B.

Sample schema:

    {
        "type" : "object",
        "additionalProperties" : {
            "type" : "object",
            "required" : [
                "p1",
                "p2"
            ],
            "properties" : {
                "p1" : {
                    "type" : "string"
                },
                "p2" : {
                    "type" : "string"
                }
            }
        }
    }

Dataset A:

    {
        "k1": {
            "p1": "v11",
            "p2": "v12",
        },
        "k2": {
            "p1": "v21",
            "p2": "v22",
        }
    }

Dataset B:

    {
        "k2": {
            "p1": "I'm overridden"
        }
    }

**Comment by janechu** [comment]
I believe I understand the issue and have filed this task: https://github.com/Microsoft/fast-dna/issues/1652

This should allow the arbitrary keys on an object for a dictionary which contains the same sub-schema.

**Comment by janechu** [comment]
In two cases an issue occurs when having additionalProperties for arbitrary properties on an object and when using arrays, both of which result in defaults not be assignable to individual properties since you have a single definition mapping to multiple properties or array items. As such I have added an issue #1659 that will allow a default merge strategy where defaults are carried downstream.
