### ISSUE TITLE
BreakpointTracker.currentBreakpoint() return unexpected value if breakpoints was override.

### ISSUE THREAD

**Issue by Shpool** [Microsoft/fast-dna#1625]
Breakpoint tracker does not update Current Breakpoint value if breakpoins was set. As result, if Update() was not called, currentBreakpoint will return value calculated base on default breakpoint list.

Steps to reproduce the issue?
1. import BreakpointTracker;
2. set new list of breakpoints which is different from default breakpoint list.
3. call currentBreakpoint(). Value of breakpoint will not be from a new list of breakpoints.

Expected:
currentBreakpoint() returns value from new list of breakpoints corresponded to a current window width.

Environment:
* OS & Device: Win 10
* Browser Edge (44.17763.1.0), Chrome (73.0.3683.86 )

**Comment by chrisdholt** [comment]
@Shpool Do you want to send a PR?

**Comment by Shpool** [comment]
Yes.
