### ISSUE TITLE
Convert schema files to .ts

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast-dna#1632]
fast-dna maintains numerious schema files to facilitate GUI tooling. Currently, we define these JSON schemeas as `.json` files. 

I propose that we convert these to `.ts` files that export JavaScript objects representing the JSON schema. Doing so solves several problems:

1. No longer need to maintain build configs to enable importing a .json file into a .ts file, including typings and tsconfig settings. Schemas can simply be an ES import like every other piece of data.
2. Code comments - JSON does not allow comments and, while rare, somtimes commenting a schema file is usefull.
3. Code sharing - there are several areas, such as description strings and reference IDs, where we want to keep data in sync across schemas. This is significantly easier to in a programatic language.

**Proposed work:**
1. Convert all `*.schema.json` files to `*.schema.ts` 
a. each schema file should export the schema as default
2. Remove build-system configurations allowing JSON imports, typings, tsconfig, and webpack
3. Replace hard-coded schema id references with the `id` property of the imported schema
4. Update build process so that `tsc` builds the files into the distro - remove `copy-schemas.js`

**Comment by awentzel** [comment]
This sounds great. What is the impact on perf for removing these configurations?  Can you do an assessment of performance building with Lerna before we remove it all to create a baseline and then again after removing.  If we can shave even 30 seconds off build/test/release times this would be outstanding. 

Either way, I approve.

**Comment by awentzel** [comment]
Are there any downsides?

**Comment by chrisdholt** [comment]
Currently we export all of these as `.json` files. What is the implication on distributed packages (IE, breaking change?)?

**Comment by nicholasrice** [comment]
@chrisdholt we should probably treat it as breaking - we could add an interium build step to write out a `.json` version of the file to the distro, as well as a `.js` and keep it additive until the next major - or just do it for the next major.

@awentzel any build time changes will be pretty marginal.

**Comment by janechu** [comment]
I like this, it would definitely make our integration easier. If we want to avoid the breaking issue we might want to add a conversion step when packaging. There are a lot of open source libraries that do this so I don't foresee it being too cumbersome and it might be more intuitive if someone is expecting to use the JSON file format.

Also for the sake of discussion, JSON schemas are supposed to be self documenting, that is what the "title" and "description" fields (among others) are for. See: http://json-schema.org/understanding-json-schema/reference/generic.html#annotations

Having said that, there are always edge cases.

**Comment by janechu** [comment]
Converting this to a task since we are all agreed.
