### ISSUE TITLE
Reduce and standardize dependencies vs peer dependencies

### ISSUE THREAD

**Issue by nicholasrice** [Microsoft/fast-dna#1633]
There is currently many inconsistencies between packages establishing dependencies and peer dependencies. 

We should standardize - in general, we should enumerate the following external packages as peer dependencies:
- `lodash-es`
- `react`
- `react-dom`

Additionally, we should establish `@microsoft/fast-jss-manager-react` as a peer dependency. This is because significant problems can arise if multiple versions of `@microsoft/fast-jss-manager-react` is installed.

Establishing all other packages as dependencies ensures fast packages make available packages with compatible versions. It also makes the first-install much more user-friendly when there aren't numerous peer-dependencies that need to be installed.

**Comment by janechu** [comment]
This sounds good, it should reduce the complexity and hassle for consumers who are trying to use our packages.
