### ISSUE TITLE
Migrate repo to use yarn with workspaces

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast-dna#1634]
The primary advantage of yarn is the ability to cache package dependencies for future installs. This feature alone is extremely valuable and reduces bootstrapping time to practically zero.

Lockfiles also seem to offer more predictable behavior, which would allow us to cache dependencies in the CI process - greatly speeding up build gates.

Initial investigations into migrating the repo proved straight-forward and simple.

**Comment by chrisdholt** [comment]
I think we still want this - reopening.
