### ISSUE TITLE
Add "name" property to Radio

### ISSUE THREAD

**Issue by camsmithmicrosoft** [Microsoft/fast-dna#1639]
**What feature are you requesting?**

**What would be the benefit of adding this feature?**

**What solution would be ideal for you?**

**What alternatives have you considered?**

**Is there any additional context for your request?**

**Attach screenshots or images add detail to your request:**

**Comment by camsmithmicrosoft** [comment]
It would be nice to be able to set group names to the <input type="radio"> elements that are in Radio elements with a name prop on Radio

**Comment by chrisdholt** [comment]
Thanks @camsmithmicrosoft - this seems like a valid request and a gap in the current implementation as name is passed to the root element via unhandled props.

**Comment by chrisdholt** [comment]
I think we have the same issue with checkbox as well, so we should likely change this in both places.
