### ISSUE TITLE
Update a11y for Button component

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#164]
### Expected behavior 
Raise the bar to grade C accessibility
### Actual behavior
Evaluate current behavior and make updates to reach expected behavior

**Comment by chrisdholt** [comment]
Moving alias’ to Bcc.

Hey Mat – I don’t think we need to support input[type="submit"] in our implementation. The button element offers all functionality that the input button has but supports more rich UI features (text, image, etc). If our browser support matrix supported significantly older IE browsers, I could see this being necessary, but I think with our current matrix this is acceptable.

If there were a semantically meaningful differentiation I think there could be a case to be made, but I don’t know that there is one when it comes to button VS.  input[type=”submit”].

- C

**Comment by Wilto** [comment]
With you on all points, here.
