### ISSUE TITLE
component is blend in with background in card component

### ISSUE THREAD

**Issue by Shpool** [microsoft/fast-dna#1648]
Card component style has background: designSystem.backgroundColor, which make it always blend with background in any theme.

Styles: https://github.com/Microsoft/fast-dna/blob/master/packages/fast-components-styles-msft/src/card/index.ts

**What are the steps to reproduce the issue?**

Example:

1. create card component
2. set design system background
3. card component will blend with background.

**What behavior did you expect?**
Fill swatch from neutral pallet applied. e.g. neutrallFillRest or no background set.

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

* OS & Device: Windows 10
* Browser Edge, Chrome

**Is there any additional context?**

**Comment by Shpool** [comment]
Hi, I have a question related to card component. After update to a new color system i had impression that component background should take value from neutral pallete instead of designSystem.backgroundColor. So i wonder is this part of legacy left before new color system or there is intention to leave as is?

**Comment by chrisdholt** [comment]
@bheston Can you take a look at this and advise?

**Comment by nicholasrice** [comment]
It isn't part of the legacy color system but it is a gap in the existing one.

Cards are an interesting case, in that they act both as a control and a context provider for other controls. They need to:
1. Derive their color from their context background color.
2. Supply all child components the derived card background color.

To satisfy 2, we need to implement a `DesignSystemProvider` to set the background context for child components - but for performance reasons I don't think we actually want to embed the provider into every card.

One solution would be to add a `CardContainer` component which derives and provides the card background color. For instance, if the page has some grey background, the `CardContainer` could derive a `#FFF` background color and provide that color via a single `DesignSystemProvider`. The downside to this approach is that it's harder to use (you have to know you need to wrap cards in a `CardContainer` but it circumvents the perf issue we would encounter if all cards created their own design-system.

**Comment by bheston** [comment]
@nicholasrice and I have discussed this before and came to the options he mentions here. Until we have some sort of container component, it sounds like the best approach is to create a shared design system somewhere and reference it for all cards. If there were only a few cards I suppose this would not be necessary. If you want to use the neutral ramp more directly, you can reference the steps, where 0 (#FFF) is for the cards and 2 (#F7F7F7) is for the card container. And lower levels remain offsets 4, 6, and 8. The guidance is current and correct, but there's currently no utility for making this more automatic in code.

**Comment by Shpool** [comment]
@nicholasrice Got it. Will try to create shared Design system for Cards and look how it goes.

**Comment by bheston** [comment]
I just saw this marked stale, but wanted to reference that #1964 that was just merged adds a neutralLayerCard recipe to address this issue.
