### ISSUE TITLE
Investigate selected class name not being removed on Radio

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast-dna#1664]
**Describe the bug; what happened?**
Selected class name seems to be no getting removed when implementing multiple `<Radio />` components that are part of the same "group"

**What are the steps to reproduce the issue?**
Implement multiple `<Radio />` components and set there `name` prop to the same value. 

**What behavior did you expect?**
When you select another `<Radio />` in the group it should remove the selected  class name from the others.

**Comment by nicholasrice** [comment]
@eljefe223 does this repro when all components are uncontrolled?

**Comment by eljefe223** [comment]
> @eljefe223 does this repro when all components are uncontrolled?

I believe so. @khamudom tried implementing `<Radio />` in settings and used the `name` prop @chrisdholt added.
