### ISSUE TITLE
Fix "method_complexity" issue in packages/fast-colors/src/color-palette.ts

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast-dna#1678]
Function `rescale` has a Cognitive Complexity of 22 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-colors/src/color-palette.ts#issue_5cb78212833d5e0001000480

**Comment by SgiobairOg** [comment]
Having a look at this if that's okay.

**Comment by awentzel** [comment]
closing as no longer relevant.
