### ISSUE TITLE
The default glyph is not vertically centered in Select

### ISSUE THREAD

**Issue by camsmithmicrosoft** [Microsoft/fast-dna#1691]
![image](https://user-images.githubusercontent.com/43622870/56392904-9d8b4300-61e7-11e9-91eb-b19a62339b03.png)

**Comment by chrisdholt** [comment]
Thanks @camsmithmicrosoft. It looks like this is primarily an issue on the viewbox of the SVG itself. The position of the glyph wrapper appears to be in the correct place.

**Comment by chrisdholt** [comment]
Should be fixed with #1695 

<img width="730" alt="Screen Shot 2019-04-18 at 8 30 53 PM" src="https://user-images.githubusercontent.com/13071055/56404015-2078c180-6219-11e9-9c47-a03645a46e38.png">
