### ISSUE TITLE
Pivot, 2nd example looks broken with empty string for first Pivot 

### ISSUE THREAD

**Issue by eljefe223** [Microsoft/fast-dna#1694]
**Describe the bug; what happened?**
![image](https://user-images.githubusercontent.com/37851214/56401966-4057b780-6210-11e9-8a85-846886399ba0.png)

This appears to be broken but was actually done to mimic tab examples in the Base package. This example does not not provide any real world value so it would be my recommendation to remove the example all together.

**Comment by chrisdholt** [comment]
@eljefe223 is this a bug though? If it is, I think we should investigate it. It seems broken from what I can see - can you elaborate on why this behavior is expected so we can understand the solution of just removing the second example?

If this isn’t a bug, we can just close this issue - it doesn’t make sense to me to track an issue for removing the second example.
