### ISSUE TITLE
The color of a checkbox's checkmark cannot be changed

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast-dna#1704]
Because we're using a background image with a static fill value, there is no way to override the color of the checkmark. We should provide a mechanism to change this.

**Comment by mdtauk** [comment]
If not a specific option to set the colour, it should always have a passing contrast colour to the colour for the background of the checkbox.

**Comment by chrisdholt** [comment]
I believe we are pushing contrast here using the color system so we should always have an accessible value: https://github.com/microsoft/fast-dna/blob/master/packages/fast-components-styles-msft/src/checkbox/index.ts#L42
