### ISSUE TITLE
Change the type of "value" to any in SelectOption and Select

### ISSUE THREAD

**Issue by camsmithmicrosoft** [microsoft/fast-dna#1705]
Currently the "value" of a SelectOption and the returned parameter newValue of Select's onValueChange are typed to be a string. It would be nice if this supported numbers, Objects, arrays, etc. Could we make this be type "any"?

**Comment by nicholasrice** [comment]
What is the use-case for this? How would this translate to the underlying HTML, where a value attribute *must* be a string?

**Comment by camsmithmicrosoft** [comment]
The only requirement for this to be a string is for form submission. My proposal is that this could use toString for the underlying <select> value for form submission as consumers of <Select> should understand that form submission values will be strings. If the consumer doesn't want to have form submission, and wants to use numbers as values, it is convenient to not have to toString() and Number() the values
