### ISSUE TITLE
High Contrast mode does not work for Icon Buttons

### ISSUE THREAD

**Issue by connorjsmith** [microsoft/fast-dna#1715]
**Describe the bug; what happened?**
Buttons which use SVGs/icons seem to not be setting color correctly, making the icon nearly invisible.

**What are the steps to reproduce the issue?**
1. Enable High Contract mode in Windows10
2. https://explore.fastdna.net/components/button/examples/
3. Observe the incorrect icon color

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/5892363/56759046-db8ae880-674c-11e9-98ce-0c0d0df33ce1.png)
**In what environment did you see the issue?**

* OS & Device: Windows 10 Desktop in high contrast mode
* Browser: Edge (but probably any browser which respects HC settings)
* Version: 1809

**Comment by chrisdholt** [comment]
@connorjsmith This is helpful, thanks. It looks like this is related to instances where the appearance property is not set to "primary".

**Comment by connorjsmith** [comment]
Also looks like none of the buttons handle high contract focus states, making it impossible to know which button has focus
