### ISSUE TITLE
Add color support to input hints

### ISSUE THREAD

**Issue by adkaufm** [microsoft/fast-dna#1722]
Please add colors support to the input box hints (and any other transient ui).

The benefit would be that these hints could match website theming that's done with fast colors.

![image](https://user-images.githubusercontent.com/44783604/56933563-41ed6f00-6a9d-11e9-8d76-0acaab177e3f.png)

**Comment by nicholasrice** [comment]
@adkaufm can you elaborate a bit on this? What is creating that tooltip and how can I get a repro of the screenshot?

**Comment by adkaufm** [comment]
This is TextField in fast-components-react-msft. The tooltip shows up when the textfield is required={true} and you try to submit the form. It would be great if this tooltip used the fast color system, so that the styling matched the styling of the textfield.

**Comment by nicholasrice** [comment]
Great thanks @adkaufm! We'll look into it.
