### ISSUE TITLE
Slider is not using applyFocusVisible

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast-dna#1731]
**Describe the bug; what happened?**
`<Slider />` is using the default blue focus on the thumb. Update to use `applyFocusVisible`

Below is the implementation I used locally to fix:
```
slider_thumb: {
        ...applyFocusVisible<DesignSystem>({
            boxShadow: ensureDesignSystemDefaults(
                (designSystem: DesignSystem): string => {
                    return `0 0 0 ${toPx(
                        designSystem.focusOutlineWidth
                    )} ${neutralFocus(designSystem)},
                        0 0 0 1px ${designSystem.backgroundColor} inset`;
                }
            ),
            borderColor: neutralFocus,
        })
    }

```

**Comment by nicholasrice** [comment]
It looks like we are using `applyFocusVisible` to apply focus state to the thumb. Closing this issue. If you are still reproing please add additional details about what is happening vs what the expectation is.
