### ISSUE TITLE
manageJSS creates a class mismatch when rendering is supressed

### ISSUE THREAD

**Issue by janechu** [microsoft/fast-dna#1748]
When the React `shouldComponentUpdate` is used and suppresses a render cycle this can cause style mismatches where JSS updates the <style> and classes it creates but the `generateClassNames` in the React component is never hit.

The behavior was noted in a child component, this may have to do with new classes being generated on the parent component.

I would suggest either:

1. Document that `shouldComponentUpdate` can cause this to happen
2. Implement a way to suppress updating JSS classes if the render function isn't hit

**Comment by nicholasrice** [comment]
If the `JSSManager` updates a `<style>` - it will send those new class names to the child component. If the class names update, then the child component also needs to update to write those class-names to the DOM. If the child component's implementation of `shouldComponentUpdate` doesn't address changing props then that seems like a bug in that implementation - not a concern of the JSSManager.

If props aren't appearing as changed to the child component then we certainly need to address that, but if props are changing then I'm not sure what there is to document.

**Comment by janechu** [comment]
I agree, I think we should just document it.
