### ISSUE TITLE
glyph has a margin when there is no label content define in ActionTrigger component

### ISSUE THREAD

**Issue by khamudom** [microsoft/fast-dna#1755]
When you are only setting a glyph on ActionTrigger, there is a right margin on the glyph, used to space out the content.

To repo, using ActionTrigger stealth button, only set the glyph and not the children. Notice there is an extra 10px margin to the right of the glyph.

The behavior should have same pixel padding on left and right side of glyph.

**Comment by chrisdholt** [comment]
I don't repro this anymore. Closing for the time being - if this shows up again feel free to reopen.
