### ISSUE TITLE
Add scalable prop to typography

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast-dna#1759]
**What feature are you requesting?**
Add an optional `scalable` prop to typography that adds our density based functions (`...applyScaledTypeRamp()`) via className.

**What would be the benefit of adding this feature?**
This would allow `<Typograhy />` to respond to density changes from the design system if `scalable` is set too `true`.

This also allows us to continue to use `TypographyProps` as props for components and opt into text scaling.

**Comment by chrisdholt** [comment]
I've added a comment on this PR which was raised, but I am leaning towards just applying the scaled font by default: https://github.com/microsoft/fast-dna/pull/1760#pullrequestreview-238121370

It seems like density is something you apply into from a design system standpoint, so you can control where and when it gets applied.
