### ISSUE TITLE
Pane Resizing is mirrored in RTL 

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast-dna#1763]
**Describe the bug; what happened?**
Pane Resizing is mirrored in RTL.

**What are the steps to reproduce the issue?**

Example:

1. Implement Pane in RTL
2. Click and drag the resize handle
3. Dragging is mirrored

**Comment by nicholasrice** [comment]
@eljefe223 can you be more specific in your repro steps? How are you implementing RTL?

If you could put together a min repro on stackblitz that would be helpful.

**Comment by chrisdholt** [comment]
I’ll grab this - I noticed RTL issues when implementing #1977. I’ll add this for click and keyboarding.
