### ISSUE TITLE
Changing default text size causes rendering issues in Toggle

### ISSUE THREAD

**Issue by camsmithmicrosoft** [microsoft/fast-dna#1765]
The toggle resizes when text size is changed in the browser. The indicator then ends up misaligned. I would expect the toggle not to resize with text size

**Comment by chrisdholt** [comment]
Thanks @camsmithmicrosoft!

**Comment by nicholasrice** [comment]
@camsmithmicrosoft Thanks cam - I don't repro this issue, can you provide more detailed repro steps? Which browser are you using? How are you resizing text?

**Comment by camsmithmicrosoft** [comment]
![image](https://user-images.githubusercontent.com/43622870/58732102-5fb43980-83a5-11e9-9c98-77eccff554af.png)
![image](https://user-images.githubusercontent.com/43622870/58732106-62af2a00-83a5-11e9-9080-864906f55c87.png)

If I mess around with the styles that the toggle is inheriting on explore.fastdna.net I can repro. Basically you have to get to a point where font-size is not explicitly set for the toggle

**Comment by nicholasrice** [comment]
got it - I have the repro. thanks!
