### ISSUE TITLE
The listbox dropdown width expands outside the bounds of the Select.

### ISSUE THREAD

**Issue by camsmithmicrosoft** [microsoft/fast-dna#1766]
I would expect the listbox dropdown to inherit the width of the Select

![image](https://user-images.githubusercontent.com/43622870/57957781-58bffe00-78b2-11e9-9bb8-689e1262bf06.png)

**Comment by chrisdholt** [comment]
Adding @scomea. Would be great if we can ensure that the max and min widths are aligned between listbox and select.

**Comment by chrisdholt** [comment]
Closing this as it appears to have been fixed by #1775
