### ISSUE TITLE
Pivot preview TypeError

### ISSUE THREAD

**Issue by fmamic** [microsoft/fast-dna#1773]
**Describe the bug; what happened?**
In component explorer pivot preview is displaying TypeError.

**What are the steps to reproduce the issue?**
1. Go to https://explore.fastdna.net/components/pivot/ or open component explorer locally
2. Click on Pivot
3. See error

**What behavior did you expect?**
Pivot rendered correctly

**If applicable, provide screenshots:**

![image](https://user-images.githubusercontent.com/9407124/57984138-804ccd00-7a50-11e9-8c38-6aee72d34fb5.png)
![image](https://user-images.githubusercontent.com/9407124/57984140-893d9e80-7a50-11e9-8d7f-6006da2dd726.png)

**In what environment did you see the issue?**

Chrome
Version 74.0.3729.157 (Official Build) (64-bit)

**Is there any additional context?**
N/A

**Comment by chrisdholt** [comment]
@fmamic I think this has been solved with the move to the storybook implementation and the new component explorer. If you still repro this, feel free to open again!
