### ISSUE TITLE
color pickers don't work in Explorer site

### ISSUE THREAD

**Issue by bheston** [microsoft/fast-dna#1783]
**Describe the bug; what happened?**

In the component explorer, when adjusting the background or accent color, the design system does not get updated.

Also, updating design system form by entering a background color results in an error because the color is processed before typing is complete.

**What are the steps to reproduce the issue?**

- In the bottom right, update the background and accent colors.
- Observe the container background update, but not a neutral component.
- Observe an accent-colored component does not update.
- Update the "Background color" field in the design system form by typing something like #-8-0-8-0-8-0 (not pasting).

**What behavior did you expect?**

Design system values to be updated so component styles update.

Background color to be parsed if possible, otherwise not error the component display.

**If applicable, provide screenshots:**

![Explorer colors](https://user-images.githubusercontent.com/47367562/58190383-427abf00-7c71-11e9-8caf-7402c62fb4a7.png)

**In what environment did you see the issue?**

https://explore.fastdna.net/components/button/examples/, any browser, platform, etc.

**Is there any additional context?**

I suspect this was caused when we added the design system properties form. If you manually update the "Background color" field (focused in screenshot) the recipes adjust based on contrast, but not color.

**Comment by eljefe223** [comment]
@bheston this is related to the work Jane has been doing. Let's keep this in triage until we know the right person to work on this.

**Comment by janechu** [comment]
Assigning this back to @eljefe223.

The work I've done is in, this was an unforseen issue that only affects the explore site and not any of our exported packages. Can you take a look?
