### ISSUE TITLE
hover should not cause color changes in checkbox

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast-dna#1800]
1. Navigate to https://explore.fastdna.net/components/checkbox/
2. Disable the checkbox via the form
3. Hover over the checkbox

Actual: border color of checkbox changes when the checkbox is hovered
Expected: border color should not change when the checkbox is hovered

This bug also repos in Radio

**Comment by austin94** [comment]
I'd be willing to take a look at this one if it's still available. I'll take a deeper look this evening.

**Comment by nicholasrice** [comment]
That would be great! Thanks @austin94
