### ISSUE TITLE
JSS declarations in FAST

### ISSUE THREAD

**Issue by prabashn** [microsoft/fast-dna#1810]
**Describe the bug; what happened?**
It appears top-level selectors cannot be combined together using syntax like the following (which I would expect to work, but doesn't seem to be):

    "carousel_flipperPrevious, carousel_flipperNext": {
         // common styles
    },
    carousel_flipperPrevious: {
        left: "0"
    },
    carousel_flipperNext: {
        right: "0"
    }

**What are the steps to reproduce the issue?**
In a managed JSS style sheet where there are styles, for say 2 components A & B, you cannot seem to declare a top-level style such as "A, B": { … } and expect it to work.

Example:

    "carousel_flipperPrevious, carousel_flipperNext": {
         // common styles
    },
    carousel_flipperPrevious: {
        left: "0"
    },
    carousel_flipperNext: {
        right: "0"
    }

**What behavior did you expect?**
I expected the "common styles" section to get generated and applied correctly for both flipperPrevious/Next, but it doesn't seem to be.

**If applicable, provide screenshots:**
N/A

**In what environment did you see the issue?**
local testing

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Edge, Chrome, Safari, FireFox]
* Version [e.g. 1.8.0]
Chrome/Edge

**Is there any additional context?**
N/A

**Comment by nicholasrice** [comment]
This is actually a limitation with JSS itself - https://stackblitz.com/edit/typescript-qs7qwk.

Interestingly, the combination stylesheet in the above stackblitz seems to *almost* use the generated "b" class name.

**Comment by prabashn** [comment]
Agh, that sucks :-/
Thanks for looking into it Nick!

**Comment by nicholasrice** [comment]
yea - the best approach would be to do:

```
{
  carousel_flipper: {
    // common stuff
  },
  carousel_flipper__previous: {
    left: "0"
  },
  carousel_flipper__next: {
    right: "0"
  }
}

**Comment by prabashn** [comment]
Thanks @nicholasrice, that's a good suggestion :)
