### ISSUE TITLE
Carousel type error in Component Explorer

### ISSUE THREAD

**Issue by NicoM1** [microsoft/fast-dna#1811]
https://explore.fastdna.net/components/carousel/ displays 
"Something went wrong.
TypeError: Function expected"

**What are the steps to reproduce the issue?**

1. Go to https://explore.fastdna.net/components/carousel/

**What behavior did you expect?**

To see a preview of the carousel component

**If applicable, provide screenshots:**

![image](https://user-images.githubusercontent.com/6273562/58829945-f54a0600-85fd-11e9-9eb4-6ba287de6043.png)

**In what environment did you see the issue?**

* OS & Device: Windows 10 on PC
* Browser: Edge
* Version: 44.17763.1.0

**Comment by nicholasrice** [comment]
thanks @NicoM1

**Comment by nalogiudice** [comment]
Closing, as this was fixed with one of @janechu 's PRs recently
