### ISSUE TITLE
Opening a select doesn't collapse a different select

### ISSUE THREAD

**Issue by connorjsmith** [microsoft/fast-dna#1814]
**What are the steps to reproduce the issue?**
1. Have two `<Select>`s on one page
2. Open one of the Selects
3. Click the other select while the first select is expanded
4. Observe that both selects are open

**What behavior did you expect?**
The first select collapses

**In what environment did you see the issue?**

* OS & Device: Windows PC
* Browser Edge Canary
* Version  76.0.176.0

**Example repro**
```typescript
    private renderSelect(): JSX.Element {
        return (
            <Select
                onValueChange={this.onSelectChange}
                aria-label={this.props.accessibleSelectLabel}
                aria-details={this.props.accessibleSelectDetails}
                selectedItems={[this.generateIdForValue(selectedValue)]}
                jssStyleSheet={selectStyle}
            >
                {this.generateOptions()}
            </Select>
        );
    }

    private generateOptions(): JSX.Element[] {
        return this.props.options.map((option: Option) =>
              <SelectOption
                key={option.value}
                id={this.generateIdForValue(option.value)}
                value={option.value}
                displayString={option.displayName}/>
        );
    }
```
If I render two of these selects, I can get a repro

**Comment by nicholasrice** [comment]
Thanks @connorjsmith!

**Comment by nicholasrice** [comment]
@scomea is this something you can look at?

**Comment by chrisdholt** [comment]
@nicholasrice I think what we really want is to close the menu if something other than the menu itself is clicked, correct? The functionality that I see when I use native select is that I can't actually open the other select on the initial click - it closes the select and then I can open the second.

I can take this one.

**Comment by chrisdholt** [comment]
@connorjsmith I'm not able to currently repro this; can you add more details on the specific implementation/props for each of your `<Select />` components and I'll try and get a repro?

**Comment by connorjsmith** [comment]
@chrisdholt Added to the original post

**Comment by nicholasrice** [comment]
@chrisdholt yea, I would expect the transient menu to close on any click outside of the menu.

**Comment by scomea** [comment]
Now closes on menu blur
