### ISSUE TITLE
HOC Focus Manager

### ISSUE THREAD

**Issue by bekell** [microsoft/fast-dna#1822]
**What feature are you requesting?**
A virtualized list that displays a list of generic components.

**What would be the benefit of adding this feature?**
- A standard component to use for long lists with complex components
- Improved performance with virtualization
- Consistent and familiar accessibility functionality

**What solution would be ideal for you?**
- Minimally styled list component that accepts an array of generic list-item components
- Single & multi-select functionality for list-items
- Virtualized, rendering only what is visible
- Allows for lazy-loading list-items as the user reaches to the bottom of the list (via number of items or via arbitrary scroll length?)
- Vertical and Horizontal support
- Fully accessible, following W3 List accessibility standards
    - Support for modifier keys (shift + ctrl) for multi-select)
    - Support for focus hand-off to allow for internal list-item focus navigation

**What alternatives have you considered?**
- The FAST-DNA select component, however this does not support virtualization or focus hand-off

--- After discussions we decided a HOC Focus Manager might be a better solution

**Comment by nicholasrice** [comment]
I think we should create a component/components to manage keyboard behavior. They would manage keyboard behavior based on ARIA keyboard specs for supplied role types, ie tree-view and tree-view-item, select/option, etc. It would be great to make this config driven so behaviors could be defined for arbitrary attribute selectors, and even better if we can supply behavior for those selectors. How it all shakes out would need some investigation.
