### ISSUE TITLE
Add slide navigation callback to/in Carousel

### ISSUE THREAD

**Issue by prabashn** [microsoft/fast-dna#1825]
**What feature are you requesting?**
Need a callback prop on the Carousel for the parent to get notified when the user navigates back/forth between slides using click or keyboard. I need to be able to basically only need this for when the user initiates it (for example not when code triggers an active slide id change). So if you're exposing a generic callback for when next/prev is done, I need an argument to identify this is for an actual user initiated flip. I don't care about the programmatic change scenario, but if you decide to put it under the same callback, I need a way to distinguish between the two.

**What would be the benefit of adding this feature?**
MSN News Infopane experience's auto rotation feature. Currently I'm using a generic 'onclick' handler to stop the auto rotation, to indicate that the user has interacted with the carousel. But I will be missing things like the keyboard navigation, etc. 

So from the infopane perspective I need a way to start/resume from where the user left off, but if the user manually interacts with the carousel in the meantime, then I don't have a way to keep track of the *current slide id* to know which slide to flip to when the next auto-rotation timer fires.

**What solution would be ideal for you?**
A callback on the CarouselHandledProps to indicate that the user has navigated prev/next via mouse or keyboard (or any other mechanism that I'm unaware of).

**What alternatives have you considered?**
Resorting to using a blind 'onclick' handler to trigger the auto-rotation stop behavior.

**Is there any additional context for your request?**

**Attach screenshots or images add detail to your request:**

**Comment by prabashn** [comment]
To add, I also need the ability to "query" the current active ID. So as part of the callback, I would also need to get access to the "current active id". Otherwise there would be no straightforward way to get access to this data, and would essentially make it useless for my use case (which is to resume auto-rotation from where the user last left off)

**Comment by prabashn** [comment]
Also the direction that's navigating to will be needed for tracking purposes.

**Comment by chrisdholt** [comment]
@prabashn I think we would probably just send both the event and the props back as part of the callback. It seems like that would give you everything you could possible need.

**Comment by prabashn** [comment]
@chrisholt, you specifically mean the state props right? Not react props?

Another thing tracking actually needs is to get the internal DOM ref back so that tracking code can track the specific slide that's currently active. So being able to get a ref to that would be great as well. (We're currently using document.getElementById(slideId) to get access to this - not sure if that's OK or not, or whether we need a more 'react' way to get this)

**Comment by chrisdholt** [comment]
> @chrisdholt , you specifically mean the state props right? Not react props?
We'd give you what the component has so you can identify.

> Another thing tracking actually needs is to get the internal DOM ref back so that tracking code can track the specific slide that's currently active. So being able to get a ref to that would be great as well. (We're currently using document.getElementById(slideId) to get access to this - not sure if that's OK or not, or whether we need a more 'react' way to get this)

If we give you a fully "controlled" mode for carousel, I think that will solve this issue. That puts you squarely in control of managing the activeId of the carousel; so even in a situation where you are automating the rotation, you would be managing that. In a controlled instance, you always would have a reference to the active slide because you would have to set it, so I think that's the desired path forward.

**Comment by chrisdholt** [comment]
I think #1848 is related here as well.

**Comment by prabashn** [comment]
@chrisdholt 
Ideally, I don't want to overtake the internal Carousel navigation mechanisms (i.e., keyboard handling, button clicking, carousel indicator clicking, etc.) That should all ideally be handled automatically... we just need an event to get active id (this is the P0 wrt to this ask). Having a fully 'controlled' is OK, if that means we don't need to handle any UI events, etc. 

Maybe getting an idea of the proposed solution would be nice - because to me it sounds like we'd be handling all of that

**Comment by chrisdholt** [comment]
Sure, I'll see if I can dig more into the code and provide a proposal for this.
