### ISSUE TITLE
SlideTheme in Carousel is not exported

### ISSUE THREAD

**Issue by prabashn** [microsoft/fast-dna#1826]
**Describe the bug; what happened?**

**What are the steps to reproduce the issue?**
SlideTheme is an enum that's part of the handled carousel prop contract, but unfortunately it's not being exported (https://github.com/microsoft/fast-dna/blob/master/packages/fast-components-react-msft/src/carousel/index.ts) 

Example:
https://github.com/microsoft/fast-dna/blob/master/packages/fast-components-react-msft/src/carousel/index.ts

**What behavior did you expect?**
Export all types/enums related to exported prop contracts. Not sure if there are anything else like this throughout the codebase.

**If applicable, provide screenshots:**

**In what environment did you see the issue?**

**Is there any additional context?**

**Comment by chrisdholt** [comment]
Thanks @prabashn - PR incoming. I'll add you to it.
