### ISSUE TITLE
Move common color utilities to [fast-colors]

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast-dna#1840]
There are a few color utilities that I think would be helpful in a general sense that currently live in the MSFT package. Currently, none of the below common utilities are exported from the MSFT package. Instead of simply exporting those utilities from the MSFT package, I think it makes more sense to add those to `fast-colors` and export them there.

Since none of the common color utilities are exported from the MSFT package root, this change would not be breaking.

```
/**
 * Determines if a string value represents a color
 * Supports #RRGGBB and rgb(r, g, b) formats
 */
export function isValidColor(color: string): boolean {
    return isColorStringHexRGB(color) || isColorStringWebRGB(color);
}

/**
 * Determines if a color string matches another color.
 * Supports #RRGGBB and rgb(r, g, b) formats
 */
export function colorMatches(a: string, b: string): boolean {
    return parseColorString(a).equalValue(parseColorString(b));
}

/**
 * Returns the contrast value between two colors. If either value is not a color, -1 will be returned
 * Supports #RRGGBB and rgb(r, g, b) formats
 */
export const contrast: (a: string, b: string) => number = memoize(
    (a: string, b: string): number => {
        const alpha: ColorRGBA64 = parseColorString(a);
        const beta: ColorRGBA64 = parseColorString(b);

        return contrastRatio(alpha, beta);
    },
    (a: string, b: string): string => a + b
);

/**
 * Returns the relative luminance of a color. If the value is not a color, -1 will be returned
 * Supports #RRGGBB and rgb(r, g, b) formats
 */
export function luminance(color: any): number {
    return rgbToLuminance(parseColorString(color));
}
```

**Comment by nalogiudice** [comment]
Makes sense to me. I would definitely look for `isValidColor()` in the _color_ package before looking in MSFT.

**Comment by nicholasrice** [comment]
`fast-colors` already has functions for most of these - these functions are wrappers for those that make working with our JSS implementation easier.

The only function that isn't already captured in the library is `isValidColor`. We do have a generic color parser though, which returns `null` the input cannot be converted to a color.

**Comment by janechu** [comment]
If @nicholasrice is saying we already have a color parser that returns null if it can't be converted then isn't that the equivalent functionality?
