### ISSUE TITLE
Unable to properly animate slides in Carousel

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast-dna#1843]
**Describe the bug; what happened?**
Using pure css I'm able to animate the next slide in. However, the current slide disappears because we are setting the `tabPanel__hidden` `display` property to `"none"`. 

**What behavior did you expect?**
The previous and next slide should remain visible so when you animate to the next or previous slide the current slide remains visible until it animates outside the bounds of the component.

**Comment by nalogiudice** [comment]
Hidden class needs to be set on every `tab-panel` + 1 and -1 of the activeId. This will allow animation from the current panel out and the next one in.
Looks like this logic needs to change:
```
    /**
     * Generates class names based on props
     */
    protected generateClassNames(): string {
        return this.props.active
            ? super.generateClassNames(get(this.props, "managedClasses.tabPanel"))
            : super.generateClassNames(
                  `${get(this.props, "managedClasses.tabPanel", "")} ${get(
                      this.props,
                      "managedClasses.tabPanel__hidden",
                      ""
                  )}`
              );
    }
```

**Comment by eljefe223** [comment]
Add an opt in prop name `animatable` to tab-panel.tsx and pass up to `<tabs/>` that changes the assignment of `tabPanel__hidden` logic.

**Comment by nalogiudice** [comment]
@chrisdholt thoughts?

**Comment by chrisdholt** [comment]
closing this - would prefer to handle this with #2226.
