### ISSUE TITLE
Expose flippers in carousel

### ISSUE THREAD

**Issue by nalogiudice** [microsoft/fast-dna#1848]
**What feature are you requesting?**
Flippers are not currently exposed in the carousel component but need to be passed unHandled props for various reasons (telemetry, style, etc.)

**Comment by chrisdholt** [comment]
Is there a proposal on an implementation here? This seems more like a bug to me; I'm unable to customize and wire in a given control, etc...

**Comment by nalogiudice** [comment]
Besides an ask for this functionality, no. Semantically speaking yes, when we baked the flipper shape is baked directly in the carousel we should have provided means to accessing that control.

**Comment by chrisdholt** [comment]
I think this can be as simple as creating optional render props for the time being and those can get slotted in and have the onClick passed. For now, perhaps that means we add that and then we create a new task for vNext where we remove the actual flippers. Flippers on the carousel are technically not a requirement IMO.

**Comment by nalogiudice** [comment]
So in that case, if the consumer passes those render props we'll just use their incoming flipper instead of our flipper, correct? And the sequence indicators are the only required control in this case?

**Comment by chrisdholt** [comment]
I'm going to try and take care of this in conjunction with #1848.

**Comment by chrisdholt** [comment]
PR up with 2136 to solve this as a non-breaking change
