### ISSUE TITLE
Selection dropdown menu focus state gets changed when users type Space key as part of search string

### ISSUE THREAD

**Issue by shaohaolin** [microsoft/fast-dna#1859]
**Selection dropdown menu focus state gets changed when users type Space key as part of search string**

**What are the steps to reproduce the issue?**

Example:

1. Go to a select component with country names as select options.
2. Type United States
3. The select dropdown menu get closes once users enter space key.

**What behavior did you expect?**
United Stated option should be in focus state.

**Is there any additional context?**
If space key is the first key an user presses, it acts selection operation in a single selection; otherwise, it should be part of search string.

**Comment by nicholasrice** [comment]
Thanks @shaohaolin - this example has the implementation described above: https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html

Space will *open* a listbox, but it will not close it.

**Comment by shaohaolin** [comment]
Based on the w3 spec: https://www.w3.org/TR/wai-aria-practices-1.1/#Listbox
Space should be part of the search string if users type multiple characters in rapid succession.

> Type-ahead is recommended for all listboxes, especially those with more than seven options:
Type a character: focus moves to the next item with a name that starts with the typed character.
Type multiple characters in rapid succession: focus moves to the next item with a name that starts with the string of characters typed.

**Comment by shaohaolin** [comment]
@nicholasrice I didn't see anything related to space key interaction for single selection element. In fact, in the [w3 spec](https://www.w3.org/TR/wai-aria-practices/#listbox_kbd_interaction) it says:

> Recommended selection model -- holding modifier keys is not necessary:
Space: changes the selection state of the focused option
