### ISSUE TITLE
Search selection options without open the selection dropdown menu

### ISSUE THREAD

**Issue by shaohaolin** [microsoft/fast-dna#1860]
**What feature are you requesting?**
Search selection options without open the selection drop-down menu

**What would be the benefit of adding this feature?**
This allows users search options easily, reduce interaction.

**What solution would be ideal for you?**
When a selection component is in a focus state, users can type any characters in rapid succession including space key: focus moves to the next item with a name starts with the string of characters typed without opening selection drop-down menu.

**Attach screenshots or images add detail to your request:**
![image](https://user-images.githubusercontent.com/6677092/59470396-65217300-8dec-11e9-92b9-0697bf227549.png)

**Comment by nicholasrice** [comment]
@shaohaolin to clarify - you're not expecting the use to be able to physically type into the select, correct? It would set selection to the closest match from the provided key strokes?

**Comment by chrisdholt** [comment]
@nicholasrice I'll let @shaohaolin clarify his expectation; my assumption (and expectation) is that if I am focused on a given select and I type the letter "s" without it open, it would focus on the first `option` that starts with the letter "s". The behavior can be accomplished with the select example here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

What I **would not** expect would be that if I typed the letter "r" and there were not `options` starting with "r", it would focus on the next closest selection. That would be unexpected; I would expect it to do nothing.

If the ask is for the first, I think it mimics a native select and would be a valuable feature add here.

**Comment by shaohaolin** [comment]
@nicholasrice exactly what @chrisdholt said and the example that chris pointed out.

One thing I wanted to point out the example also support is: 
I am focused on a given select and I type the letter "d" withour it open, it goes to the dog option.
Wait about a second, I type the letter `p`, it goes to the parrot option.
