### ISSUE TITLE
Checkbox background color change error in FAST Component Explorer

### ISSUE THREAD

**Issue by fmamic** [microsoft/fast-dna#1866]
**Describe the bug; what happened?**
When changing background color in the FAST component explorer, type error happens.

**What are the steps to reproduce the issue?**
1) Open https://explore.fastdna.net/components/checkbox/
2) Click configure to open the form
3) Scroll to background color and remove one F from #FFFFFF
4) Error on preview

**What behavior did you expect?**
Component to render

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/9407124/59619232-f4e35c00-9121-11e9-9c26-b7936e311523.png)

**In what environment did you see the issue?**
Edge Chromium Version 74.0.84.0 (Official build) canary (64-bit)

**Is there any additional context?**

**Comment by nicholasrice** [comment]
This field is redundant. We should either remove the text input and rely on the color input, or remove the color input and then ensure the color is valid before assigning it to the background-color design-system property.

My preference would be to simply remove the text input.

**Comment by nicholasrice** [comment]
It also looks like this issue has been fixed - just not deployed. Closing.
