### ISSUE TITLE
Blank screen after changing width of the component in FAST Explorer

### ISSUE THREAD

**Issue by fmamic** [microsoft/fast-dna#1867]
**Describe the bug; what happened?**
Set the width of the component and then delete the value (so textbox is empty). Blank screen appears.

**What are the steps to reproduce the issue?**
1) Open https://explore.fastdna.net/components/checkbox/
2) Click Configure to open FAST form
3) Put width to 200
4) Remove 200
5) Blank page

**What behavior did you expect?**
Component to redner with default width

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/9407124/59619742-20b31180-9123-11e9-9f3a-9d4ccf6b0db0.png)
![image](https://user-images.githubusercontent.com/9407124/59619793-3f190d00-9123-11e9-8a01-f31347c5aec9.png)

**In what environment did you see the issue?**
Edge Chromium 
Version 74.0.84.0 (Official build) canary (64-bit)

**Is there any additional context?**

**Comment by nicholasrice** [comment]
Looks like this is fixed in master and is just not deployed. Closing.
