### ISSUE TITLE
Styles not getting applied to buttons on initial rendering in horizontal overflow

### ISSUE THREAD

**Issue by abhiyadav1323** [microsoft/fast-dna#1892]
**Describe the bug; what happened?**
Styles are not getting applied to the button when the component is rendered for the first time.
![image](https://user-images.githubusercontent.com/14785768/59954243-99261500-9438-11e9-9de4-1bceb2445374.png)
Buttons are coming on the left and as soon as I click on them they move to the right (where they should actually be rendered)
**What are the steps to reproduce the issue?**
Create a horizontal-overflow component and apply the below styles to the buttons.
``` 
horizontalOverflow: {
            position: "relative"
        },

carousel_button: {
            height: "40px",
            width: "40px",
            position: "absolute",
            top: "-4px",
            [applyLocalizedProperty("right", "left", config.direction)]: "0",
            transform: applyLocalizedProperty("translate(0, -100%)", "translate(0, -100%)", config.direction),
carousel_first_button: {
            transform: applyLocalizedProperty("translate(-100%, -100%)", "translate(100%, -100%)", config.direction),
            [applyLocalizedProperty("right", "left", config.direction)]: "4px"
        }
```
And the html snippet for buttons 
```
<Flipper direction={FlipperDirection.previous} slot={FlipperDirection.previous} 
className={this.generateClassNames([managedClasses.carousel_button, managedClasses.carousel_first_button].join(" "))} />

<Flipper direction={FlipperDirection.next} slot={FlipperDirection.next} 
className={this.generateClassNames(managedClasses.carousel_button)} />
```
**What behavior did you expect?**
Buttons to appear on the right.

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/14785768/59954474-bf988000-9439-11e9-9ee3-007480cc2831.png)

**In what environment did you see the issue?**

* OS & Device: Windows 10 on PC
* Browser: Edge Next

**Comment by chrisdholt** [comment]
Hey @abhiyadav1323 - Thanks for the robust issue!

I think you can actually simplify here. I see that you're passing your own classes and trying to access those in the same stylesheet. What may not be obvious is that we actually add a className to the flipper you are passing in. You can create a styled instance of horizontal overflow and pass your styles to the flippers using the stylesheet below:

```jsx
const styles = {
    // The root of the horizontal overflow component styles
    horizontalOverflow: {},
    // The overflow items container styles
    horizontalOverflow_contentRegion: {},
    // The overflow item(s) styles
    horizontalOverflow_item: {},
    // The next scroll control styles
    horizontalOverflow_next: {},
    // The previous scroll control styles
    horizontalOverflow_previous: {},
};

const MyCarousel = manageJss(HorizontalOverflowStyles)(HorizontalOverflow);

export { MyCarousel };
```

Then you can use it such as below:

```jsx
<MyCarousel>
        <Flipper direction={FlipperDirection.previous} slot={FlipperDirection.previous} />
        <Flipper direction={FlipperDirection.next} slot={FlipperDirection.next} />
        // Children
</MyCarousel>
```
I think that will help solve your problem.
