### ISSUE TITLE
Deprecate fast-development-site-react

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast-dna#1902]
# Proposal
Deprecate `@microsoft/fast-development-site-react` in favor of [StoryBook](https://storybook.js.org/)

I've done an initial implementation here: https://github.com/microsoft/fast-dna/tree/users/nirice/storybook-investigation

To see the example, run:
`git checkout users/nirice/storybook-investigation`
`lerna bootstrap`
`cd packages/fast-components-react-msft`
`npm start`

# What is storybook?
Storybook is a development environment that facilitates development of UI components. It organizes component example instances into "stories" that can be arbitrarily added / removed / organized, where each "story" is a fully implemented component instance. Storybook has integrations for most of the popular UI libraries/frameworks, as well as static HTML / Web Components. Storybook provides a very useful architecture for developing components in isolation, as well as a plugin architecture for meeting author-specific needs.

# What problem does storybook solve for us?
## Dev site circular dependencies
[Lerna](https://github.com/lerna/lerna) isn't the best at resolving circular npm dependencies, which means we can't use our own components in packages that *use* `@microsoft/fast-development-site-react`. This means none of the tooling work can use any of our `@microsoft/fast-components-react-base` and `@microsoft/fast-components-react-msft` components. By moving to storybook, we divorce the tooling from the component development experience and are free to use those components in those packages. 

## Maintenance of proprietary development site
The development site requires maintenance periodically to fix issues and bugs we find. Moving to an open source solution should reduce this burden because there are numerous other developers finding and fixing issues for us.

## Real world code examples
The development site currently generates component examples through a confusing abstraction. We effectively have large prop data blobs that get processed to work with our form generator, with the result of that processing mapped to a component. This leads to may headaches trying to figure out why the component won't render correctly or is throwing an obscure error.

By writing real-world example components, we are able to more accurately validate that a component is doing what it should be doing, gain the experience of implementing the component as an app author would, and provide more useful code references for app authors trying to implement a component. We also gain more flexibility on *how* to write component examples.

## Testing surface of automated tests, interaction and visual
Storybook provides a well structured document that could easily be used to run automated tests against. While we don't have automation tests currently set up, the nature of storybook is that each example can be fully-functioning and should therefore be a perfect test case to run automated interaction and visual tests against.

# How do we convert to StoryBook?
First, we will need top convert the existing MSFT development site to a stand-alone application. This will involve creating a new private package and migrating the existing app code from `@microsoft/fast-components-react-msft`. This will be the new source of [https://explore.fastdna.net/](https://explore.fastdna.net/). Once that migration is complete, we will be free to integrate `@microsoft/fast-components-react-msft` components into the `@microsoft/fast-tooling` package without causing circular dependencies.

Each component package will install and set up storybook through minimal configuration files. To provide consistency across our implementations, I've created a `@microsoft/fast-storybook-presets` package which will do most of the heavy lifting of installing / setting up plugins.

We will then need to convert all existing component examples to StoryBook examples. This will involve:
- Create a {component}.stories.tsx file in the component directory - see button and checkbox in @microsoft/fast-components-react-msft
- For each prop example in examples.data.tsx, create a "story" in {component}.stories.tsx
	
When developing components, it should be noted that the component will need to be tested in *both* the StoryBook application as well as the [https://explore.fastdna.net/](https://explore.fastdna.net/) application.

### Issues / things I've noticed about StoryBook:
- Building is a bit slower
- Documentation on plugin APIs is lack-luster
- Accessibility plugin is always validating text colors against #FFF background - need to figure out why

**Comment by awentzel** [comment]
Note:  https://explore.fastdna.net will be deprecated as well.  Instead we will use https://explore.fast.design which has already been setup on DNS and with Azure.  A pipeline will need to be created to build/release to this server (fast-explore).
