### ISSUE TITLE
Add a mock for manageJss in fast-dna-jss-react (or somewhere else)

### ISSUE THREAD

**Issue by shauntc** [microsoft/fast-dna#1916]
**What feature are you requesting?**
A mock of manageJss that returns static string values

**What would be the benefit of adding this feature?**
- More stable snapshots
- More readable snapshots

**What solution would be ideal for you?**
Something like this:
```typescript
import manageJss from "@microsoft/fast-jss-manager-react";

jest.mock("@microsoft/fast-jss-manager-react", () => {
  // @ts-ignore: requireActual does exist on jest
  const  fastJss = jest.requireActual("@microsoft/fast-jss-manager-react");
  return {
    ...fastJss,
    __esModule: true,
    default: () => {
      // tslint:disable-next-line:no-require-imports
      const React = require("react");
      return (Component: React.ComponentType<any>) => {
        return (inProps: {jssStyleSheet: object}) => {
          const jssStyleSheet = inProps.jssStyleSheet || {};
          const classNameGenerator = { get: (target, name) => {
            return `${name}` + (jssStyleSheet[name] ? ` ${name}-injected` : "");
          } };
          const classNameProxy = new Proxy({}, classNameGenerator);
          const outProps = {
            ...inProps,
            jssStyleSheet: undefined
          };
          return <Component {...outProps} managedClasses={classNameProxy} />;
        };
      };
    }
  };
});
```

that could then be imported into a test file like

```typescript
import "fast-dna-jss-react/manageJss.mock";
```

**What alternatives have you considered?**
- Use the unstyled component and pass in static class names
 - Manual for each component
 - Sub components that use manageJss (ie Typography, etc) still have generated classes
- Just deal with the occasional snapshot changes

**Comment by chrisdholt** [comment]
Thanks @shauntc - do you want to send a PR?

**Comment by nicholasrice** [comment]
An easier solution might be to customize the class name generator for your test files:

```
// In some test file
import { jss } from "@microsoft/fast-jss-manager-react";

jss.setup({
    createGenerateClassName: () => (styleRule) => styleRule.key // returns the key value the sheet rule being processed - this value is defined in the stylesheet itself so it won't change unless the sheet itself is changed
})
```

**Comment by shauntc** [comment]
@nicholasrice Seems like a much better solution, that would maintain the behavior of the JSSManager component. I will start using/recommending that ✅

Thanks!

**Comment by shauntc** [comment]
@nicholasrice @chrisdholt Is there a reason we couldn't use this method on our entire repo by running it in a jest setup file?

**Comment by nicholasrice** [comment]
I don't think so - not super familiar with your repo but all this would do is provide consistent class names across renders. If thats not a problem anywhere then you should be good.
