### ISSUE TITLE
Create tasks for each project for test coverage that doesn't include jest testing and coverageThreshold 

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#192]
### Expected behavior 
1. Each project should use jest (see colors for example)
2. Each project should use code coverage on jest
3. Each project should use coverage threshold
"coverageThreshold": {
      "global": {
        "branches": 50,
        "functions": 50,
        "lines": 50,
        "statements": -10
      }
    }
4. If unit tests are required to meet the threshold write them
5. Test until pass.
6. Write tasks for each project where this is not yet setup, assign, and do work.

**Comment by chrisdholt** [comment]
@awentzel can you add more detail as to which packages we want to add coverage for? I think there may be some that we don't actually want to add Jest to, such as class-name-contract packages, but in general I agree with this.

**Comment by awentzel** [comment]
There are already several projects that do not use Jest.  That is ok as long as there is no value in it. But, anywhere a UX exists or business rules there should be testing for 50% code coverage and 100% test coverage.

**Comment by awentzel** [comment]
Created new tasks #608, #609, #610, #611, #612, #613, #614
