### ISSUE TITLE
Add overflow information to horizontal overflow component

### ISSUE THREAD

**Issue by nalogiudice** [microsoft/fast-dna#1939]
**What feature are you requesting?**
Adding more overflow information to the horizontal overflow component, namely **which items are out of view**.

**What would be the benefit of adding this feature?**
This would allow easy usage of the `<HorizontalOverflow />` component in cases when the author is not using its basic "carouselling" behavior. For instance, a horizontal navigation menu with navigation items that are visible based on available screen-room and no flippers. The items that are hidden get added to an overflow menu.

**What solution would be ideal for you?**
Adding a prop that lets the author know what items are hidden (or partially hidden) - or - the inverse of this.

**What alternatives have you considered?**
After attempting to use horizontal overflow to create a horizontal navigation menu with the behavior described above, I ran into numerous problems. You cannot create a dynamic array of refs, so I am unable to simply assign a ref to the navigation items to access their underlying DOM with `ReactDOM.findDOMNode()` (which is not ideal anyway). Most other methods of trying to gather the size of DOM elements rely on this as well. **But**, horizontal overflow is _already_ doing these measurements - why not use them? It doesn't make sense to redo these measurements in a parent component.

It would be much simpler, cleaner, and more functional if the horizontal overflow component simply supplied the information.

**Comment by nalogiudice** [comment]
🚨 @janechu & @chrisdholt for visibility

**Comment by janechu** [comment]
What level of fidelity are we asking for here, because it would seem to be we have in view, out of view and then partials, which if you use the [intersection observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) you could have a lot of information should you need it.

**Comment by nalogiudice** [comment]
> _"...we have **in view**, **out of view** and then **partials**..."_

This seems like the desired fidelity to me - In my usage case, I would want to know what **is hidden** and **partially-hidden** (because I would choose to hide that item as well).

Are you suggesting using `IntersectionObserver` in `<HorizontalOverflow />` to supply this information as a prop/callback to the user, or are you suggesting I attempt to use `IntersectionObserver` in my current use-case and see if I can get the desired results without altering `<HorizontalOverflow />`?

**Comment by janechu** [comment]
Well if you want to perform some action like hiding an item when its partial, what if you want to hide the item when its clipped by 5%? Or 25%? At that point you need higher fidelity on what "partial" means. I would argue that you could include this as part of HorizontalOverflow and provide that information once clipping has started. It seems like there is already a callback "onOverflowChange" that returns an object that can supply this information.

**Comment by nalogiudice** [comment]
Correct, `onOverflowChange` was always meant to be added to with more datapoints - I totally forgot about that in the outline above - thanks for pointing that out.

> _"...what if you want to hide the item when its clipped by 5%? Or 25%? At that point you need higher fidelity..."_

Got it - good point. That seems like valuable information for the author to have. I can update the task to reflect this.
