### ISSUE TITLE
Update to improve code coverage

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#194]
Desired code coverage should not include any warnings or errors. Additionally, all thresholds should be at least 80 or higher.  
"coverageThreshold": {
      "global": {
        "branches": 75,
        "functions": 95,
        "lines": 85,
        "statements": 85
        }
    },

**Comment by Falkicon** [comment]
Duplicate of #192

**Comment by Falkicon** [comment]
Duplicate #192
