### ISSUE TITLE
Update coverage thresholds to 50% 

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#195]
current :
"coverageThreshold": {
      "global": {
        "branches": 29,
        "functions": 57,
        "lines": 67,
        "statements": 68
        }
    },

write tests where necessary to reach this goal.  50% is the goal.  It's more important beyond that to write unit tests tied to functionality and business rules than just arbitrary code coverage.

**Comment by Falkicon** [comment]
Duplicate of #192
