### ISSUE TITLE
Add typings for contextTypes and childContextTypes in DesignSystemProvider

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#196]
This task is related to overall code quality and type safety. 

contextTypes and childContextTypes are currently typed as `any` and ideally should be updated to have typings. If possible these should be typed as both generics AND static properties.

TODO Reference:
https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-jss-manager-react/src/design-system-provider.tsx#issue_5abfc3249ab05300010001d3

**Comment by Falkicon** [comment]
This task should be updated to include a description that describes that work to be done.
