### ISSUE TITLE
Add a onUserNavigation event to Carousel

### ISSUE THREAD

**Issue by prabashn** [microsoft/fast-dna#1966]
**What feature are you requesting?**
We need a way to stop auto-rotation of Carousel when we detect one of the following things.
- user clicks on left/right paddles
- user clicks on bottom slide nav indicators
- user hits left/right button to navigate

Currently we have generic onClick and onKeyDown handlers in Infopane code to "try to guesstimate" when a user has clicked on a navigation element. This logic is very fragile and is not accurate (and honestly does not belong in the Infopane level)

If we had a new event to indicate when a user initiated navigation happened (note that this should not trigger the same way the "active slide id" change event is raised as that event is triggered even if the auto-rotation advances the slide, for example).

So I'm proposing we add a new "onUserNavigation" callback that will be raised when a user explicitly uses one of the navigation affordances (mouse, keyboard, etc.) so we can distinguish this from a click like user clicking on a content slide to explicitly pause/resume the auto rotation.

**What would be the benefit of adding this feature?**
It would give a Carousel consumer to distinguish when a navigation event happened via a user action, so that we can stop the auto-rotation.

**What solution would be ideal for you?**
Above mentioned onUserNavigation event, or equivalent.

**What alternatives have you considered?**
Using the existing "active slide ID" changed event. This unfortunately does not let us distinguish between when the slide changed due to auto-rotation itself, or if it was due to a user navigation action.

**Is there any additional context for your request?**
Infopane experience.

**Attach screenshots or images add detail to your request:**

**Comment by chrisdholt** [comment]
@prabashn Is there a reason you cannot use `onFocus` events? The above are all focusable events and should bubble to notify that user interaction has taken place; the parent at that point (whatever is managing the autorotation prop) should pass a new prop of false to autorotation. I tested this scenario with the autorotation updates.

**Comment by prabashn** [comment]
We already have an 'onFocus' listener that *pauses* the auto-rotation (but not completely end it forever). We essentially need the above event to explicitly know when to *forever stop* the auto rotation (that is when the user interacts with the built-in Carousel navigation affordances)

**Comment by chrisdholt** [comment]
@prabashn if the carousel receives focus, a user has interacted with it - how else is focus brought to the carousel? I’m not understanding the difference here between what constitutes a pause in your implementation vs “forever”. When would focus be brought to the carousel without user interaction and what would trigger it to restart? Per the W3C spec for carousel, once a user interacts with the carousel, it should stop and it should only be restarted by the user: https://w3c.github.io/aria-practices/#carousel

> If the carousel has an auto-rotate feature, automatic slide rotation stops when any element in the carousel receives keyboard focus. It does not resume unless the user activates the rotation control.

**Comment by prabashn** [comment]
@chrisdholt  Focus can happen for example when the user is tabbing through the page components, and they happen to come across the infopane momentarily. So in this case we do not want to stop the auto rotate forever. Interaction (for our implementation) counts as keyboard navigation (left/right), clicking on paddles/indicators. 

In fact even if the user clicks on an article link in the infopane, we do not want the auto rotation to stop forever. In this scenario it will get paused until the user goes back to the tab where the infopane exists.

**Comment by prabashn** [comment]
To clarify, this is a feature we would need ideally in the longer term, when we switch to the new carousel. Currently I have hacks for all of these currently (keyboard left/right detection, non-anchor click detection, etc.) to stop the auto rotation forever. The reason I opened this is so we can track this requirement on the new carousel as not to forget to clean up all the hacks we have in place in the infopane experience.

**Comment by chrisdholt** [comment]
I believe this was closed with #1970 - includes a boolean value in the existing callback to notify if the event was not user initiated (was initiated by autoplay).
