### ISSUE TITLE
Update button appearance name to "accent"

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast-dna#1975]
We should deprecate the "primary" appearance name and implement "accent" - this maps directly to the terminology used in the color recipes.

**Comment by chrisdholt** [comment]
@nicholasrice I think we may want to convert this thread into a larger deprecation strategy for the “uber” button. Thoughts?

**Comment by nicholasrice** [comment]
@chrisdholt I think that can be a separate issue - this will just align terminology in the short term so that tooling packages are consistent with design language.
