### ISSUE TITLE
Add ability to ommit <div> tag when drawBackground: false to background component

### ISSUE THREAD

**Issue by Shpool** [microsoft/fast-dna#1982]
**What feature are you requesting?**
Add ability to omit "< div >" tags when we use background component with drawBackground: false property.

**What would be the benefit of adding this feature?**
Less DOM elements will be created if background used only as background context provider.

**What solution would be ideal for you?**
setting drawBackground: false would not produce additional < div >tags.

**What alternatives have you considered?**
Adding additional param which will work with drawBackground: false which will cause omit of < div > elements.

**Comment by nicholasrice** [comment]
Seems like a good idea - I think we should add another prop flag so we don't remove elements out from under current integrations that may be making use of unhandled props.

**Comment by chrisdholt** [comment]
Closed with #1983
