### ISSUE TITLE
Track on slider is not visible in windows high contrast modes

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast-dna#1984]
**Describe the bug; what happened?**
Slider track bar and knob are not visible in high contrast mode, which results in an inaccessible experience. 

**What are the steps to reproduce the issue?**

Example:
1. Turn on windows high contrast
2. Open edge browser
3. Go to https://explore.fastdna.net/components/slider/
4. See that the track bar is not visible

**What behavior did you expect?**
The slider track bar and knob are both visible and map accordingly to HC colors

**If applicable, provide screenshots:**
![slider_hc](https://user-images.githubusercontent.com/13071055/61471696-0ba2eb80-a938-11e9-9d4a-facf8f5d99c6.png)

**Comment by khamudom** [comment]
Update: screenshots with the fix implemented.
High contrast 1
![image](https://user-images.githubusercontent.com/37851220/61490457-d7dcbb80-a961-11e9-8475-71751e46809e.png)
High contrast 2
![image](https://user-images.githubusercontent.com/37851220/61490462-dc08d900-a961-11e9-9d2c-4138ac54ca32.png)
High contrast black
![image](https://user-images.githubusercontent.com/37851220/61490469-e034f680-a961-11e9-8a85-98b29ed977de.png)
High contrast white
![image](https://user-images.githubusercontent.com/37851220/61490479-e32fe700-a961-11e9-86bf-18898f814c30.png)
