### ISSUE TITLE
AutoSuggest component with dynamic suggestions is not accessible via keyboard

### ISSUE THREAD

**Issue by hchokshi** [microsoft/fast-dna#1989]
**Describe the bug; what happened?**
When rendering a controlled AutoSuggest that updates children `onValueChange`, pressing an arrow key to navigate through the suggestions will update the input value and cause the suggestions to change making it impossible to navigate to middle items in the suggestion list 

For example:
`New Y` suggests a list of locations, user wants to select the 2nd.
User presses down arrow to first entry `New York, New York, USA`, which updates the text input with this value.
Input value change causes suggestion list to update, hiding values that matched `New Y` but don't match `New York, New York, USA`.

**What are the steps to reproduce the issue?**
Render an `<AutoSuggest>` component that changes its children `onValueChange` in *controlled* mode. There is an `onInvoked` handler which will update the user's settings when they select a location.

`onValueChange` will update the user input value in parent component state, and make an API request for new suggestions. New suggestion API result will update props on the parent and the parent renders new `AutoSuggestOption` children.

When the user starts navigating the menu, it changes the text input and triggers a new set of suggestions (that may not show the user's desired choice).

**What behavior did you expect?**
Navigating suggestions would not trigger `onValueChange` or would provide some other mechanism to ensure that the suggestions can be left as-is for the user.

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/10136407/61499859-90642880-a97d-11e9-810e-66a4cfb2f1e5.png)

*Press down arrow*

![image](https://user-images.githubusercontent.com/10136407/61499863-91955580-a97d-11e9-9aeb-5d4b4a9ba2ef.png)

**In what environment did you see the issue?**
* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC] - Any
* Browser [e.g. Edge, Chrome, Safari, FireFox] - Any
* Version [e.g. 1.8.0] fast-components-react-base@4.10.0

**Any other context**
Relevant code - https://github.com/microsoft/fast-dna/blob/master/packages/fast-components-react-base/src/auto-suggest/auto-suggest.tsx#L248

**Comment by chrisdholt** [comment]
@scomea can you take a look at this?

**Comment by scomea** [comment]
Proposed fix - https://github.com/microsoft/fast-dna/compare/master...users/scomea/autosuggest-limit-onchange

**Comment by chrisdholt** [comment]
closed via #2002
