### ISSUE TITLE
Investigate other UI frameworks to create a list of components for the CSS Editor

### ISSUE THREAD

**Issue by janechu** [microsoft/fast-dna#1994]
![Screen Shot 2019-07-19 at 3 57 35 PM](https://user-images.githubusercontent.com/7559015/61569801-fe702480-aa3d-11e9-8008-c8415c87e549.png)
Currently there are three components for the CSS editor which allow the change of:

1. Margin & padding
2. Width & height
3. Position

Future components:

Range #2053
Number pair #2057 
Border #2026 
Color picker #2025 
Box shadow #2052 
Radius #2058 
Thickness #2059

**Comment by bheston** [comment]
Updated with the form fields we will be adding at this point.
