### ISSUE TITLE
Outline on keyboard focus on slider thumb looks like its “pixelated”

### ISSUE THREAD

**Issue by poagra** [microsoft/fast-dna#2011]
Outline on keyboard focus on slider thumb looks like its “pixelated”

It should not look that way.

![image](https://user-images.githubusercontent.com/45394423/61857864-8e045000-aee2-11e9-99c9-503f1b72c052.png)

windows/chromium

**Comment by chrisdholt** [comment]
Unable to repro this. Closing unless this shows up again.
