### ISSUE TITLE
 Throttled callback not cancelled in componentWillUnmount

### ISSUE THREAD

**Issue by 1hw7** [microsoft/fast-dna#2022]
Throttled callback not cancelled in componentwillunmount for horizontal overflow.
fix: add this.throttledResize.cancel(); to componentwillunmount.

**Comment by nicholasrice** [comment]
per @1hw7 , adding `this.throttledResize.cancel()` to line 173 of horizontal overflow solves the issue.

**Comment by chrisdholt** [comment]
@nicholasrice I can grab this

**Comment by chrisdholt** [comment]
closed with #2133 Thanks @shauntc and @1hw7
