### ISSUE TITLE
Clicking on last marker/tick in the slider will not select the last value

### ISSUE THREAD

**Issue by poagra** [microsoft/fast-dna#2027]
1. Clicking on last marker/tick in the slider will not select the last value.
2. If you want to select item x you have to click on item “x+1” to make the selection. Selection of the smallest value works fine

In the screen shot, if we try to select last tick (with label "large"), the slider thumb will not move there or select the particular value.
![image](https://user-images.githubusercontent.com/45394423/62041765-10aa4980-b21a-11e9-9141-5652c3e14982.png)

If any tick or area around it is clicked, the value at that point should be selected.
For eg, if there is 1 unit difference between two ticks X and Y, then if we click anywhere in range [0, 0.5] unit, X should be selected otherwise Y.

Windows/Chromium

**Comment by chrisdholt** [comment]
fixed by #2119
