### ISSUE TITLE
Address style issues with CSSEditor components

### ISSUE THREAD

**Issue by janechu** [microsoft/fast-dna#2048]
There appears to be styling inconsistencies with `<CSSBorder />` and `<CSSColor />` when applied to wider containers.

Address so that all inputs and other necessary elements align no matter what the width of the container is.

![Screen Shot 2019-07-29 at 6 09 32 PM](https://user-images.githubusercontent.com/7559015/62092922-16a92600-b22c-11e9-9418-5ac30ea3c118.png)

**Comment by bheston** [comment]
Per our discussion, use percentage based layout for these fields. The margin is fixed at 4px, and percentages can be derived from individual form field comps.

**Comment by eljefe223** [comment]
This has been fixed.

![image](https://user-images.githubusercontent.com/37851214/69201885-af71f300-0af4-11ea-842d-570c36c32cf7.png)
