### ISSUE TITLE
Investigate automated a11y testing solutions

### ISSUE THREAD

**Issue by Wilto** [microsoft/fast-dna#206]
Look into [axe-core](https://github.com/dequelabs/axe-core)/[Chisel](https://mseng.visualstudio.com/VSOnline/Keros/_packaging?feed=Keros&package=%40mskeros%2Fchisel&protocolType=Npm&version=1.133.1&_a=package) integration.

**Comment by awentzel** [comment]
Tried to implement Sonarwhal to no avail.  Too many issues to get through and possibly overkill at this point in time.  

Now recommending just implementing axe-core for minimal text-fixtures which will work very similarly to how we're doing snapshots now.  
https://github.com/dequelabs/axe-core/tree/develop/doc/examples/jest%2Breact

**Comment by chrisdholt** [comment]
Closing this issue as it's had no follow-up since Oct 2018
