### ISSUE TITLE
Badge should show underline on hover in high contrast

### ISSUE THREAD

**Issue by khamudom** [microsoft/fast-dna#2093]
**Describe the bug; what happened?**
There is no indication that badge is hovered or focus.

**What are the steps to reproduce the issue?**
1. Turn on Windows high contrast
2. Open Edge browser (I use Spartan Edge)
3. Go to https://explore.fast.design/components/badge
4. Hover over badge, you will see no indication that it is hovered

**What behavior did you expect?**
Should underline the text

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/37851220/62323039-3ffbc900-b45b-11e9-9f74-5db201eb914a.png)

**Comment by chrisdholt** [comment]
Are we sure - this is not an interactive element. What purpose does the underline serve for non-interactive UI?

**Comment by khamudom** [comment]
Closing this issue. Since Badge is not actionable in FAST, we do not want to add underline.
