### ISSUE TITLE
Card is missing outline in high contrast mode

### ISSUE THREAD

**Issue by khamudom** [microsoft/fast-dna#2094]
**Describe the bug; what happened?**
There are no outlines indicating if there is a card.

**What are the steps to reproduce the issue?**
1. Turn on Windows high contrast
2. Open Edge browser (I use Spartan Edge)
3. Go to https://explore.fast.design/components/card
4. Observe and see no card, just an image

**What behavior did you expect?**
There should be an outline around the Card
The bound of the Card should be mapped to the "Text" keyword.

**If applicable, provide screenshots:**
Default mode
![image](https://user-images.githubusercontent.com/37851220/62323842-0c21a300-b45d-11e9-9e71-9eb7a6a0f93b.png)

High contrast mode
![image](https://user-images.githubusercontent.com/37851220/62323830-02983b00-b45d-11e9-809f-a93c88ca35d5.png)

**Comment by chrisdholt** [comment]
@khamudom Cards are not interactive by nature - they are simply UI. Is there a requirement for UI boundaries to be visible in High Contrast Modes? What would this map to?

**Comment by khamudom** [comment]
The Card boundary, in high contrast, will be assigned the "Text" color. Having the border should not indicate the card as being interactive, or for decoration. The border will be helpful for organizing the UI.
