### ISSUE TITLE
Flyout Component is not exported from msft component package

### ISSUE THREAD

**Issue by shaohaolin** [microsoft/fast-dna#2101]
**@microsoft/fast-components-react-msft/dist"' has no exported member 'Flyout'**

**What are the steps to reproduce the issue?**

Updated "@microsoft/fast-components-styles-msft": "^4.19.0"

When tried to use Flyout component, it returns `node_modules/@microsoft/fast-components-react-msft/dist"' has no exported member 'Flyout`.

**Comment by shaohaolin** [comment]
Here is the index.ts link in fast-component-react-msft package: https://github.com/microsoft/fast-dna/blob/master/packages/fast-components-react-msft/src/index.ts

**Comment by chrisdholt** [comment]
PR is out; thanks @shaohaolin
