### ISSUE TITLE
Pane - Screen reader: Vertical separator is announced as button instead of a separator 

### ISSUE THREAD

**Issue by roryfa** [microsoft/fast-dna#2175]
This is the vertical separator that appears on the edge://favorites page, for example.

**Repro:** Move screen reader to the separator.

**Expected**: Screen reader user hears "separator" https://www.w3.org/WAI/PF/aria/roles#separator

**Actual**: Screen reader reads "button"

**Comment by chrisdholt** [comment]
Thanks @roryfa - we'll get this rolling!
