### ISSUE TITLE
Touch input in Slider component

### ISSUE THREAD

**Issue by ryanpcsm** [microsoft/fast-dna#2191]
**Describe the bug; what happened?**
The slider component thumb isn't supporting touch input.

**What are the steps to reproduce the issue?**
1. On a touch enabled device, navigate to https://explore.fast.design/components/slider
2. Attempt to touch and drag the thumb on the slider
3. Notice focus goes to the thumb but you can't slide it via touch

**What behavior did you expect?**
I expect to be able to touch and drag the slider in the same manner as with the mouse.

**In what environment did you see the issue?**

Windows 10, on Surfacebook and Surface Studio

Latest Edge Beta and Google Chrome

**Comment by chrisdholt** [comment]
I believe @scomea is looking into this.

**Comment by chrisdholt** [comment]
closed by #2213
