### ISSUE TITLE
Disabled Toggle is almost invisible

### ISSUE THREAD

**Issue by adkaufm** [microsoft/fast-dna#2215]
The toggle component in the disabled state is almost invisible against a white background.

1. Go to the component explorer and choose Toggle
2. Check the box for 'disabled'
3. Observe the toggle is so light-gray it's almost invisible. The hint text also has a weird gray background.

![image](https://user-images.githubusercontent.com/44783604/64212001-d6594b00-ce5c-11e9-9220-7f382c94159a.png)

It's even harder to see when you don't have any hint text:
![image](https://user-images.githubusercontent.com/44783604/64212035-eec96580-ce5c-11e9-9897-57d14038f990.png)

**Comment by chrisdholt** [comment]
This definitely looks to be a bug. What version are you seeing this in @adkaufm?

**Comment by chrisdholt** [comment]
@khamudom and @bheston for awareness

**Comment by adkaufm** [comment]
I'm using these versions:
    "@microsoft/fast-colors": "5.0.0",
    "@microsoft/fast-components-react-base": "4.14.3",
    "@microsoft/fast-components-react-msft": "4.19.3",
    "@microsoft/fast-components-styles-msft": "4.20.2",

But this is reproing in whatever versions are used in the Component Explorer as well

**Comment by chrisdholt** [comment]
@khamudom can you audit that file to see if there are some missing or incorrect selectors in the styles after your high contrast work? There was a similar issue in Button I believe.

**Comment by bheston** [comment]
Yeah, I was just noticing that as well. I have an open PR to add a "toggle" color that is for an update to components like this to make checkboxes and radio buttons toggle style like the toggle switch. It's #2210. In disabled mode it will then be that color at 30% instead of the really light color it is now.
