### ISSUE TITLE
Add server side support to Horizontal Overflow styling

### ISSUE THREAD

**Issue by minnieliu** [microsoft/fast-dna#2217]
File: fast-dna/packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx

Currently, horizontal overflow does not throw exception with server side rendering but the styling is off. Would be beneficial to add some workaround (e.g. default props) so that components rendered on the server side can still be styled.

**Comment by chrisdholt** [comment]
Updated the name here - the component technically supports SSR, but I believe the ask is for something that prevents the control from not visually showing up as height is 0. Perhaps a prop for default height could help here?

**Comment by erhuan-msft** [comment]
Default prop should satisfy the current requirement. Thanks!

**Comment by chrisdholt** [comment]
closed with #2472
