### ISSUE TITLE
Acrylic utility throws an exception when server side rendering

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast-dna#2220]
On line 4 there is no check for the document before referencing.

![](https://user-images.githubusercontent.com/19615595/64299303-9746fa80-cf2d-11e9-9451-35a2eff9e711.JPG)

**Comment by JamesBurnside** [comment]
@chrisdholt can you reopen this. The fix is currently incorrect as when canUseDOM is false, it will check the or statement `|| "-webkit-backdrop-filter" in document.documentElement.style;` thus trying to access the undefined document object.

This should most likely be:

    export const backdropFilterSupport: boolean = canUseDOM() &&  
        ("backdrop-filter" in document.documentElement.style || "-webkit-backdrop-filter" in document.documentElement.style);`

**Comment by chrisdholt** [comment]
Thx @JamesBurnside - want to submit a PR for this?

**Comment by JamesBurnside** [comment]
Sure !

**Comment by chrisdholt** [comment]
closed with #2357 (thanks @JamesBurnside!)
