### ISSUE TITLE
Classname generation to ensure same classnames are generated every time

### ISSUE THREAD

**Issue by k1mby** [microsoft/fast-dna#2227]
To support SSR we need classnames generated on the server to match classnames generated on the client. 

JSS let's us customize classname generation, it would be nice if manageJSS supported this.

**Comment by nicholasrice** [comment]
You can do this today by providing a custom JSS instance to the JSSManager - https://github.com/microsoft/fast-dna/tree/master/packages/fast-jss-manager-react#custom-jss-instance
