### ISSUE TITLE
Fix "nested_control_flow" issue in packages/fast-permutator/src/utilities/resolve-dependencies.js

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#224]
Avoid deeply nested control flow statements.

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-permutator/src/utilities/resolve-dependencies.js#issue_5ac7d9e6bb10750001000155

**Comment by janechu** [comment]
Will be resolved with #994.
