### ISSUE TITLE
Fix "nested_control_flow" issue in packages/fast-permutator/src/utilities/get-deep-prop-locations.js

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#225]
Avoid deeply nested control flow statements.

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-permutator/src/utilities/get-deep-prop-locations.js#issue_5ac7d9e7bb10750001000162

**Comment by janechu** [comment]
Will be resolved with #994.
