### ISSUE TITLE
ContextMenu and Select menus should have a different background level

### ISSUE THREAD

**Issue by connorjsmith** [microsoft/fast-dna#2250]
**Describe the bug; what happened?**
ContextMenus and Select menus appear "on top" of the background, so they should select a lighter background color (especially in dark themes). This makes it hard to distinguish a menu from the background when shadows are less apparent

**If applicable, provide screenshots:**

![image](https://user-images.githubusercontent.com/5892363/65185402-56b2ab00-da1c-11e9-8669-db1c7894592f.png)

We should probably be using a lighter grey, as seen in this native context menu
![image](https://user-images.githubusercontent.com/5892363/65185423-5f0ae600-da1c-11e9-8851-6a6abb0e8966.png)

**Comment by chrisdholt** [comment]
@bheston I think you are tracking this.

**Comment by connorjsmith** [comment]
Note that I could wrap the entire component in a BackgroundProvider, but this would affect the trigger of a Select and could lead to contrast issues

**Comment by bheston** [comment]
Yeah, found it. #2211.

**Comment by bheston** [comment]
Bumping this back up. Select has been fixed, but we need the same support in Context Menu. The background for the menu should also be neutralLayerFloating, which from what I can tell should produce the correct color for any of the supported design system configurations, using background color or luminance.

**Comment by chrisdholt** [comment]
@bheston are there any negative implications with updating/adding this *today*?

**Comment by bheston** [comment]
I don't believe so. Currently the background color is based on light / dark mode, which flips near the middle of the ramp. I looked at these possible configurations:
- current defaults (luminance: -1 / off, background: white, no layer recipes): currently it will render with a white background, and updating to the floating recipe will also render white.
- menu within background: if someone was already styling it according to guidance, say an L2 background for a content area with a Floating background containing the menu, L2 would render as expected, floating would render as white, and floating again applied within the menu would also render as white.
- The above should work the same in dark mode.

The only potential color swap I can think of is if the app is in the middle area of the ramp, it's possible the content background could be middle grey, but the backwards compatible portion of this style (no luminance setting) could make the floating layer white. This seems highly unlikely though.
