### ISSUE TITLE
Add ability to wrap menu in base select component

### ISSUE THREAD

**Issue by bheston** [microsoft/fast-dna#2266]
**What feature are you requesting?**
Ability to wrap or modify the menu portion of the base select component.

**What would be the benefit of adding this feature?**
This is currently possible for the trigger portion. In the styled component, the design system context cannot be set appropriately, because there is no way to define that the menu portion should start a different context based on a different background color recipe.

**What solution would be ideal for you?**
Please see #2211 and the comments thread including a proposed solution that seems like it would work.

**What alternatives have you considered?**
Alternatively we could redefine the entire menu in the styled component. That runs the risk of getting out of sync and having duplication.

**Comment by connorjsmith** [comment]
Hm unable to assign myself (I guess I'm missing some permissions), but I'm actively working on this

**Comment by scomea** [comment]
fixed by connonjsmith's merge
