### ISSUE TITLE
[Select dropdown auto closing when clicked on scroll when used as children of dialog popup]

### ISSUE THREAD

**Issue by gauravmahajan28** [microsoft/fast-dna#2276]
<Dialog
                contentHeight="auto"
                contentWidth="400px"
                labelledBy="dialogTitle"
                modal={true}
                visible={true}
                children={
                    <Select
                        placeholder={"Select an option"}
                        autoFocus={true}
                    >
                        <SelectOption
                            id={"21"}
                            value={"Select option 1"}
                            displayString={"Select option 1"}
                        />
                        <SelectOption
                            id={"22"}
                            value={"Select option 2"}
                            displayString={"Select option 2"}
                        />
                        <SelectOption
                            id={"23"}
                            value={"Select option 2"}
                            displayString={"Select option 2"}
                        />
                        <SelectOption
                            id={"24"}
                            value={"Select option 1"}
                            displayString={"Select option 1"}
                        />
                        <SelectOption
                            id={"25"}
                            value={"Select option 2"}
                            displayString={"Select option 2"}
                        />
                        <SelectOption
                            id={"26"}
                            value={"Select option 2"}
                            displayString={"Select option 2"}
                        />
                        <SelectOption
                            id={"27"}
                            value={"Select option 1"}
                            displayString={"Select option 1"}
                        />
                        <SelectOption
                            id={"28"}
                            value={"Select option 2"}
                            displayString={"Select option 2"}
                        />
                        <SelectOption
                            id={"29"}
                            value={"Select option 2"}
                            displayString={"Select option 2"}
                        />
                        <SelectOption
                            id={"30"}
                            value={"Select option 1"}
                            displayString={"Select option 1"}
                        />
                        <SelectOption
                            id={"31"}
                            value={"Select option 2"}
                            displayString={"Select option 2"}
                        />
                        <SelectOption
                            id={"32"}
                            value={"Select option 2"}
                            displayString={"Select option 2"}
                        />
                    </Select>

**Comment by chrisdholt** [comment]
I believe @scomea is actively working on this.

**Comment by scomea** [comment]
Fixed by https://github.com/microsoft/fast-dna/pull/2289
(missed this morning's publish, will be in next one)
