### ISSUE TITLE
Carousel component should be able to disable looping

### ISSUE THREAD

**Issue by bekell** [microsoft/fast-dna#2295]
**What feature are you requesting?**
The carousel component should loop by default (hitting next on the last slide goes to the first slide), but should have an optional prop to disable looping.

**What would be the benefit of adding this feature?**
Allows for better configuration to fit more use cases.

**What solution would be ideal for you?**
An optional boolean "loop" prop that defaults to true. When loop is set to false, on the first slide the previous button doesn't exist, and on the last slide the next button doesn't exist. This prevents the user from looping through the carousel.

**What alternatives have you considered?**
This may be possible by providing values to nextFlipper/previousFlipper, but seems a bit cumbersome.

**Comment by chrisdholt** [comment]
Thanks @bekell, I think we should add this to the proposal that @SethDonohue has out right now with #2226

**Comment by SethDonohue** [comment]
@bekell, I think this will take about a day, getting on it.

@chrisdholt will add it to the proposal for `@microsoft/fast-components-react-base` #2226
