### ISSUE TITLE
Fix "similar-code" issue in packages/fast-viewer-react/webpack.config.js

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#230]
Similar blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-viewer-react/webpack.config.js#issue_5ac8185fa18a74000100013e

**Comment by awentzel** [comment]
consider using the fast-development-site to eliminate webpack from viewer.

**Comment by janechu** [comment]
This no longer appears to be an issue.
