### ISSUE TITLE
Controlled mode keyboard tab navigation always triggers menu in AutoSuggest

### ISSUE THREAD

**Issue by hchokshi** [microsoft/fast-dna#2309]
**Describe the bug; what happened?**
When using the auto-suggest component in controlled mode (passing `value` prop, and updating it from `onValueChange`) with the keyboard, the suggestion menu is always triggered when tabbing out of the input text box.

**What are the steps to reproduce the issue?**
Create an auto suggest in controlled mode - `value={this.state.input}` and `onValueChange={value => this.setState ...}`. Create some mock function or something to population `AutoSuggestOption` children on input.

Tab to the input, type into it, select an option using the keyboard. When you press tab next, to move onto something else, the menu will trigger.

The root cause is because [`handleInputRegionKeydown`](https://github.com/microsoft/fast-dna/blob/af5f04a7c54c208f5475ec8ee0372bb1038f4411/packages/fast-components-react-base/src/auto-suggest/auto-suggest.tsx#L309) has a `default` case which calls `this.updateValue()` and `this.focusOnInput()`. `updateValue` always calls [`this.toggleMenu(true)`](https://github.com/microsoft/fast-dna/blob/af5f04a7c54c208f5475ec8ee0372bb1038f4411/packages/fast-components-react-base/src/auto-suggest/auto-suggest.tsx#L299) when `props.value !== undefined` which triggers the menu.

Additionally, the `focusOnInput` call makes this a key accessibility bug - if elements are covered by the auto-suggest menu, these elements are always hidden under the menu since you can't tab away from the input without opening the menu.

**What behavior did you expect?**
Pressing `tab` would not trigger the default case that opens the menu and refocuses the input.

**In what environment did you see the issue?**
Observed in Edge Chromium on Windows, would be reproducible on all supported browsers/OS.

* Version [e.g. 1.8.0]
`@microsoft/fast-components-react-base` - 4.14.3
Code is there in latest master, as of writing.

**Is there any additional context?**
The fix may be as simple as an empty `case (keyCode): break` for tab, depending on what the intended behaviour for tab with inactive menu is.

**Comment by chrisdholt** [comment]
Thanks @hchokshi - do you want to send a PR?

**Comment by hchokshi** [comment]
Sure @chrisdholt, I'll try push one by EOD today.

**Comment by chrisdholt** [comment]
Awesome, thx - will look for it!
