### ISSUE TITLE
getOwnPropertyDescriptor method in hoistNonReactStatics dependency used by fast-jss-manager-react is blocked by ad-blockers

### ISSUE THREAD

**Issue by simonli92** [microsoft/fast-dna#2326]
**getOwnPropertyDescriptor method in hoistNonReactStatics dependency used by fast-jss-manager-react is blocked by ad-blockers**

**Repo steps**

1. Install Nano Adblocker in edge chromium.
2. Go to https://www.msn.com/en-us/money/companies/boeing-737-max-investigations/sl-AAIw6eH
3. The page is blank.

**Expected: It should render the page.**

**Additional context**

Fast jss manager is using dependency [**hoistNonReactStatics** ](https://github.com/microsoft/fast-dna/blob/34d373842d345a0b32358b5e5e8fd1169605786b/packages/fast-jss-manager-react/src/manage-jss.tsx#L5).

[**hoistNonReactStatics** ](https://github.com/microsoft/fast-dna/blob/34d373842d345a0b32358b5e5e8fd1169605786b/packages/fast-jss-manager-react/src/manage-jss.tsx#L5) uses [getOwnPropertyDescriptor here](https://github.com/mridgway/hoist-non-react-statics/blob/3b368d8ae1f73f8fa60c9668ffee21468f8a4033/src/index.js#L91).

This is blocked by uBlock which is used in Nano Adblocker. [The uBlock filter is here](https://github.com/uBlockOrigin/uAssets/blob/1dec9f94b3b57c1419599606422f9115a1476e03/filters/filters.txt#L9180).
`!#if env_chromium
baggersmag.com,cbssports.com,chowhound.com,diversitybestpractices.com,floridatravellife.com,gamespot.com,goal.com,hotbikeweb.com,`**msn.com**`,popsci.com,scubadiving.com,sportdiver.com,streetchopperweb.com,superstreetbike.com,thoughtcatalog.com,utvdriver.com,workingmother.com`**##+js(aopw, Object.getOwnPropertyDescriptor)**

We can see if the env is chromium, it will block Object.getOwnPropertyDescriptor for msn.com.

This is a huge risk for any msn pages using fast-jss-manager. When users use adBlocker that has the same filter on chrome or edge chromium, they won't be able to see the pages.

**Suggestion: avoid using Object.getOwnPropertyDescriptor or any dependencies that use it.**

**Comment by nicholasrice** [comment]
Thanks @simonli92 - we'll look into this.

**Comment by nicholasrice** [comment]
Closing this - resolved by uBO: https://github.com/uBlockOrigin/uAssets/issues/6436
