### ISSUE TITLE
Fix "identical-code" issue in packages/fast-components-react-msft/app/index.tsx

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#233]
Identical blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-components-react-msft/app/index.tsx#issue_5acb891775f41c00010001c1

**Comment by awentzel** [comment]
Please validate this is no longer an issue once you fix #217

**Comment by chrisdholt** [comment]
closed with #217
