### ISSUE TITLE
Slider labels aren't anchored correctly

### ISSUE THREAD

**Issue by bheston** [microsoft/fast-dna#2386]
**Describe the bug; what happened?**

Sliders with labels at the min or max should be aligned such that they meet the edge of the control bounds and don't go outside of it.

**What are the steps to reproduce the issue?**

Configure a slider with long label text for the beginning and/or ending bounds

![image](https://user-images.githubusercontent.com/47367562/67538548-3ec1ed00-f694-11e9-9f90-87c08196352b.png)

**What behavior did you expect?**

The lower label aligns to the left extent of the control bounds (a few pixels left of the visible track)

**Comment by bheston** [comment]
Additionally, the label schema seems to be missing `label`, `showTickmark`, and `valuePositionBinding`.

**Comment by scomea** [comment]
I definitely need to update schema and docs for slider and labels, but the functionality is there if you define label positions using the "totalRangeMin/totalRangeMax" anchor values instead of a number:
            <SliderLabel valuePositionBinding={SliderTrackItemAnchor.totalRangeMin} label="Low" />
            <SliderLabel valuePositionBinding={50} label="50" />
            <SliderLabel valuePositionBinding={SliderTrackItemAnchor.totalRangeMax} label="High" />

**Comment by scomea** [comment]
I definitely need to update schema and docs for slider and labels, but the functionality is there if you define label positions using the "totalRangeMin/totalRangeMax" anchor values instead of a number: valuePositionBinding={SliderTrackItemAnchor.totalRangeMin}

**Comment by chrisdholt** [comment]
@scomea was this closed with the issue above?
