### ISSUE TITLE
Fix "similar-code" issue in packages/fast-components-react-base/src/image/image.tsx

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#239]
Similar blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-components-react-base/src/image/image.tsx#issue_5acd43ed4b1b320001000175

**Comment by awentzel** [comment]
Will be auto-resolved by feature update to breakpoints task that @chrisdholt is creating with details.

**Comment by chrisdholt** [comment]
Fixed this with an update for v3.0 so assigning to myself.

**Comment by chrisdholt** [comment]
Closing as the PR has gone into the release branch #914
