### ISSUE TITLE
Create performance matrix at compile time

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#24]
@awentzel commented on [Wed Jan 17 2018](https://github.com/Microsoft/fast/issues/20)

Evaluate wiring up something like https://www.sitespeed.io for build time analysis of perf 

1. Add in a command line argument to run BundleAnalyzer 
2. Add in a command line tool that writes out 
-- Total files,
-- Total css file size (min and non), 
-- Total JS file size (min and non), 
-- Total HTML home page file size (might be nice to actually write this as a code comment on each rendered page in SPA if possible, 
-- Total components
-- Total layouts
-- Total example

It might be actually even nicer to add this for the website as part of a commented out section in markup so at any time Jason or myself can view source and see friendly data matrix on code health.

**Comment by chrisdholt** [comment]
@awentzel Can you update this task to be more accurate based on the current state of things?

RE: number 2 above - We really only have JS being exported now, so the parts regarding HTML and CSS are obsolete. What website would this be for? We have the MSFT documentation site; is this necessary for that?

Regarding code health, is this still valid based on whats been added by Code Climate and our test coverage?

**Comment by awentzel** [comment]
Invalid. Can be closed

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
