### ISSUE TITLE
Fix "similar-code" issue in packages/fast-components-styles-msft/src/utilities/breakpoints.ts

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#240]
Similar blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-components-styles-msft/src/utilities/breakpoints.ts#issue_5acd43ed4b1b320001000176

**Comment by awentzel** [comment]
Will be auto-resolved by feature update to breakpoints task that @chrisdholt is creating with details.

**Comment by eljefe223** [comment]
Looks like this has been resolved

**Comment by chrisdholt** [comment]
reopening as this is still active and valid. Was marked as "won't fix" for some reason.

**Comment by eljefe223** [comment]
Duplicate: #239
