### ISSUE TITLE
Horizontal overflow OverflowChange event is not fired until resize in Microsoft Edge

### ISSUE THREAD

**Issue by hchokshi** [microsoft/fast-dna#2402]
**Describe the bug; what happened?**
Created a `HorizontalOverflow` with `onOverflowChange` prop that shows/hides buttons for scrolling the overflow container.

In Chromium based browsers and Firefox, there is an OverflowChange event that fires when the component mounts, letting the parent component update its state on whether there's an overflow on either side to show buttons for.

In Microsoft Edge, this first event is not fired when the page loads. It gets fired when the browser window is resized, even if the size of the component is not affected.

**What are the steps to reproduce the issue?**
Render a `HorizontalOverflow` as below, with enough children to cause overflow:

```tsx
const MyComponent: React.FC = ({ children }) => {
    const [{ overflowStart, overflowEnd }, setOverflowState] = useState<OverflowChange>({
        overflowStart: false,
        overflowEnd: false
    });

    return (
        <HorizontalOverflow onOverflowChange={setOverflowState}>
            {children}

            {/* Show flippers if there's content in that direction */}
            {overflowStart && (
                <Flipper
                    direction={FlipperDirection.previous}
                    slot={FlipperDirection.previous}
                />
            )}
            {overflowEnd && (
                <Flipper
                    direction={FlipperDirection.next}
                    slot={FlipperDirection.next}
                />
            )}
        </HorizontalOverflow>
    );
};
```

Open in Chrome/Edge Chromium, Firefox and Edge. Next button is initially visible without resize in browsers other than Edge.

**What behavior did you expect?**
Next button initially visible in all browsers.

**In what environment did you see the issue?**

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
Windows 10 Enterprise 1909

* Browser [e.g. Edge, Chrome, Safari, FireFox]
Microsoft Edge 44.18362.387.0
Microsoft EdgeHTML 18.18363

* Version [e.g. 1.8.0]
@microsoft/fast-components-react-base 4.18.2

**Is there any additional context?**

**Comment by scomea** [comment]
A bunch of these horizontal overflow bugs are related to this issue, working on a fix: http://lists.w3.org/Archives/Public/www-style/2014Apr/0438.html
