### ISSUE TITLE
Update a11y on header component

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#242]
1. Reuse the same component markup as on FW.Framework / Fluent Web
2. Comments from Mat "Honestly, this component is really solid as-is. The only recommendation I might make is modifying `NavigationMenu` to include `aria-labelledby` on subnav lists, pointing at the ID of the button that invokes them."

**Comment by chrisdholt** [comment]
@awentzel or @Falkicon - suggest closing this out and marking as obsolete, or moving to fast tracking for the following reasons:

- The component doesn't currently exist or have a plan in FAST
- If there is an issue to create the component, these task details could live there

**Comment by chrisdholt** [comment]
Issue moved to [Microsoft/fast-tracking #8](https://github.com/Microsoft/fast-tracking/issues/8) via [**ZenHub**](https://www.zenhub.com/)
