### ISSUE TITLE
Proposal: Add rtl scrollLeft helper utility

### ISSUE THREAD

**Issue by scomea** [microsoft/fast-dna#2437]
We have found a number of issues with the horizontal overflow component in rtl mode and have root caused them down to some really inconsistent behavior across browsers regarding how they handle element.scrollLeft in rtl.
http://lists.w3.org/Archives/Public/www-style/2014Apr/0438.html

I expect we'll encounter this issue in any component that uses scroll left.

I have worked up a mechanism to manage this and added it to my working branch for the HorizontalOverflow fix -
https://github.com/microsoft/fast-dna/commit/1397455078ba74838ad819215a2d974ecf8da535 
(in fast-web-utilities/src/localization.ts)

So far I have tested in Anaheim, Edge and Firefox.  Doesn't yet work in Chrome but I'm pretty sure I just need to tweak my math for one of the cases so shouldn't block discussing the approach.

The idea is that we have get/set function calls that test the browser the first time they are called and set the right conversion functions.  Trying to be performant as this function could get called a lot for ui's that animate scrolling.

The behavior we are "normalizing" to is as described here:
https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollLeft
"If the element's direction is rtl (right-to-left), then scrollLeft is 0 when the scrollbar is at its rightmost position (at the start of the scrolled content), and then increasingly negative as you scroll towards the end of the content."

**Comment by janechu** [comment]
I have added some comments to your linked commit, I believe this is a good objective and definitely a good feature to add to our web utilities.
