### ISSUE TITLE
Update Select component's accessibility

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#244]
In our current select, when open the menu and press a key "a", it does nothing. Instead I would expect the focus to move to any of the select items that start with "a". 

We should fix this and retest to ensure it's Grade C and optimized.

https://fluentweb.com/components/select

Example of this behavior: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select

**Comment by nicholasrice** [comment]
Blocked because this component does not exist yet.

**Comment by Falkicon** [comment]
It looks like this task was created based on the old Select component. @nicholasrice , we should review the comments above while you re-build Select.

**Comment by nicholasrice** [comment]
Closing this because Select is not a component yet. We can do this work in the task to create this component.
