### ISSUE TITLE
Change menu open functionality in AutoSuggest

### ISSUE THREAD

**Issue by eljefe223** [microsoft/fast-dna#2458]
**What feature are you requesting?**
Currently the menu opens on focus, while acceptable according to [ARIA spec](https://w3c.github.io/aria-practices/#combobox) this does not match what design wants or what we see in similar experiences like bing and google. 

> The popup is hidden by default, i.e., the default state is collapsed. The conditions that trigger expansion -- display of the popup --are specific to each implementation. Some possible conditions that trigger expansion include:
> 
> 1. It is displayed when the Down Arrow key is pressed or the Open button is activated. Optionally, if the combobox is editable and contains a string that does not match an allowed value, expansion does not occur.
> 2. It is displayed when the combobox receives focus even if the combobox is editable and empty.
> 3. If the combobox is editable, the popup is displayed only if a certain number of characters are typed in the combobox and those characters match some portion of one of the suggested values.

Suggesting to change the functionality to match the the 3rd option above. Or have some configurable prop to choose the current implementation or the one suggested here

**What would be the benefit of adding this feature?**
This would match other experiences we see elsewhere on the web.

![bing](https://user-images.githubusercontent.com/37851214/69265461-27383000-0b7e-11ea-927c-c779d0af89e5.gif)

**Comment by janechu** [comment]
I would like to see the second suggestion implemented:
> Or have some configurable prop to choose the current implementation or the one suggested here

My opinion is that we include a prop which accepts an enumeration of all of the expansion triggers and provide them as an array, so for example (if all three suggested behaviors are possible):

```js
["keyDownPress", "focus", "characterMatch"]
```

With some implementations adding extra props, perhaps `"characterMatch"` could default to `1`, but AutoSuggest could have another prop such as `characterMatchCount`.

**Comment by SethDonohue** [comment]
I don't see an issue with this change as it will still match ARIA spec.

**Comment by eljefe223** [comment]
I think we should also support filtering as that is related ot the menu being open or not.

> Alternatively, if a combobox supports text input, it is referred to as editable. An editable combobox may either allow users to input any arbitrary value, or it may restrict its value to a discrete set of allowed values, in which case typing input serves to filter suggestions presented in the popup.

That being said I think there are 2 possible scenerios both of which could support filtering. `filtering` could default to false and `menuTrigger` could default to the current implementation `menuTriggers.onFocus`. 

Mark-up suggestion:

**1. On focus.**

`<AutoSuggest menuTrigger={menuTriggers.onFocus}/>` or
`<AutoSuggest menuTrigger={menuTriggers.onFocus} filtering={true}/>

**2. On Key Down / On Click.**

`<AutoSuggest menuTrigger={menuTriggers.onKeyDown}/>` or
`<AutoSuggest menuTrigger={menuTriggers.onKeyDown} filtering={true}/>

**Comment by janechu** [comment]
I think the menu is always filtering isn't it? Otherwise you will start typing and the suggestions won't change, thus there is no "suggestion" so I believe it's implied in the name.

Do you mean to prevent any value other than the ones provided? Where the textbox you type in has a shadowed autocomplete to indicate that this is the current option being selected for once the user has submitted the value. To illustrate as you are typing the textbox would show something akin to:

> **My Curre***nt Autocompleted Value*

Where "My Curren" string is what is currently typed and "nt Autocompleted Value" is the shadowed autocompleted value, indicating what value would be set if the user submits this string.

If so I believe you want to add a prop that might be named `restrictToSuggestedValues`.

**Comment by eljefe223** [comment]
I'm talking about specifically filtering the options down in the menu based on what you type. So if there are no matches the menu does not display

Filtering menu options:
![ScreenRecording2019-11-20at14456](https://user-images.githubusercontent.com/37851214/69281270-d683ff80-0b9c-11ea-8b55-b9b3615c0a4d.gif)

Not filtering menu options:
![ScreenRecording2019-11-20at14813](https://user-images.githubusercontent.com/37851214/69281285-dd127700-0b9c-11ea-8757-9d0945246c55.gif)

**Comment by janechu** [comment]
I see, the portion of the aria spec you quoted was mentioning the filtering as well as restriction of values, so I thought you were including that as part of this discussion. Thanks for the context, I think your proposal makes sense. I would like to backlog the restricted values functionality since that is also valid behavior (not in this task but as a feature for later).

**Comment by eljefe223** [comment]
Jane and I chatted and agreed on adding two optional props:
```
export enum menuTriggers {
  onFocus,
  onKeyDown,
}
....
menuTrigger?: menuTriggers;
filterSuggestions?: boolean;
```

`menuTrigger` will default to `menuTrigger.onFocus`
and
`filterSuggestions` will default to `false`

**Comment by scomea** [comment]
I'd be careful about adding filtering here.  I would expect that the typical developer using this control is already doing that when they catch value change events, examine the new value and update children as a result.  Not sure this functionality would be well placed as an integral part of this component,

**Comment by janechu** [comment]
As a user I would expect the component to do filtering for me.
