### ISSUE TITLE
Remove cursor styles from MSFT typography component

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast-dna#2465]
**Describe the bug; what happened?**
We've had quite a bit of feedback from the community (typically through communication channels) about the cursor style on `Typography` causing problems. As a user, if I want to use the typography component and wrap it within an anchor (or for example our `Hypertext` or `LightweightButton` components) the cursor styles for the text have greater specificity and win out.

**What are the steps to reproduce the issue?**

Example: https://stackblitz.com/edit/react-ts-fwadwf?file=index.tsx

1. Go to the link above
2. Hover each example

**What behavior did you expect?**
I would expect us to respect the browser default here and allow users to add the default cursor styles for typography when they find it appropriate. As it currently stands it makes composition with the typography component a bit more cumbersome.

If we want to provide the default cursor to our typographic components I would suggest we do so one level up (Heading, Paragraph, Subheading). That level makes more sense to me as those components serve a more semantic purpose than typography. For instance, in the MSFT design system, headings are semibold. Similarly, in the MSFT design system, headings have the default cursor.

**Comment by bheston** [comment]
I've noticed this issue before, and agree that it's hard to compose and style correctly. I like the idea of applying to the specific semantic type-related components. I would add Label to that list above. It would also be cool if there was a way to set the style at the top of the page or something so by default text didn't get the selection cursor, but if not, setting those components should resolve most places.

**Comment by chrisdholt** [comment]
> I would add Label to that list above.

@bheston with Label we may actually run into this as well though, right? In certain cases we may want the label to be actionable as well (radio, checkbox) which would also create this problem. Would we want the label to reflect the same cursor as those controls?

We could likely handle those cases using the `className` in our own system. I think that may be a way to mitigate the issue. In our Radio/Checkbox implementations we ensure that the correct cursor is passed to the label via the className in our stylesheet. That way, if someone is working within the current system we at least ensure that we aren't causing issues for them.

**Comment by bheston** [comment]
Good thought on Label. In the case of radio button or checkbox, where it is rendered as part of the container, that seems like a good place to take care of it with className. In the other cases, I wonder if there is a way we can make inputs more standard like this. It may get into more questions like labels on top or left though, which checkboxes don't typically have. Possibly if a label is associated with a field, it should actually have the pointer icon because it's actionable in that clicking it focuses the input field.

For now it seems safe to start without label, but with the other semantic components you mentioned.
