### ISSUE TITLE
Add Tree View and Tree View Item as new base components

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast-dna#2479]
There should be a new components in fast-components-react-base for Tree View (and thus Tree View Items).

<img width="1040" alt="Screen Shot 2019-12-04 at 11 28 15 AM" src="https://user-images.githubusercontent.com/13071055/70174134-34c6dd00-1689-11ea-8e38-94c43ffced7b.png">

As defined by the W3C:
> A tree view widget presents a hierarchical list. Any item in the hierarchy may have child items, and items that have children may be expanded or collapsed to show or hide the children. For example, in a file system navigator that uses a tree view to display folders and files, an item representing a folder can be expanded to reveal the contents of the folder, which may be files, folders, or both.

**Functional requirements:**
- Nodes may or may not have child nodes
- Nodes with child nodes may expand and collapse
- Tree view should support multi-select
- Tree view should enable items to be composed as draggable nodes
- Tree view items should support infinite nesting
- The Tree View should manage focus within its context
- The Tree View should support both controlled and uncontrolled behavior by allowing a user to declare a selected node via props.
- Tree view items should support a slot for glyph content
- Tree view items should support a slot for the expand/collapse glyph

**Interaction model:**
The tree view should align to the interaction model provided by the W3C: https://w3c.github.io/aria-practices/#TreeView

**Implementation examples:**
Flat:
```jsx
<TreeView>
    <TreeViewItem title="Favorites" glyph={favIcon} />
    <TreeViewItem title="Read later" glyph={folderIcon} />
    <TreeViewItem title="Other" glyph={folderIcon} />
</TreeView>
```

With selected defined:
```jsx
<TreeView>
    <TreeViewItem title="Favorites" glyph={favIcon} />
    <TreeViewItem title="Read later" glyph={folderIcon} selected={true} />
    <TreeViewItem title="Other" glyph={folderIcon} />
</TreeView>
```

Nested:
```jsx
<TreeView>
    <TreeViewItem title="Root node & parent node" glyph={favIcon}>
        <TreeViewItem title="Child node" glyph={folderIcon} />
        <TreeViewItem title="Child node" glyph={folderIcon} />
        <TreeViewItem title="Child node & Parent node" glyph={folderIcon}>
            <TreeViewItem title="Child node" glyph={folderIcon} />
            <TreeViewItem title="Child node" glyph={folderIcon} />
        </TreeViewItem>
    </TreeViewItem>
    <TreeViewItem title="Root node" glyph={folderIcon} selected={true} />
    <TreeViewItem title="Root node" glyph={folderIcon} />
</TreeView>
```

**Comment by scomea** [comment]
I'm thinking the base "tree view item" could be more generic and perhaps not have a notion of a specific visual implementation like an icon, which could be a prop for a styled version.

**Comment by chrisdholt** [comment]
> I'm thinking the base "tree view item" could be more generic and perhaps not have a notion of a specific visual implementation like an icon, which could be a prop for a styled version.

@scomea that seems like a reasonable constraint. There's quite a few design systems where this is a pattern, but if we can easily accomplish it in those implementations I think it can be left out of base.
