### ISSUE TITLE
Progress is width 100% even when circular=true

### ISSUE THREAD

**Issue by adkaufm** [microsoft/fast-dna#2494]
Progress still has width 100% even when it's the circular version. Can we not

**Comment by chrisdholt** [comment]
@eljefe223 can you take a look at this? I don't think this should be required to be wrapped in a containing div just to properly size it. (@bheston as FYI)

**Comment by eljefe223** [comment]
@adkaufm How is width 100% negatively impacting your use case? Just trying to understand what the expectation is. Even if we remove `width: 100%` it will default to that same value.

**Comment by adkaufm** [comment]
The issue is that the containing div is width 100%. So if I place the progress in a larger div, it takes up the full width but the progress is left aligned. So annoying to have to add a jss stylesheet just to center it, when it shouldn't be 100% in the first place.

**Comment by adkaufm** [comment]
![image](https://user-images.githubusercontent.com/44783604/71026957-20d69e80-20bf-11ea-9a27-7bb958880f46.png)
why

**Comment by eljefe223** [comment]
Just implemented a progress in a prototype real quick. I see the `width` issue, but as an fyi there is no need to use `jssStyleSheet` in the current implementation you can apply the style directly to the `<Progress/>` itself.

https://stackblitz.com/edit/progress-circular
