### ISSUE TITLE
Dialog components ignore autoFocus

### ISSUE THREAD

**Issue by alyssacleonard** [microsoft/fast-dna#2495]
Dialogs force focus the first element in the dialog, even if autoFocus={true} is set on another element in the dialog.

Expected:
Setting "autoFocus={true}" on an element within a dialog should override the default behavior of focusing the first element in the dialog.

Example: 
autoFocus is set on the search box, but the "x" button gets focused because it is the first element of the dialog.
![image](https://user-images.githubusercontent.com/32080524/70361211-9c219000-1835-11ea-84c1-2fc49a1cefc5.png)

**Comment by chrisdholt** [comment]
I believe this was closed with #2498
