### ISSUE TITLE
Add shimmer state to loading lists

### ISSUE THREAD

**Issue by bheston** [microsoft/fast-dna#2612]
**What feature are you requesting?**
As an extension to #2255, support the shimmer effect for a number of placeholder items in a list. Consider the count of the actual items is unknown at the time of shimmer display.

**What would be the benefit of adding this feature?**
Lists are probably the most common component type that are delay loaded because of the cost of assembling and receiving multiple items.

**What solution would be ideal for you?**
It should work like the basic shimmer feature, but have a mechanism for fading the list out to imply the unknown amount of items, like:

![image](https://user-images.githubusercontent.com/47367562/72959655-ea480f80-3d5f-11ea-8c7b-2eacca095d57.png)

**Comment by chrisdholt** [comment]
This seems fairly implementation specific. On of the reasons we don’t have a “list” component is that it’s just markup, and there are several ways to accomplish or accommodate that where a component for such a thing may be an unnecessary abstraction. Can you elaborate how this might fit into our current framework for components? I’m not sure I see the value of this in FAST as a component with our current model.

**Comment by bheston** [comment]
Good point. I was thinking in regards to some of the list virtualizing work currently in incubation. Following the "it's just markup" notion, perhaps the right way to do it is to create some number of placeholder items in shimmer mode and adjust the opacity falling off on the way down. That doesn't lead to a consistent application though, which highlights one of the subtleties of shimmer. To me this feels like it fits somewhere with the idea that multiple components might shimmer as one, like an icon next to text. I'm not sure technically how we'll want to handle that, but I'm fine with closing this issue and leaving to to convention for now until / unless it fits into the component model better.

**Comment by chrisdholt** [comment]
Thx @bheston, closing for now - though I do think this could be a good candidate for an "example" of using shimmer. Additionally, if the component model expands to support this we can reopen this request.
