### ISSUE TITLE
fast-tooling-react in create-react-app cannot compile

### ISSUE THREAD

**Issue by dalyIsaac** [microsoft/fast-dna#2656]
**Describe the bug; what happened?**
Using the `Navigation` component from `@microsoft/fast-tooling-react` results in the following error:

```
Failed to compile.

./node_modules/@microsoft/fast-components-foundation-react/dist/foundation/foundation.js
Module not found: Can't resolve 'lodash-es' in '/home/username/Repos/my-app/node_modules/@microsoft/fast-components-foundation-react/dist/foundation'
```

**What are the steps to reproduce the issue?**

1. Create a fresh create-react-app app: `npx create-react-app my-app`.
2. Add `@microsoft/fast-tooling-react`: `yarn add @microsoft/fast-tooling-react`
3. Modify `App.js` to look like:

```js
import React from "react";
import { Navigation } from "@microsoft/fast-tooling-react";

function App() {
  return <Navigation menu={[{ displayName: "red", location: "/" }]} />;
}

export default App;
```

**In what environment did you see the issue?**

* OS & Device: Ubuntu 18.04
* Browser: Chrome, Edge, Firefox
* Node: 12.14.1
* Package managers: yarn 1.21.1 and npm 6.13.4

**Comment by janechu** [comment]
@dalyIsaac you should be getting a warning letting you know that `lodash-es` is a peerDependency. This is so that you don't accidentally end up compiling two copies of lodash-es and can control the version yourself.

Closing this issue.
