### ISSUE TITLE
Auto height do not work well in server side rendering in Horizontal Overflow

### ISSUE THREAD

**Issue by atifield** [microsoft/fast-dna#2687]
We made a fix previously #2472 (based on issue #2217)that will set height to auto on server side. Client side will then calculate max item height after hydration.

This is still not a perfect solution because we have observed that the horizontal scroll bar is visible for the server rendered page since height is auto.

After hydration, client rendered horizontal overflow will remove the horizontal scroll bar by setting to a pixel height based on the calculated height of the items inside.

**What are the steps to reproduce the issue?**

Server rendered horizontal overflow has

height: auto

Client rendered horizontal overflow after hydration has

height: 340px

**What behavior did you expect?**

We expect the height to match. We are proposing having horizontal overflow to support a fixed height. Since we already know the height of the items on the server side, we would like to use it to set a fixed height (as a prop) so it does not change or recalculate on hydration.

Please let us know if this is fine. If yes, we could summit a PR for this.

**In what environment did you see the issue?**

* OS & Device: Windows
* Browser Chrome
* Version 80

**Comment by nicholasrice** [comment]
closed by the above.
