### ISSUE TITLE
cssGridPropertyName logic incorrect in fast-layouts-react/Page.tsx

### ISSUE THREAD

**Issue by JamesBurnside** [microsoft/fast-dna#2689]
Logic incorrect when setting the display property in Page.tsx:
![image](https://user-images.githubusercontent.com/2684369/75061141-f5907700-5494-11ea-877c-81ca47abc81f.png)

This should instead be:

    this.props.cssGridPropertyName || (canUseCssGrid()
        ? "grid"
        : "-ms-grid"), 

i.e. have parens around the ternary operator.

And ultimately probably be:

    (this.props.cssGridPropertyName === "grid") ? "grid" :
        (this.props.cssGridPropertyName === "-ms-grid") ? "-ms-grid" : 
            canUseCssGrid() ? "grid" : "-ms-grid"),

**Comment by JamesBurnside** [comment]
I'll try get round to this today

**Comment by nicholasrice** [comment]
Ahh yep - good catch

**Comment by nicholasrice** [comment]
closed by the above
