### ISSUE TITLE
Stealth button with href has no hover affordance on explore.fast.design 

### ISSUE THREAD

**Issue by chrisdholt** [microsoft/fast-dna#2696]
1. Go to https://explore.fast.design/components/stealth-button
2. In the form to the left, add a value for the href attribute
3. Hover over the stealth button
4. Notice there is no visual affordance for hover

**What behavior did you expect?**
The hover state should not change.

**Comment by eljefe223** [comment]
This appears to be because of the `:enabled` selector on `hover` and and `active` since `<a/>` do not respond to `:enabled` we either need. to remove the `:enabled` selector from the base button styles or add individual `hover` and `active` selector to target the a tag.
