### ISSUE TITLE
Create state storage and examples to the CLI routine

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#27]
@awentzel commented on [Wed Jan 17 2018](https://github.com/Microsoft/fast/issues/18)

Currently, when a new component or module is created there are multiple places throughout the repo where it needs to be included before the build will succeed. This all could be automated at build time which would improve our workflow, limit merge conflicts, and improve the experience for contributors.

Ideally this would be easily incorporated in our experimentation and prototype repos.

getInitialState, createStore, examples, etc should all be populated dynamically at build time based on an export or config file.

This task would automate the imports for initial state, store and examples which currently have to be manually populated and managed. Automating these will reduce conflicts and ensure that nothing is missed as it is all auto-generated.

#17

**Comment by Falkicon** [comment]
Based on conversation with @chrisdholt  and @janechu, this does not appear to still be relevant.
