### ISSUE TITLE
Add language changing support

### ISSUE THREAD

**Issue by janechu** [Microsoft/fast-dna#270]
We should be able to switch languages in for testing, this should also switch RTL.

There should be:
- A dropdown in the information bar that should contain a subset of languages including some RTL and LTR languages
- Selecting a language should change the language of the examples shown
- Any change in LTR should be passed as a callback so that users can update their design systems and other page level items accordingly.

**Comment by nicholasrice** [comment]
Per @Falkicon , the initial implementation of this can just change the direction, not the language (English RTL)
