### ISSUE TITLE
Enable Boolean Attributes and Type Conversion for FastElement

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast-dna#2742]
### HTML Standard 2.4.2

A number of attributes are boolean attributes. The presence of a boolean attribute on an element represents the true value, and the absence of the attribute represents the false value.

If the attribute is present, its value must either be the empty string or a value that is an ASCII case-insensitive match for the attribute's canonical name, with no leading or trailing whitespace.

The values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether.

[Link](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#boolean-attributes)

### Current Behavior in FastElement

The `@attr` decorator has some un-predictable behavior. Take the following:

```TypeScript
@attr
required: boolean = false;
```

For some element *implementing* that property, invoking `element.setAttribute("required", "")` will add the attribute as expected, but will also assign the IDL property to the value `""`. Likewise, invoking `element.removeAttribute("required")` assigns the IDL attribute to the value `null`.

Additionally, setting the property to true or false does not update the attribute by adding or removing it.

### Proposed Solution

Let's add a `mode` property to the configuration for attributes, supporting the following values:

* `reflect` - Reflects properties to the attribute as is.
* `boolean` - Reflects properties as boolean attributes.
* `none` - Does not reflect properties.

By default, the mode will be `reflect`. 

**Example 1: The Default Reflect Behavior**

```TypeScript
class MyButton extends FastElement {
  @attr foo;
}
```

**Example 2: Boolean Attribute**

```TypeScript
class MyButton extends FastElement {
  @attr({ mode: 'boolean' }) foo;
}
```

## Type Conversion

In HTML, all attribute values are strings. However, in IDL they can be other primitive types. For example, an attribute might have the value "5" but the IDL should have the number 5. Or, an attribute might have the value "" which should be interpreted as IDL true, or null, which should be interpreted as IDL false (the case with boolean attributes).

### Proposed Solution

Introduce an interface `ValueConverter` as follows:

```TypeScript
interface ValueConverter {
  toView(value: any): string;
  fromView(value: string): any;
}
```

Extend the `attr` configuration with a `converter` property  to allow providing a converter.

**Example 3: Custom Converter**

```TypeScript
class MyButton extends FastElement {
  @attr({ converter: numberConverter }) foo: number = 5;
}
```

`FastElement` will then convert to html to update the attribute and from html to update the property value, using the provided converter.

Provide a boolean converter out of the box that can handle: "true", "false", "", `null`, `undefined`, `true`, `false`. This converter will automatically be used when specifying `mode: 'boolean'` unless a different converter was manually provided.

Converters will run first and then the `mode` code will handle actually setting the property or attribute with the final value.

**Comment by EisenbergEffect** [comment]
Closing this as implemented.
