### ISSUE TITLE
The fast-element "when" does not opperate correctly after a few changes to observable value

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast-dna#2816]
Repro:
Min repro branch here: https://github.com/microsoft/fast-dna/tree/users/nirice/when-directive-not-working.
1. `yarn start` in `packages/fast-components`
2. Click the "when test" navigation item from the storybook application
3. Click the "change" button several times

Unexpected behavior: Clicking the button the first few times will show/hide a "TEST" text. After several cycles though, the "TEST" text never gets removed, even though the value provided to the `when` directive is falsey.

**Comment by EisenbergEffect** [comment]
Ok, I've got a fix for this coming shortly. I need to run some benchmarks to make sure there's no real regressions.
