### ISSUE TITLE
Fast Element lifecycle events fire out of order in firefox

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast-dna#2875]
It appears that in FireFox the FastElement lifecycle events are fired out of order; connectedCallback is fired *before* the constructor. I'm not really sure how this is possible but that appears to be what is happening.

repro:
1. checkout https://github.com/microsoft/fast-dna/tree/users/nirice/fast-element-lifecycle-event-firefox
2. run `yarn start` in `packages/fast-components` and open app in Firefox
3. navigate to the 'name tag' component
4. observe order of console logs.

**Comment by EisenbergEffect** [comment]
I figured out what's going on here and should have a PR with the fix tomorrow.

**Comment by EisenbergEffect** [comment]
Fixed in #2885
