### ISSUE TITLE
attribute `value` is getting overwritten by default value "" if no default value is provided

### ISSUE THREAD

**Issue by marjonlynch** [microsoft/fast-dna#2894]
If a value is provided for the attribute `value` on a FormsAssociated based component, that value is set and then overridden by whatever the default value was for the value attribute. If no value is provided it's set to "",  if a value is provided then that value is used.

use branch: users/marjon/add-slider-check

1. Go to fast-components directory
2. run `npm start`
3. open console in the browser after stories page loads
4. Click on the slider example

Expect that the value provided in slider/fixtures/base.html for the initial value is used.
Instead "" is used which translates to 0 for the slider. If you provide a default of some other value it will use that value instead of what was provided in the examples base.html.

The behavior is the same in Edge and FireFox

**Comment by chrisdholt** [comment]
I think this may be related to #2893. FYI @EisenbergEffect

**Comment by EisenbergEffect** [comment]
Fixed in #2903
