### ISSUE TITLE
Add rendered example to component-documentation page

### ISSUE THREAD

**Issue by nicholasrice** [Microsoft/fast-dna#294]
Displays a single example of a component - this example needs to be wired into the schema-form-generator. This should appear above component documentation

**Comment by nicholasrice** [comment]
blocked by #272, #288

**Comment by chrisdholt** [comment]
I believe @janechu addressed this with a PR. Jane - can you confirm that this should be closed?

**Comment by chrisdholt** [comment]
closed by #470
