### ISSUE TITLE
Create utility to generate typedoc and component API documentation

### ISSUE THREAD

**Issue by nicholasrice** [Microsoft/fast-dna#296]
Bring over the utility to generate typedoc docs for documenting component APIs

**Comment by awentzel** [comment]
There is already a task to integrate TypeDoc with Docusaurus.  @nicholasrice Can you add details using the new issue template so I can better understand this work and ensure it's not in conflict with other TypeDoc and Docusaurus work already started?  Otherwise, let's close this.

**Comment by nicholasrice** [comment]
I think this has been completed - closing
