### ISSUE TITLE
Create a plan to release a VSTS marketplace package

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#30]
@awentzel commented on [Wed Jan 17 2018](https://github.com/Microsoft/fast/issues/15)

1. Create scope of work for all requirements users would want
2. Create tasks from this scope of work to execute the build out
3. Create documentation for installing, configuring, and using this package
4. Create blog post announcing this new package on fluentweb.com
5. Add to existing curriculum to include how to do all of the above.
6. Create video to walk through this entire process.

**Comment by Falkicon** [comment]
Please provide more context to what a VSTS marketplace package and what the outcome will be if we add it.
