### ISSUE TITLE
[Proposal] Nested Design System Objects

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast-dna#3003]
There is a desire for our design-system object to support nested data structures. Not only would we like to leverage this capability to organize like properties, but there is also a desire to support other open-source design-system implementations, including [https://theme-ui.com/theme-spec](https://theme-ui.com/theme-spec) and [https://styled-system.com/theme-specification](https://styled-system.com/theme-specification).

The primary challenge in supporting arbitrary (and nested) data structures is devising an observable pattern that allows observation of *any* mutation to the object or it's nested properties *and* observation of it's individual nested objects.

There are two paths forward that I see:

## Proxy

The ES6 Proxy class would allow us to implement a simple validator that would allow us to notify on any property change:

```jsx
var validator = {
    get(target, key) {
      if (typeof target[key] === 'object' && target[key] !== null) {
        return new Proxy(target[key], validator)
      } else {
        return target[key];
      }
    },
    set (target, key, value) {
        if (typeof value === 'object' && value !== null) {
            target[key] = new Proxy(value, validator)
        } else {
            target[key] = value;
        }

        // Notify subscribes of the design-system that the design-system has changed
        // Also notify subscribes of the target that the key has changed, similar to @observable
      return true
    }
}
```

Note: `Proxy` is not natively supported by IE. There is a polyfill: https://github.com/GoogleChrome/proxy-polyfill

## @observable

The `@observable` decorator from `@microsoft/fast-element` allows simple observation of keys on object. Using this, we could introduce an API to set the design system's structure, iterating through that structure and creating observable properties for all object keys. This is obviously more limited and would be prone to missed updates if objects are extended by natural assignment.(`designSystem.foo = { bar: "bat" } // not observed`). 

While we can't avoid the above, we could expose an API to manage updates for us:

```jsx
DesignSystemProvider.setDesignSystemProperty("foo", { bar: "bat" });
DesignSystemProvider.setDesignSystemProperty("foo.bar" /* or ["foo", "bar"] */, { bee: "bat" });

// 

public setDesignSystemProperty(key, value) {
    // Note - this would need to be slightly more complicated because in this world,
    // key would need to either be a string or an array of strings representing a nested
    // accessor structure.
    if (!Object.getOwnPropertyDescriptor(this.designSystem, value) {
	observable(this.designSystem, value);

	Observable.getNotifier(this.designSystem).subScribe(this, value);
    }
}
```

The goal of this thread is to land a path forward to unblock the described feature. Please chime in with thoughts / concerns / better ideas.

**Comment by EisenbergEffect** [comment]
Where are the design system objects coming from? Could we just ask people to define them as observable? Example:

```TypeScript
class SubObject {
  @observable prop1;
  @observable prop2;
}

class MyDesignSystem {
  @observable prop1;
  @observable prop2: SubObject;
}

```

**Comment by nicholasrice** [comment]
Ideally, the object's values could come from a few sources:

1. Reflected from design-system-provider properties or attributes
2. Set imperatively (and arbitrarily)

For declaratively defined properties (#1) we have a mechanism to map a content / IDL attribute to a nested design-system property. We could extend that to accept a design system "target" which could support a nesting structure:
```ts
@designSystemProperty({ customProperty: "font-size-base", target: "fontSize.base"})
baseFontSize = 12;
```

which results in:
```ts
designSystemProviderInstance.designSystem.fontSize.base === 12;
```

This decorator would provide us ample opportunity to attach observation mechanisms where necessary.

The extensibility story is where this gets trickier - how do I define a property on the design-system, instruct that property to be converted to a css custom property, *and* inject the observable behavior? This is the question I'm trying to answer.

In the OP I omitted reflection to css custom properties, which was a missing requirement. Thinking about this more, and with that requirement, I think the only way to accomplish this is to surface an API:

```ts
designSystemProviderInstance.defineDesignSystemProperty(
  { target: "fontSize.bigger", customProperty: "font-size-bigger"}, 18
);
```

The above could also be leverage by the decorator to keep things consistent. Setting the design-system *directly* would not be supported (`designSystemProviderInstance.designSystem.fontSize.bigger = 18`)

**Comment by EisenbergEffect** [comment]
Ok, I think I understand now. I was missing something earlier. Let me know if this is correct.

* We have a design system that we want to model as a more complex object, such as having a `fontSize` property, which is itself and object with sub properties like `base`.
* Regardless of the structure of the object, we need it to map to a flat set of CSS variables.
* We want the CSS variables on the host to update even if they are mapped to a nested object's properties.
* We want everything to be observable.

Is my understanding correct?

**Comment by nicholasrice** [comment]
Yep pretty much, we need to know when *any* property on or under the root object updates to re-evaluate.

**Comment by nicholasrice** [comment]
I'm going to table this for the time being for a few reasons:

1. The design system is designed to be configured through element attributes and properties, which is inherently a flat structure
2. One of the primary products of the design-system is CSS custom properties, which are inherently a flat structure
3. I haven't been able to come up with a good way to support nested properties that
   a. Is fully observable to deep mutation in a performant way
   b. Doesn't require a clunky API where nested properties are set via a string representation of the target path
   c. Doesn't add a lot of complexity and code

Because the primary configuration and output of the design-system is inherently a flat structure, and any nested system would need to be mapped to a flat structure *anyway* to support these cases, I think we're okay for the time being to simply require the flat structure. We can open this back up at a later point in time if not having nested structures is a deal-breaker for teams.
