### ISSUE TITLE
[Proposal] Content Composition

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast-dna#3039]
## Description

Today, if you provide a binding in your element's content, you can only return a primitive value from your expression. For example:

```TypeScript
const template = html`
  <div>${x => x.name}</div>
`;
```

Or, if you have an existing template, you can compose it like this:

```TypeScript
const sharedTemplate = html`...`;
const template = html`
  <div>${sharedTemplate}</div>
`;
```

But, what if you want a binding expression to return a template? You can't do that because the text binding doesn't know how to handle anything except for primitives, and the composed template directive doesn't know how to handle expressions 😢 

I propose that we teach the "text binding" how to be a "content binding" so that if a template is returned from an expression, it will create a view, bind it to the data source, and then insert it at that location in the DOM. Furthermore, I propose that we extends the `repeat` and `when` directives so that they can receive not only an inline template, but an expression that returns a template as well. By combining these things, we can greatly expand the compositional capabilities of the template engine.

### Examples

Below are a few examples of what we can enable with the above described capabilities.

#### Dynamic Composition

```TypeScript
const defaultTemplate = html`...`;
const templatesByType = {
  foo: html`...`,
  bar: html`...`,
  baz: html`...`
};

const template = html<MyElement>`
  <div>${x => x.selectTemplate()}</div>
`;

@customElement(...)
export class MyElement extends FASTElement {
  @observable data;

  selectTemplate() {
    return templatesByType[this.data.type] || defaultTemplate;
  }
}
```

#### Custom List Item Override

```TypeScript
const defaultItemTemplate = html`
  <li>${x => x.name}</li>
`;

const template = html`
  <ul>
    ${repeat(x => x.items, x => x.itemTemplate)}
  <ul>
`;

@customElement(...)
export class MyElement extends FASTElement {
  @observable items: any[] = [];
  @observable itemTemplate = defaultItemTemplate;
}
```

#### Per Item List Types

```TypeScript
const defaultTemplate = html`...`;
const templatesByType = {
  foo: html`...`,
  bar: html`...`,
  baz: html`...`
};

const template = html<MyElement>`
  <ul>
    ${repeat(x => x.items, html`
      <li>
        ${(x, c) = c.parent.selectTemplate(x)}
      </li>
    `)}
  <ul>
`;

@customElement(...)
export class MyElement extends FASTElement {
  @observable items: any[] = [];

  selectTemplate(item) {
    return templatesByType[item.type] || defaultTemplate;
  }
}
```

#### Overide Templates

```TypeScript
const myCustomTemplate = html`...`

@customElement(...)
export class MyDerivedElement extends MyElement {
  selectTemplate() {
    return myCustomTemplate;
  }
}
```

#### Custom Rendering in the Extreme

```TypeScript
const defaultTemplate = html`...`;
const template = html<MyElement>`
  <div>${x => x.selectTemplate()}</div>
`;

@customElement(...)
export class MyElement extends FASTElement {
  selectTemplate() {
    return defaultTemplate;
  }
}

export class MyCustomTemplate implements ViewTemplate {
  create(): View {
    // some custom view stuff here
    return customView;
  }
}

@customElement(...)
export class MyDerivedElement extends MyElement {
  selectTemplate() {
    return new MyCustomTemplate();
  }
}
```

## Technical Approach

There are several steps involved.

### Step 1

Currently, the template compiler flattens all text nodes into a single node when it finds a binding in content. Then it creates an aggregate binding that interpolates the static text with the dynamic text. This needs to be changed so that the flattening no longer happens and we get one text node per binding. The current design is largely the product of limitations in the older compiler which no longer apply. We should be able to switch this up, enabling us to interleave regular text and template bindings in the same content (otherwise they would get concatenated and break).

### Step 2

We need to update the "text binding" to become a "content binding". It should recognize when the value it is given has a `create` method. If it does, it should treat it as a template, create the view and then use the text node as an anchor to inject the view. The binding can keep track of the view and template to intelligently dispose the view as needed.

### Step 3

We should update the `repeat` and `when` directives to accept an expression and not just a literal template. This means they'll need to be updated to observe that expression if present and re-render if the template changes.

### Step 4

After the above, we can probably then remove the template directive and have it simply generate a normal content binding, just with a static template.

### Step 5

We may want to detect when a literal template is passed as a value to an attribute and turn that into a binding that always returns the same template. This will allow the following

```TypeScript
const myTemplate = html`...`;
const template = html`
  <my-element :itemTemplate=${myTemplate}></my-template>
`;
```

As apposed to forcing people into this:

```TypeScript
const myTemplate = html`...`;
const template = html`
  <my-element :itemTemplate=${x => myTemplate}></my-template>
`;
```

This is a *nice to have* but not required.

**Comment by nicholasrice** [comment]
Looks great! I didn't follow step #4 - what is the "template directive" that is being removed?

**Comment by EisenbergEffect** [comment]
Currently the ViewTemplate that creates views from templates also inherits from Directive so that templates can be interpolated into other templates (because you can only interpolate primitives, expressions, and directives). So, if we enable a text binding to become a content binding, it would handle this scenario and we would no longer need to inherit our template implementation from Directive.

**Comment by nicholasrice** [comment]
ahh gotcha - okay cool!

**Comment by chrisdholt** [comment]
LGTM!

**Comment by EisenbergEffect** [comment]
I'd like to start by working on phase one, hopefully next week, after we get some of the testing in place we talked about in issue #3046

**Comment by EisenbergEffect** [comment]
Everything but the `repeat` behavior is now implemented and merged 😄 

I'm holding off on the `repeat` because I've got some additional ideas forming in my head that would make it even better and I want to take a little time to work those out. I'll update this issue with the ideas after I get a chance to think it all through.

**Comment by EisenbergEffect** [comment]
Submitted a PR to add the last bit of this by enabling `repeat` to take a binding expression for its template.

**Comment by EisenbergEffect** [comment]
Closing this one as fully implemented now 😄
