### ISSUE TITLE
MSFT checkbox styling does not work across browsers 

### ISSUE THREAD

**Issue by chrisdholt** [Microsoft/fast-dna#304]
### Expected behavior 
Checkbox looks like a MSFT checkbox on all browsers.

### Actual behavior
Checkbox inherits the native styles of whatever browser it is opened in. It only appears similar to a MSFT checkbox in MSFT browsers (where MSFT design language is being applied).

### Steps to reproduce the problem
Boot fast-components-react-msft in chrome, firefox, safari and notice that the checkbox appears to be a native checkbox.
### Specifications (hardware, software, configurations)
* Include device make, model, OS version: 
* Include browser and version: 
* Include screen orientation: 
* Include screen size: 
* Include page URL: 
* Include localization: 

*Please attach screenshots or video of the problem for quickest resolution*

**Comment by nalogiudice** [comment]
Closed with [#371](https://github.com/Microsoft/fast-dna/pull/371)
