### ISSUE TITLE
Unable to authenticate, need: Basic realm="https://pkgsprodwus21.pkgs.visualstudio.com/"

### ISSUE THREAD

**Issue by memao** [microsoft/fast-dna#3045]
**Describe the bug; what happened?**

We are using an Microsoft internal package in VSTS. The version we are using: @microsoft/fast-application-utilities 3.1.3.

Start this morning, we are seeing this error when running "npm ci" on build machine. 

npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="https://pkgsprodwus21.pkgs.visualstudio.com/"

The build machine we are using is hosted machine "windows-2019"

All our PATs are updated. The package was downloading fine before today. 

I am wondering what is the authentication step we need to use to get access again？

**Comment by chrisdholt** [comment]
This package was previously deprecated though it never leaves the public npm registry. This looks like an issue with a private registry needing auth due to the packages perhaps being cached and referenced by VSO or ADO.

**Comment by Tiffastic** [comment]
How do we fix the issue?
