### ISSUE TITLE
[Proposal] Web Components Testing

### ISSUE THREAD

**Issue by EisenbergEffect** [microsoft/fast-dna#3046]
## Description

A proposal for test setup for web components work.

### Background

Testing in monorepos can can be tricky, especially when testing across multiple packages with cross-dependencies and breaking changes. After several attempts to do this on various open source projects, personal projects, and at other companies, the best solution I've seen is to have a dedicated "tests package" within the monorepo that itself has a dependency on all other packages. This enables not only unit testing but very easy integration testing. It also makes it easy to run *all* tests while working so you know that a change in one package does not cause a test to break that's related to another package.

## Setup

I'd like to propose that we add a new `__tests__` folder under our `web-components` folder where we can place all tests for `fast-element`, `fast-components`, and any future web-component-related libraries.

For test infrastructure, we'll include a setup for karma, mocha, and chai, which are the recommended test setup for web components according to open-wc.org. I've also used this particular combination for several years on non-React projects and it works well in that context. After we get the initial test setup going, I recommend that we also add a setup for Karma on BrowserStack for automated cross-browser testing of every PR.

Inside the package I'd recommend that we have a folder for `fast-element` tests and a folder for `fast-components` tests. We can also extract any shared testing infrastructure code to its own folder. As that matures, we may want to turn it into its own package to enable customers to test their own components using our same approaches. For now, we can keep it simple and build as needed.

In the `package.json` we should create a number of tasks related to testing. This can include commands to test in node vs. browser, to test only fast-element or specific components maybe, to test with or without debugging, and to test with particular browsers. We can start out with a few simple commands and then extend this over time.

## Plan

If there aren't any objections, I can have a PR ready either tomorrow (Friday) or Monday morning. The PR will contain the basic setup as well as a few initial tests which we would then plan to grow each day up until (and following) the release.

**Comment by chrisdholt** [comment]
Thanks @EisenbergEffect - one pattern that we've previously used was to keep unit tests for specific components within their given folder. Part of this was to make it extremely easy and intuitive to work on and test components. Everything I need for my control is easily found within its folder. Is the reason to move away from this preference/pattern/or due to technological restraints? I'm open to it, but we've had positive feedback from others about the pattern of keeping all things component related within a single folder.

**Comment by EisenbergEffect** [comment]
We can do that but then it's difficult to test changes to fast element against changes in our individual components. For example, I can now very easily break our components while it looks like all my fast-element tests are passing. To be safe, any change to fast-element requires running all individual components tests as well. So, this enables that kind of flow very easily and any other similar dependency-related testing issues that might come up down the road.

**Comment by chrisdholt** [comment]
The overall build gate would fail though if `fast-components` relies on `fast-element`, correct? This problem currently exists for the entire react directory - changes to any of the base component packages directly impact the MSFT packages. In this case as it is now, the build would fail if you made a change in a base component and then failed to account for it in the MSFT packages. 

A couple additional questions to better understand:

Is the overall concern the ease of creating intertwined tests or the overall dev inner-loop of testing? If we add additional web component specific packages, would we then include any pertinent tests in the root of the web components folder as well? 

If the concern is just being able to scope and run all the w/c tests easily, I think there are ways to accommodate that without hoisting all tests to the root of the w/c folder. No golden calfs here, just trying to think through the long term effects and reconcile the deltas between the various patterns that currently exist in the repo. Thanks Rob!

**Comment by awentzel** [comment]
I'd like to break out testing into separate proposals. What are our requirements?  What are we trying to achieve? What browser matrix? Vdiff? testing success/failure/approval process?  

I'm not sure BrowserStack or SauceLabs is necessary if testing for rendering engines (quality over quantity). Instead, I'd recommend proposing a testing strategy, then get into technologies once the strategy is locked.

I'd also, like to know a little more background into moving away from Jest and running different solutions in the same repository.

**Comment by chrisdholt** [comment]
I think for WC testing this can serve as the proposal; it might get confusing to break out beyond this. The browser matrix would be the same matrix for the technologies we are using w/ the WC packages from what I can tell.

**Comment by EisenbergEffect** [comment]
To be transparent on what's top of mind for me: we don't have any tests and to really do an ok job we need to have a few thousand tests written before release probably. So, I want to be careful to not have too many separate proposals since each day without a decision makes things a bit more difficult.

Regarding Jest, I'm not a fan because of the way it mucks with the test environment. I haven't had the best experiences with Jest in the past. I'd also like to be able to run tests in an actual browser, which I think is pretty important for libraries and components. Ideally, we should run all tests in all major browsers before merging to master.  That aside, guidance for web components seems to be mocha/chai/karma, which is a combination I have used successfully on multiple occasions. When we can, I want to try to follow what others are doing in the WC space. Obviously, I don't want to be a follower. We should innovate. But, since this isn't an issue of innovation at this point, I'd prefer to go with the crowd.

On the question of test organization, there are a few things I'm thinking about:

* I want the ability to create tests that span components and libraries.
  * I want to combine various components together in arbitrary ways and make sure they function properly.
  * I want to make sure our components work properly when used inside of a fast-element template where data is changing dynamically (several of our components are actually broken in this way today from looking at the code)
* I also want a very fast test inner loop.
* I'd like to add the test setup and tests in a non-destructive way and with as little duplication as possible.
  * Without a single package for tests, if there's repeated test library code, I either need to duplicate it or I need to go through the process of creating another package. I'm not ready to create an official testing package yet though. I'd like to let the testing shape that over a longer period and then extract it.
  * I'd prefer not to duplicate karma, mocha, tsconfig, etc. across multiple packages if possible.
  * I'd like a simple PR that is additive so that it doesn't effect anyone's existing work stream.
* Even if we do keep component tests with components and fast-element tests with it, we will need some place to put the tests that cross components and the library.
  e.g. Testing a card with a select inside it where the select has its item list generated from a fast-element repeat and each item in the list contains some typography and a badge.

**Comment by chrisdholt** [comment]
Thanks for the thoughtful response. Agree on most of the points above (including the Jest bit). Very specifically I wonder if we're talking about two kinds of tests, unit and integration tests. 

I would agree that integration tests are very important and I could see those laddering up to the __tests__ folder. With that in mind, I do see how it could also create confusion to have two different places where the tests live. I think the separation of unit vs. integration tests could help with the inner loop. If I'm focused on adding a new feature to a component, I can live in that space and run isolated tests (I'll acknowledge that watch scripts can help here as well).

Not exhaustive but I see two potential options here:

```md
...
  > web-components
      > __tests__
          > integration
              > test.spec.ts
          > components
              > accordian
              > anchor

**Comment by EisenbergEffect** [comment]
@chrisdholt I absolutely value having the code and tests side-by-side. That's a definite loss in my proposal. If we're ok with some duplication and open to having a top level integration tests folder, I'd be fine to move ahead with option 2, keeping unit tests with their code and adopting the global folder for integration tests. Would it be ok to start with getting this setup for fast-element first as a single PR? That would help get me moving ahead on some critical tests for that area.

**Comment by chrisdholt** [comment]
I love the push for integration tests and I'm personally okay with some duplication to get things rolling. I'm good with moving ahead in `fast-element` so we can get some critical coverage going. :thumbsup:

**Comment by EisenbergEffect** [comment]
Ok, I'll put together an initial PR to get it setup with mocha/cha/karma in the fast-element package. PR should be in either tomorrow or Monday. Various time-sensitive tasks might prevent me from getting it in before EoB tomorrow. We'll see how things go.

**Comment by awentzel** [comment]
I agree with where we have landed.  Though, I have some new points.

1. As code duplication, complexity, etc goes down, code quality goes up.
2. I'm in favor of test quality over quantity.  Meaning I'm not concerned with a number of tests.  I'm concerned that the right tests are in place whatever that number may be.  Also, we hit our thresholds (now's a good time to determine what that is) for statements, branches, functions, lines. 
3. Would we be looking to change the Jest tests at some point if we like the new setup better?
4. What is the impact on Code Climate --> Code Quality?  How would coverage work on the new tech?

**Comment by chrisdholt** [comment]
@awentzel a few follow-ups on some of your thoughts:

1. I agree here, though I think it's going to be better to eat some duplication now so we can increase quality of what is going out the door immediately. I don't think that's a hard/fast principle but specific to this scenario at this point in time.

2. I agree here. I'd even go so far as to say that sometimes thresholds need to change because the only way to meet them is to add quantity. If the only way to hit statement, branch, and function thresholds is to add tests which dig into the internals of a bit of code I think we should consider dropping those thresholds instead.

3. I don't think so - going in and changing the tests here would be a ton of work that seems unnecessary. I think that Jest + Enzyme is a good testing combo for our react unit tests. Additionally, going in and changing all these would open up opportunity for mistakes to be made and potentially create regressions or issues. I don't think we need to have alignment across the entire monorepo - I think we should just use what we find is best for a given scenario (within reason).

4. My assumption is that code climate really shouldn't care about how we generate coverage reports. Coverage is reported and it does its thing based on that. If it expects specific unified technology across the entire monorepo I think that's an incorrect assumption on the part of the tech. 

Just my $.02 :)

**Comment by EisenbergEffect** [comment]
Closing since we got the basic setup in over the weekend.
