### ISSUE TITLE
Create an API or utility to apply variable font properties to components

### ISSUE THREAD

**Issue by chrisdholt** [Microsoft/fast-dna#306]
We need an easy way to apply font properties to typographic components and potentially all components. Create an API or utility that allows for a global set of font properties to be set and easily manipulated from a component level.

Upon completion, the TODO found below should be fixed:

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-components-styles-msft/src/heading/index.ts#issue_5adfa15298a8bf00010001d9

**Comment by nicholasrice** [comment]
Would this be a candidate for a framework-agnostic utility? or are you envisioning this as a JSS implementation?

**Comment by chrisdholt** [comment]
@nicholasrice I'm not 100% sure yet. I'm a bit torn. I'm totally open to ideas on this one. On one hand, I think a framework agnostic utility is more compelling, but I also feel like managing through JSS may make it more useful for people within the overall fast system to just plug and play.

Send the ideas, I'm in an infinite loop of pros and cons!
