### ISSUE TITLE
[Accessibility] [Narrator] [Select] Narrator in item navigation reads differently in forward and backward navigation when labelledBy is specified

### ISSUE THREAD

**Issue by dhveerap** [microsoft/fast-dna#3065]
Narrator in item navigation reads differently in forward and backward navigation when labelledBy is specified
In forward navigation it reads
1. labelledBy text + selected menu item text+  Group
2. labelledBy text + selected menu item text + button collapsed
3. selected menu item text

In backward navigation it reads
1. labelledBy text + selected menu item text + <selected menu item text>
2. labelledBy text + selected menu item text + button collapsed
3. labelledBy text + selected menu item text+  Group

**What are the steps to reproduce the issue?**
1. Render Select component.
2. Start Narrator and using item navigation(NARRATOR + RIGHT ARROW) navigate to the select component. 
3. There will be 3 item navigations which reads as mentioned above in the description
4. Now navigate away from select component and do backward item navigation( 
NARRATOR + LEFT ARROW)
5. There will be again 3 item navigations but it does not read same as forward navigation

**If applicable, provide screenshots:**
![image](https://user-images.githubusercontent.com/64888708/81155032-2404f500-8fa2-11ea-8e85-137e716f494f.png)
with labelledBy as Translate- 
Forward Navigation - 
1) Translate choose a language group
2) Translate choose a language button collapsed
3) Choose a language

Backward Navigation - 

1) Translate choose a language choose a langugae
2) Translate choose a language button collapsed
3) Translate choose a language group

**What behavior did you expect?**
1) It should read same in both forward and backward navigation
2) It should not read same text twice(happening in backward navigation)

**In what environment did you see the issue?**

* OS & Device: [ Windows ]
* Browser [ Edge ]

**Comment by chrisdholt** [comment]
Thanks @dhveerap - we don't have a lot of control of how narrator navigation happens. Does this repro in other AT as well or is it specific to narrator?

**Comment by dhveerap** [comment]
@chrisdholt 
This does not repro with other screen readers. We checked with NVDA and voice over.

**Comment by roryfa** [comment]
Recommend close as external behavior on Narrator.

**Comment by chrisdholt** [comment]
Closing as External per above.
