### ISSUE TITLE
Rule is not linked issue

### ISSUE THREAD

**Issue by nalogiudice** [Microsoft/fast-dna#309]
Rule is not linked. Missing sheet option "link: true" issue found in button and toggle.

Marked exact location of issue in button ts.

Troubleshot with @nicholasrice and @janechu and concluded probably JSS issue.

Renders `background: "red"` fine but not 
`background: (config: IDesignSystem): string => {
      return config.brandColor;
 }`

**Comment by nicholasrice** [comment]
dupe of #342
