### ISSUE TITLE
Add the FAST web component library to Creator and Component Explorer

### ISSUE THREAD

**Issue by janechu** [microsoft/fast-dna#3154]
# Description

The Creator and Component Explorer currently only have React components from the `@microsoft/fast-components-react-msft` library. They should also have the components from the `@microsoft/fast-components` library.

This is a child item of #3025

## Requirements
- Place the components in categories according to their package name in the Component Explorer
- Add the `@microsoft/fast-components` to both the Creator and the Component Explorer
- Address any integration issues and determine if React components should be able to have web components as children (this may be confusing)

**Comment by EisenbergEffect** [comment]
@janechu Is this implemented now or are there still things left?

**Comment by janechu** [comment]
This is completed, I forgot to auto-close it with https://github.com/microsoft/fast-dna/pull/3226
