### ISSUE TITLE
Document changing the accent color

### ISSUE THREAD

**Issue by janechu** [microsoft/fast-dna#3221]
# Abstract

There's currently no documentation describing how to change the accent color of components.

## Description

In order to accomplish an accent color change, the `--accent-base-color` must be set as well as the `accentPalette` property on the `FASTDesignSystemProvider` using the utilities `createColorPalette` and `parseColorHexRGB`.

This should be documented and the utilities should be exported from the root.

Related to #3043

**Comment by nicholasrice** [comment]
closed by #3239
