### ISSUE TITLE
Fix broken dev site styles

### ISSUE THREAD

**Issue by nalogiudice** [Microsoft/fast-dna#328]
See screenshots - check in **ALL** browsers

<img width="1752" alt="screen shot 2018-04-26 at 1 30 46 pm" src="https://user-images.githubusercontent.com/22480660/39330344-2b1c8cd4-4956-11e8-8acd-3436dd644709.png">

<img width="1700" alt="screen shot 2018-04-26 at 1 31 12 pm" src="https://user-images.githubusercontent.com/22480660/39330347-2dd54b96-4956-11e8-8d20-642d89ad1439.png">

![imgo](https://user-images.githubusercontent.com/22480660/40013538-9aab7f0a-5762-11e8-819f-39a0a7404200.jpg)

**Comment by chrisdholt** [comment]
These specific issues are resolved. Closing as fixed.
