### ISSUE TITLE
Narrator can focus on a div unexpectedly in Select component

### ISSUE THREAD

**Issue by roryfa** [microsoft/fast-dna#3309]
For the Select component, Narrator is able to items navigate (Capslock+left arrow, Capslock+right arrow) to a div which CONTAINS the actual button of the control. This is unexpected. User should just be able to items navigate directly to the button of the control.

**Repro:**
1. Go to https://explore.fast.design/components/select
2. Turn on Narrator
3. Move focus to the preview pane of the component explorer
4. Press Capslock+right arrow once
5. Press Capslock+right arrow once more

**Expected:**
4. Narrator focus moves to button control
5. Narrator focus moves to next control

**Actual:** 
4. Narrator focus moves to containing div around the button (unexpected)
5. Narrator focus moves inside the div to the button control

Environment:
- Win10 version 2004 build 19041.329 ("Vibranium")
- Latest Edge Canary/Dev/Beta/Stable

**Comment by chrisdholt** [comment]
@scomea can you investigate?

**Comment by scomea** [comment]
This was fixed by https://github.com/microsoft/fast-dna/pull/2980

Just hasn't made it into production yet.
