### ISSUE TITLE
Fix "TODO" issue in packages/fast-form-generator-react/app/components/children/README.md

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#333]
TODO found

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-form-generator-react/app/components/children/README.md#issue_5ae2da07391e890001000218

**Comment by Falkicon** [comment]
@awentzel , should this be a bug? What needs to happen to close this?

**Comment by janechu** [comment]
This is blocked as full E2E must be implemented first.

**Comment by janechu** [comment]
Package has been deprecated.
