### ISSUE TITLE
Fix "TODO" issue in packages/fast-form-generator-react/app/components/arrays/README.md

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#334]
TODO found

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-form-generator-react/app/components/arrays/README.md#issue_5ae2da07391e890001000219

**Comment by Falkicon** [comment]
@awentzel , should this be a bug? What needs to be completed to resolve this?

**Comment by janechu** [comment]
This is unassigned as E2E testing is required before it can be picked up.

**Comment by janechu** [comment]
Package has been deprecated.
