### ISSUE TITLE
Create monitoring for all websites

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#34]
@awentzel commented on [Wed Jan 17 2018](https://github.com/Microsoft/fast/issues/11)

Provide analytics and monitoring on application health that will then fire off alerts on CloudBot -> Slack App.

1. Configure app insights
https://ms.portal.azure.com/#resource/subscriptions/456b8669-6142-4a7b-b4a6-adf39c80289e/resourceGroups/fluent-web-resource-group/providers/microsoft.insights/components/fluent-web-app-insights/properties 
2. Update webpage code with the instrumentation keys
3. Update CloudBot to integration

**Comment by Falkicon** [comment]
Issue moved to [Microsoft/fast-tracking #10](https://github.com/Microsoft/fast-tracking/issues/10) via [**ZenHub**](https://www.zenhub.com/)
