### ISSUE TITLE
JSS sometimes throws "link" error

### ISSUE THREAD

**Issue by nicholasrice** [Microsoft/fast-dna#342]
![image](https://user-images.githubusercontent.com/3213292/39387820-b2aff264-4a30-11e8-820d-6e1c091b5bfd.png)

Current repro in Toggle and also in ComponentViewToggle in development-site. 

It is preventing proper styling of components.

**Comment by chrisdholt** [comment]
related to [#664](https://github.com/cssinjs/jss/issues/664)

**Comment by chrisdholt** [comment]
Adding a note here to search for #309 when fixing this issue as places where this is broken is commented throughout the code base in reference to that issue.
