### ISSUE TITLE
Create breakpoint tracker utility

### ISSUE THREAD

**Issue by chrisdholt** [Microsoft/fast-dna#358]
- Should only be initialized once (implementation from previous repo exports the initialized instance)
- Should include default breakpoints but allow each instance to be configurable
- Should allow for up to 6 breakpoints, but not require all 6
- Should follow a subscriber model

**Comment by nicholasrice** [comment]
We should probably create a utility project to hold cross-cutting features like this that will be used in component projects -  maybe `fast-components-utilities`?

**Comment by chrisdholt** [comment]
@nicholasrice totally agree. I think we'll need quite a few of these utils. 

@janechu gave me some insight on how we can extrapolate the breakpoints so it's configurable and not tightly coupled. I'll add it in a separate utility package and we can try and figure out a good extensible solution for this.
