### ISSUE TITLE
add sideEffects: false to each package.json for webpack 4 users

### ISSUE THREAD

**Issue by TheLarkInn** [Microsoft/fast-dna#367]
### Expected behavior 
webpack can deeply prune unused exports because no side effects exists between reexports in any module packages

### Actual behavior
webpack 4 relies on having a `sideEffects: false` field in the package.json of resolved package to provide this treatment. I did a full analysis of every import/export in each package and it looks like no sideEffects actually occur at any re-export level, therefore its safe and a nonbreaking change to add this property. 

(PS: I'll send PR 😏 )

### Steps to reproduce the problem
N/A
### Specifications (hardware, software, configurations)
N/A
* Include device make, model, OS version: 
* Include browser and version: 
* Include screen orientation: 
* Include screen size: 
* Include page URL: 
* Include localization: 

*Please attach screenshots or video of the problem for quickest resolution*

**Comment by chrisdholt** [comment]
Thanks @TheLarkInn - Look forward to the PR!

**Comment by TheLarkInn** [comment]
@chrisdholt can other MSFT'ers push branches to master? Otherwise I'll fork and proceed.

**Comment by chrisdholt** [comment]
@TheLarkInn I think currently we have it setup where you'll need to fork

**Comment by TheLarkInn** [comment]
No worries at all!

I’ll try and squeeze some time to push these changes tomorrow!

**Comment by chrisdholt** [comment]
@TheLarkInn I'm going to go ahead and put up a PR that includes this as we need to make a few adjustments to our webpack config to reduce our app bundle size and I think it makes sense to handle this at the same time. Would love to have you audit and put up a PR to further improve and refine things!
