### ISSUE TITLE
Create formatting to the report generation process

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#37]
@awentzel commented on [Wed Jan 17 2018](https://github.com/Microsoft/fast/issues/8)

Reports currently generate as a single string, they should be formatted with proper nesting so that we can easily identify areas in which they change.

This reformats from single line to multi-line readably formatted file.  

Would make code reviews and maintaining far easier.  

Related: #4

**Comment by Falkicon** [comment]
We do not need this because we have snapshots.
