### ISSUE TITLE
Update changelog creation and management

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#40]
@awentzel commented on [Wed Jan 17 2018](https://github.com/Microsoft/fast/issues/5)

Compare this with our changelog format and look to remove as much manual operations as possible. 

Additionally ensure we're following latest standards and guidelines on how it's been implemented. 
https://nodejs.org/en/blog/release/v7.8.0/?utm_source=nodeweekly&utm_medium=email

1. We should have an all up (rolled up) versions in the developer documentation page.  as shown here
http://fluentweb.com/documentation/distribution-deployment/changelog/

2. Each components or module should include a link to it's own changlog history.

3. This component/module level history should have a new section after specifications for "Changelog" and show top 5.  

4. There would be a link to view all history beyond top 5.

get this initial stuff functional and then fine tune with Andrew.

**Comment by chrisdholt** [comment]
Closing this as we currently use lerna which provides changelog creation and management using conventional-commits as part of our release process.
