### ISSUE TITLE
Adding snapshots in MSFT to components using Chroma plugin results in error

### ISSUE THREAD

**Issue by nalogiudice** [Microsoft/fast-dna#402]
**Describe the bug**
When adding snapshots in react MSFT package, components using Chroma for JSS styling error in different ways (see screenshot)

**To Reproduce**
1. Go to `packages/fast-components-react-msft`
2. Add a snapshot for toggle (most straighforward error) or button (less helpful error) - anything that uses Chroma)
3. Update jest tests and see error

**Expected behavior**
Not to error and to add snapshots

**Screenshots**
<img width="783" alt="screen shot 2018-05-10 at 12 03 21 pm" src="https://user-images.githubusercontent.com/22480660/39888729-856bb3b4-544a-11e8-90e0-d4d62a3fcbd3.png">

**Comment by chrisdholt** [comment]
We need to add Chroma to some existing components that have tests, and we can't do that without dropping test coverage. I think I have a fix for this, so I'm going to grab this.

**Comment by chrisdholt** [comment]
PR is up for a fix to address this in #687
