### ISSUE TITLE
Create report generation CI process

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#41]
@awentzel commented on [Wed Jan 17 2018](https://github.com/Microsoft/fast/issues/4)

Generate on a nightly CI process a batch of reports that will generate every data permutation to determine what/where changes occur and if they are acceptable. This will help us account for changes to the API and ensure we are not accidentally introducing errors in the design system.

1. Reports can be completely removed from the development run time.
2. Reports could be in the hundreds of thousands so we want this ran on nightly CI
3. Reports would check for errors and inform us of issues.

Related: #8

**Comment by Falkicon** [comment]
We don't generate reports by design. Obsolete.
