### ISSUE TITLE
Create plan for Azure CD to notify upon ZipDeploy completion

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#42]
@awentzel commented on [Tue Jan 16 2018](https://github.com/Microsoft/fast/issues/3)

Create an Azure notification plugin that will notify users upon completion of Zip Deploy:

Current method is a GitHub project, but, requires code in every repository to accomplish. We should write a plan that can accomplish the same thing in a single Docker file and/or be using Azure Platform.  They may already have a plan, so talk with Azure PM team to get an idea.

https://github.com/awentzel/KuduPostDeploymentSlackHook.git

**Comment by Falkicon** [comment]
No longer relevant, @jane will add updated, accurate tasks.
