### ISSUE TITLE
Readme should explain how to install the package

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#453]
@nicholasrice commented on [Tue Jan 23 2018](https://github.com/Microsoft/fast-animation/issues/16)

### Expected behavior 
The readme should have instructions for how to install the npm package

### Actual behavior
The readme does not have instructions for installing the npm pacakge

### Specifications (hardware, software, configurations)
* Include device make, model, OS version: 
* Include browser and version: 
* Include screen orientation: 
* Include screen size: 
* Include page URL: 
* Include localization: 

*Please attach screenshots or video of the problem for quickest resolution*

**Comment by Falkicon** [comment]
No detail, what readme, what package?
