### ISSUE TITLE
Create animation library package in Angular

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#456]
@awentzel commented on [Wed Jan 10 2018](https://github.com/Microsoft/fast-animation/issues/5)

Create tasks for this story.

related features: #4 #3

**Comment by chrisdholt** [comment]
@awentzel fast-animation isn't a framework specific package, so I don't think we need to recreate it specifically for angular. The current examples are built in react, so we could add documentation on how to use it with various frameworks, but I don't believe there is any work to do in creating a new package. Closing this as obsolete and in favor of #466
