### ISSUE TITLE
Add mouse move handling function

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#457]
@awentzel commented on [Wed Jan 10 2018](https://github.com/Microsoft/fast-animation/issues/4)

My vision for this is a function that is called on mouse move and by default applies animation corresponding to the mouse position to its target but can be passed properties to adjust the input or a function to apply an arbitrary animation with normalized mouse position input.

**Comment by Falkicon** [comment]
This is part of a legacy task from the Animation Library work.
