### ISSUE TITLE
Fix "argument_count" issue in packages/fast-form-generator-react/src/utilities/form-input.style.ts

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#459]
Function `boxShadow` has 6 arguments (exceeds 4 allowed). Consider refactoring.

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-form-generator-react/src/utilities/form-input.style.ts#issue_5afe32ad506c710001000232

**Comment by nalogiudice** [comment]
Closed with [#449](https://github.com/Microsoft/fast-dna/pull/449)
