### ISSUE TITLE
Fix "identical-code" issue in packages/fast-form-generator-react/src/form/form-item.array.tsx

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#460]
Identical blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-form-generator-react/src/form/form-item.array.tsx#issue_5afe32bc506c710001000255

**Comment by nalogiudice** [comment]
Moving the functionality of menu into its own function

**Comment by janechu** [comment]
Package has been deprecated.
