### ISSUE TITLE
Fix "similar-code" issue in packages/fast-components-react-base/src/text-field/text-field.tsx

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#465]
Similar blocks of code found in 3 locations. Consider refactoring.

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-components-react-base/src/text-field/text-field.tsx#issue_5b0321681822ec0001000262

**Comment by chrisdholt** [comment]
@awentzel I just reviewed this one and it's clearly a won't fix. The duplicate code is being thrown even though these are three different, independent class structures, with different prop contracts. I've marked as "invalid" and am closing the issue as there should be no action taken here as the error is incorrect.
