### ISSUE TITLE
Fix "method_complexity" issue in packages/fast-layouts-react/src/column/column.tsx

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast-dna#472]
Function `generateStyleAttribute` has a Cognitive Complexity of 7 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-layouts-react/src/column/column.tsx#issue_5b073167da04120001000252

**Comment by chrisdholt** [comment]
If we can reduce the cognitive complexity of the generateAttributes function in the column component from 5 to 7, we should. However, we shouldn't fix this for the sake of making the error go away. In reality, the removal of the msGrid augmentation would help significantly. Unfortunately, we require msGrid to support our browser matrix.

**Comment by Falkicon** [comment]
@chrisdholt @awentzel , based on the comments above, this task seems to be in lymbo. Can you two please discuss, decide on a course of action and update or close the task with an actionable course forward.

**Comment by chrisdholt** [comment]
@Falkicon & @awentzel I think my comments above are still valid. It's not something I would prioritize internally for us right now based on the value it adds, but I would value a PR from someone who wants to contribute. I think we should move this to the backlog, keep it tagged with good first issue and leave this unassigned so those who want to contribute can find it.

I think valid issues like this which aren't an immediate priority but contribute to things like code quality, code cleanup, etc can be classified the same way.

**Comment by awentzel** [comment]
Closing as this is not a value add or enabler for current web component objective.
