### ISSUE TITLE
Descenders are clipped in component configurator

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#479]
**Describe the bug**
Notice how the descenders on "Lightweight" are clipped and now showing in the attached screenshot.

**To Reproduce**
1. Go to the latest 'FireFox' on MacOS
2. Navigate to https://msft-docs.azurewebsites.net
3. Click on the left navigation to get to the button.
4. Click to configure.

**Expected behavior**
Design should remain intact including transcenders and descenders should not be clipped.

**Screenshots**
![screen shot 2018-05-30 at 6 56 01 am](https://user-images.githubusercontent.com/16669785/40724754-aad5b294-63d6-11e8-91be-a062e4c395dc.png)

**Desktop (please complete the following information):**
 - OS: [e.g. **MacOS**, Windows, Linux]
 - Browser [e.g. Edge, Chrome, Safari, **FireFox**]
 - Version [e.g. 22, **Latest**]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by nicholasrice** [comment]
This is currently no-repro as the UI has changed significantly, so closing this for now.
