### ISSUE TITLE
Unable to navigate directly into button component

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#480]

**Comment by Falkicon** [comment]
@awentzel  Please provide more information in the description of this task. Setting back to triage till info is provided.

**Comment by chrisdholt** [comment]
Confirmed repro on msft-docs site. Updating to use node and will create a server.js file to map to the index for routing.

**Comment by chrisdholt** [comment]
Updated and fixed. Can now navigate directly to valid paths.
