### ISSUE TITLE
Text on a checkbox does not align correctly

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#481]
**Describe the bug**
Text on a checkbox does not align correctly.  This should match design with full testing across browsers.

**To Reproduce**
Navigate to checkbox page on https://msft-docs.azurewebsites.net/components/checkbox/ 

**Expected behavior**
Should match the expected design.

**Screenshots**
![screen shot 2018-05-30 at 7 03 42 am](https://user-images.githubusercontent.com/16669785/40725233-bd8e7ffa-63d7-11e8-9a08-0adaf8e5842c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. **MacOS**, Windows, Linux]
 - Browser [e.g. Edge, Chrome, Safari, **FireFox**]
 - Version [e.g. **Latest**]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**

**Comment by nalogiudice** [comment]
Looks like the input just needs `align-self: center;` - I can grab this really quick if you would like.
