### ISSUE TITLE
rfc: separate 'value' and 'initial-value' concepts for FAST form-associated controls

### ISSUE THREAD

**Issue by nicholasrice** [Microsoft/fast-dna#5119]
# 💬 RFC: Form Controls and the 'value' Property
## How FAST's Form Controls Work Today
Today, all FAST form controls support a 'value' JavaScript property and 'value' HTML attribute. The behavior expressed by all FAST form controls matches the [platform behavior](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-value), where setting the 'value' HTML attribute specifies the **initial value** of the control and the stateful value is expressed by element instances's 'value' JavaScript property (`<input value="initial-value" />` vs `myInputElement.value`). In cases where the control has a stateful value change (user interaction or programatic adjustment), the stateful 'value' JavaScript property will not match the 'value' HTML attribute.

## The Problem
Many UI frameworks (React, Vue, Blazor, etc) do not provide explicit mechanisms to configure how data is bound to HTML element instances. Instead, they rely on heuristics to determine when to bind data to HTML attributes, event listeners, and JavaScript properties. This has become a large pain-point with FAST's form controls because most of these UI frameworks special-case native form elements so that they work correctly with the framework.

When these frameworks render a custom form element from FAST for which the author is binding a value, the framework does not special-case the 'value' property for the custom element (special casing is generally done by tag-name), causing the framework to set the 'value' HTML attribute. As noted above, this effectivly sets the *inital* value and not necessiarly the *stateful* value, which can cause the control not to update when authors expect it to.

## Proposed Solution
The pragmatic solution would be for FAST to adjust the component interface to work in a way that better interfaces with these frameworks. This would greatly reduce developer frustration when using FAST components with these frameworks. Two changes would need to be made:

**1. Implement a 'initial-value' HTML attribute**
The 'intial-value' HTML attribute would be responsible for what the current 'value' attribute is responsible for and would be behaviorly the same as the existing 'value' attribute, namely configuring the inital value of the control and reacting to form reset callbacks.

> A parallel change would need to be made to the 'checked' attribute & property for fast-checkbox and fast-radio

We could also consider 'default-value', which is the name React has used to fill this purpose: https://reactjs.org/docs/uncontrolled-components.html#default-values

**2. Make the 'value' HTML attribute and JavaScript property solely responsible for element state**
The 'value' HTML attribute would be kept in sync with the 'value' JavaScript property, allowing state configuration through the `Element.setAttribute()` API as well as through JavaScript property assignment.

> A parallel change would need to be made to the 'checked' attribute & property for fast-checkbox and fast-radio

### Repercussions 
This change would additively change the form-associated API which constitutes a minor version itteration. However, it does *behaviorally* change the components in a way that we might consider a *breaking change*.

Specifically, anyone relying on the 'value' HTML attribute to seed initial value, and the value the control is populated with after form-reset, will see a behavior change. I think this is a minor case but somthing to be aware of.

This change likely wouldn't affect authors leveriging any of the UI frameworks with binding deficiencies (listed above) because authors would have already needed to work-around the binding system (getting direct element references and reading / writing using DOM access) and likely would not be relying on HTML attribute binding from the framework itself.

**Comment by javiercn** [comment]
@EisenbergEffect @nicholasrice I've read through the proposal and it makes sense.

One question that I have is whether or not we need the `default-value` property at all or if we could live just with just the `value` property by capturing the value the first time it is set and not updating it afterwards. I believe that would enable things like form reset to work transparently? Or is the reason for using a default value the fact that we can't reliably tell when a value was set for a  custom element upon creation.

**Comment by EisenbergEffect** [comment]
@javiercn I believe that we can't tell when the value set means "default value" vs "updating" due to various timings between the HTML parser, various front-end frameworks, etc. @nicholasrice can correct me if I'm wrong.

**Comment by claviska** [comment]
> The 'intial-value' HTML attribute would be responsible for what the current 'value' attribute is responsible for and would be behaviorly the same as the existing 'value' attribute, namely configuring the inital value of the control and reacting to form reset callbacks.

Can you clarify how `initial-value` will get populated? Is it expected to be done by the user, or will it happen automatically?

```html
<fast-text-field initial-value="..."></fast-text-field>
```

If the user is expected to set it, I fear many simply won't because 1) they're used to using `value` and 2) when they use `value` it will still appear to work.

**Comment by EisenbergEffect** [comment]
Could we have the first set of `value` set the `initial-value` if it's not already set?

**Comment by nicholasrice** [comment]
> @nicholasrice Would it now be required to always have the `default-value` attribute in addition to `value` when setting up a form component or would it be fine to just set the `value`, assuming one doesn't need to account for form resets?

The 'default-value' would not be required. If it didn't exist, 'value' is initialized to empty string.

**Comment by nicholasrice** [comment]
> @EisenbergEffect @nicholasrice I've read through the proposal and it makes sense.
> 
> One question that I have is whether or not we need the `default-value` property at all or if we could live just with just the `value` property by capturing the value the first time it is set and not updating it afterwards. I believe that would enable things like form reset to work transparently? Or is the reason for using a default value the fact that we can't reliably tell when a value was set for a custom element upon creation.

Yea, I don't think there is a deterministic way to determine what the author's intent would be without separating the attributes.

**Comment by nicholasrice** [comment]
> Could we have the first set of `value` set the `initial-value` if it's not already set?

I don't think so. Imagine `initial-value` is intentionally omitted, and a user types 'a' (think text field). We would not want to consider 'a' the initial value because that was user-input. I don't think watching for user-input is a safe work-around to this problem, because a similar use-case could easily be imagined where the first input is a result of some programmatic side-effect and not user-input (think autofill).

**Comment by nicholasrice** [comment]
> > The 'intial-value' HTML attribute would be responsible for what the current 'value' attribute is responsible for and would be behaviorly the same as the existing 'value' attribute, namely configuring the inital value of the control and reacting to form reset callbacks.
> 
> Can you clarify how `initial-value` will get populated? Is it expected to be done by the user, or will it happen automatically?
> 
> ```
> <fast-text-field initial-value="..."></fast-text-field>
> ```
> 
> If the user is expected to set it, I fear many simply won't because 1) they're used to using `value` and 2) when they use `value` it will still appear to work.

'initial-value' would be applied as by application authors. If authors don't use it that is fine, I think the important point is that the feature is available. I don't expect many authors using React / Vue / etc to use this feature because those systems generally prefer ["controlled" form elements](https://reactjs.org/docs/forms.html#controlled-components). This work makes using FAST controls as "controlled" possible though, while still providing a mechanism to default a value to authors outside of those frameworks (or those using the listed frameworks but preferring uncontrolled form elements).

**Comment by EisenbergEffect** [comment]
Makes sense and sounds fine to me.

**Comment by ParamagicDev** [comment]
As long as I can write 

`<my-input value="blah"></my-input>` and the initial value is `"blah"`, I don't see an issue.

It's probably not ideal to have to provide an additional attribute for initial values vs current values, but for compatibility reasons it makes sense especially for JS rendering frameworks like React, Vue, Svelte, et al.

However, if i had to write:

`<my-input initial-value="blah"></my-input>` 

I would feel a little weird about that since it doesnt feel like a regular form input element.

**Comment by nicholasrice** [comment]
You can definitely just use `<my-input value="blah"></my-input>` to initialize the value to "blah", keeping in mind the control wouldn't identify "blah" as an "inital-value" in form reset scenarios.

**Comment by UtmostCreator** [comment]
> Today, all FAST form controls support a 'value' JavaScript property and 'value' HTML attribute. 
> ...
> In cases where the control has a stateful value change (user interaction or programmatic adjustment), the stateful 'value' JavaScript property will not match the 'value' HTML attribute.

Why do we really need that "`stateful value`"? if we may have a `value`? (or could you explain where the "stateful value" comes from and how it differs from the "value)?

> the framework does not special-case the 'value' property for the custom element (special casing is generally done by tag-name)

What does it mean "`the framework does not special-case the 'value'` "?
Does it mean that framework can not recognize the tag and, therefore, stops updating the element's value? (please let me know if whether I am wrong or correct)


> 'initial-value' would be applied as by application authors. If authors don't use it that is fine, I think the important point is that the feature is available. I don't expect many authors using React / Vue / etc to use this feature because those systems generally prefer ["controlled" form elements](https://reactjs.org/docs/forms.html#controlled-components). This work makes using FAST controls as "controlled" possible though, while still providing a mechanism to default a value to authors outside of those frameworks (or those using the listed frameworks but preferring uncontrolled form elements).

Do you mean that all the changes made either in code (source code) or in the form itself will be the “single source of truth”? (so no matter where you change it, you will see the same data)

And to clarify a few things up I got summed up all the comments into one about:
- default-value;
- initial-value;
- value.

Table 1.0 that explains what each attribute mean & how it can be set.
| Attribute Property Name | Description | How it can be set 
| :--- | --- | --- 
| default-value | is the initial value of the element | `<input default-value="default-value" />` 
| initial-value | is it the value that is used when neither default-value nor value is set? (is used for form-reset) | `<input value="initial-value" />` 
| value | is the current element's value (after a change or it takes the `default-value` if no changes were made) | `<input value="value" />`

> .... 'initial-value' would be applied as by application authors. 

`"initial-value"  - is designed for form reset?
So if the user (developer set it as 
```
<input value="InitialValueExample" />
```
After a form gets reseted the `default-value`,  `value` and `initial-value` will contain the `InitialValueExample`, isn't it?

Please let me know if any of my statements or suggestions is incorrect or lacking some information.

Here is my point of view:
Yeah, I reckon that making a FAST-UI elements behavior close the HTML | JS defaults, makes it much easier as for the end-users and the developers themselves (FAST-UI team), as if web-API gets changed, you could easily refer to the official [w3c](https://www.w3.org/) | [Web APIs - Introduction](https://www.w3schools.com/js/js_api_intro.asp) | [HTML Forms](https://www.w3schools.com/html/html_forms.asp). As you would benefit from maintaining/support points at the same time.

Thank you all for your persistence, hard work, and efforts!

**Comment by nicholasrice** [comment]
@UtmostCreator 
1. "stateful value" is just a semantic description of the control's `value` property; I'm not suggesting there is a `Control.statefulValue` property for the element. The proposal is that there are two properties with two corollary HTML attributes, one to represent current state (`value`) and one to represent default/initial state (`defaultValue`).
2. React, Blazor and other frameworks have special internal logic to handle data-binding to `HTMLInputElement` instances, where the "value" binding follows a different code-path than bindings for other html attributes (it sets a *property* on the element instance, not an HTML attribute). The qualifier to go down this code-path hinges on the tag-name of the HTMLElement, which precludes custom elements that should otherwise exhibit the same behavior as an HTMLInputElement. It's not that these frameworks stop updating the value, it's just that they set the *value HTML attribute* and not the *value property* for element tag-names other than `"input"`. 
3. I don't follow your third question, can you clarify?

In reference to your table, the proposal is not for **three** attribute / property pairs, it is for two. "initial-value" and "default-value" refer to the same implementation, and above we are simply discussing which name is more suitable.

**Comment by chrisdholt** [comment]
@nicholasrice and @EisenbergEffect it just occurred to me that it'll likely be hard for us to gain traction with this specific implementation/approach as a long term solution to propose back through Open-UI as it relies on *changing the default behavior of the platform*.  It essentially moves us *further* away from any future platform solution to this problem because of the sheer volume of legacy code relying on `value` operating in a consistent way. 

I'm leaning a bit away from changing value and considering how we would approach something *additive* to track the current value. Given our goals, it seems hard to come back from moving `value` away from the existing platform behavior. I can't help but think that we should reconsider changing value and instead consider an additive attribute to track the current stateful value. I think that's the only way we can really plan to be aligned to the platform in the future - there's just no way that `value` changes across the web. 

Thoughts?

**Comment by UtmostCreator** [comment]
Thank you, Nicholas! 
@nicholasrice

By 3rd question you probably mean this:

> Do you mean that all the changes made either in code (source code) or in the form itself will be the “single source of truth”? (so no matter where you change it, you will see the same data)

Here I mean that the value from JS/JS framework will be the main and that any FAST-UI component will follow/track its changes.

So after making a suggested change by other members, in the end, the result will the end-users be able to see the desired result (so that the values of any other element will be changed according to the framework's values no matter what happens)?

Yeah, I reckon that **Rob Eisenberg** suggesting a good solution for this case by adding a new property that will be in sync with the JS frameworks/JS.

---
But the only thought about that 

> 2) Frameworks create methods to manage this on their end. In the case of either of those, I think we'll want to keep from changing value.

may terrify other developers to supply some things for a specific web components library/tools.
IMHO I believe it is better to find out a way to support it out of the box on the web component's side.

---

Another question is that what interferes to sync it using a direct value property as it works with default HTML elements?
Suggested answer: Is it because of Components that is not just a simple HTML element but a set of instructions generated during template generation / Architectural solution/move to improve something else?


Please let me know if I may help you in any way! (e.g. to research something or make some testing/comparison of JS frameworks e.g. vue/angular or even react, in the last one I am not that strong)

**Comment by nicholasrice** [comment]
That's a good point @chrisdholt. It's definitely not my favorite to have two mechanisms to do the same thing but perhaps in this case it's best.
