### ISSUE TITLE
fix: in Anchored Region if horizontalInset/verticalInset is true, changing horizontalDefaultPosition/verticalDefaultPosition will not update anchored region if changed twice or more

### ISSUE THREAD

**Issue by caseyfaber** [Microsoft/fast-dna#5213]
# 🐛 Bug Report

If `horizontalInset` is true, changing `horizontalDefaultPosition` will only update the anchored region once (and emit 'positionchange' event), and after that _no_ attribute changes will update it anymore (and 'positionchange' will not be emitted again).

If `verticalInset` is true, changing `verticalDefaultPosition` has the same effect.

Notes: Once the default position has been changed twice and doesn't update anymore, even calling `AnchoredRegion.update()` will not do anything. If `autoUpdateMode` is set to 'auto', then scrolling or resizing the window will cause updates to work again, until the default position is changed twice again.

## 💻 Repro or Code Sample

Sandbox: https://codesandbox.io/s/anchored-region-position-update-3z4so

This sample has `horizontalInset = true`, and will log to the console 'positionchange' when `positionchange` event is emitted.

1. Change the selection in the Vertical Default Position dropdown a couple times (works even if you change it multiple times).
2. Change the selection in the Horizontal Default Position dropdown a couple times (works once, but after that will not update again)
3. Change Vertical Default Position again (will not work anymore)

## 🤔 Expected Behavior

Changing `horizontalDefaultPosition` should update the anchored region and emit the `positionchanged` event even if `horizontalInset` is true and it's changed more than once.

## 😯 Current Behavior

Changing `horizontalDefaultPosition` will work as intended once, but after that will not update or emit `positionchange` event again, and any other attribute changes after this won't update anymore either.

## 🔦 Context

On Harmony Hub documentation site, we have some samples using anchored region with a position dropdown to see the different positioning options.

## 🌍 Your Environment

* OS & Device: Windows
* Browser: Chrome, Edge
* Version: fast-components 2.10.0

**Comment by scomea** [comment]
Subtle, good catch.  Basically anchored region could ignore updates that didn't change geometry.

**Comment by caseyfaber** [comment]
The weird thing is it does update it the first time, and then ignores it the second time and breaks updates for any future changes on _any_ attributes.

**Comment by scomea** [comment]
> The weird thing is it does update it the first time, and then ignores it the second time and breaks updates for any future changes on _any_ attributes. Seems like the issue isn't ignoring certain updates, but that doing that update is breaking the observing somehow.

I believe what's going on is that the region gets into a state where the code that mitigates unnecessary layout updates blocks updates because it doesn't detect a geometry change even though it should not in the case of updates prompted by attribute changes.  It works the first time because the saved data is frequently stale so it doesn't kick in.  I think the change I made will ensure that attribute changes always result in a full layout update.
