### ISSUE TITLE
Consider dropping the lodash-es package

### ISSUE THREAD

**Issue by connor4312** [Microsoft/fast-dna#5271]
# 🙋 Feature Request

Hi, VS Coder here. @hawkticehurst and @daviddossett recently did some great work on a [webview toolkit](https://github.com/microsoft/vscode-webview-ui-toolkit) for our extension authors, which is based on Fast.

In our scenario, loading code quickly is important; developers have high expectations of their code editor. Naturally I opened up our package in [bundlephobia](https://bundlephobia.com/package/@vscode/webview-ui-toolkit@0.8.1) to check out the package size. I immediately noticed `lodash-es` accounts for about a quarter of the total bundle size. This is something that stood out to me, since while Lodash has been historically very useful, its usefulness has been supplanted in large part by ES6 features. While lodash-es allows for tree shaking its exports, Lodash has many cross-dependencies internally which makes its bundle size larger than one might expect when importing simple functions.

I took a quick look through imports. Lodash is only used in 9 files in `packages`, and the only features that are used from Lodash are:

- [`uniqueId`](https://lodash.com/docs/#uniqueId), which can be replaced with an ad-hoc generator, or [uuid](https://www.npmjs.com/package/uuid) whose `v4` export is 0.7KB.
- `isFunction`/`isString`/`isBoolean` which can be safely replaced with `typeof` checks
- `inRange` which can be replaced with a trivial helper or logic
- `pascalCase`, which can be replaced with a somewhat simple function or the 0.3KB [pascal-case](https://www.npmjs.com/package/pascal-case) module
- `throttle`, which can be replaced with a simple function or the 0.7KB [throttle](https://www.npmjs.com/package/throttle-debounce) package

Switching to the suggested external dependencies would reduce 95% of the code size currently imported through Lodash -- and if implemented directly in the repo (which is my preference for my own packages 🙂  ) slightly more still.

If you think this is a good idea, I'm happy to work on a PR for it.

**Comment by chrisdholt** [comment]
> Love this! I've wanted to remove that dependency for a long time. Any interest in contributing? 😉

I’d echo this - it sounds like a net-benefit. Would welcome a PR here.
