### ISSUE TITLE
fix: tree item "selected-change" event should be emitted after the selection prop changes

### ISSUE THREAD

**Issue by scomea** [Microsoft/fast-dna#5290]
# 🐛 Bug Report

This pr https://github.com/microsoft/fast/pull/5194 changed how selected state is managed by the tree view component.  However now the "selected-change" event is emitted before the selected value of the tree item has actually changed which caused some implementations to break as it was expected that the selected value had actually changed when the event was emitted which was no longer the case. This seems misleading.

I propose we add a new "invoked" event to tree view items that the parent tree view can watch for in order to determine when to change the selected prop of tree items and we only emit the "selected-change" value from the tree-item after the selected state of the item has actually changed.

**Comment by jumarroq** [comment]
@scomea @nicholasrice I logged a related bug for this here: https://github.com/microsoft/fast/issues/5311 they should be considered together I think.
