### ISSUE TITLE
Create defaults for styles that receive data from a design system provider

### ISSUE THREAD

**Issue by janechu** [Microsoft/fast-dna#535]
User should always see a style applied regardless of the presence a design system provider wrapper.

Currently we are not using fallbacks for our JSS msft styles. In case there is no config or the property has not been provided through the config we should have a default fallback built in.

The best solution might be to use the `get` utility from lodash-es to check.

Example for returning a property of config called `foregroundColor`:
```
color: (config) => {
    return get({config}, "config.foregroundColor") || designSystemDefaults.foregroundColor;
}
```

**Comment by janechu** [comment]
@chrisdholt updated the task, please let me know if this is sufficient information.

**Comment by chrisdholt** [comment]
@janechu clarifies it a ton, thanks!
