### ISSUE TITLE
Create filter UI to component navigation pane

### ISSUE THREAD

**Issue by Falkicon** [microsoft/fast-dna#536]
### **User benefit:**
User can search through large nubmers of components, examples and other resources quickly.

### **Problem statement:**
Today, a user must navigate through nested menus and lists to find what they are looking for.

### **Prefered solution:**
The filter should refine the list below in real time and have support for keywords. For example, pivot could have the keyword of tab. This will help users find resources that may not be named as expected.

![image.png](https://images.zenhubusercontent.com/5a85d50c4b5806bc2bc7186b/3617cef9-d1b8-4471-aedc-557db2fe9eaf)

**Design file:**
https://www.figma.com/file/0MUSNF4N5VnE4Mmo0qX0GYtE/FAST-Application

**Comment by eljefe223** [comment]
Closing because no longer relevant.
