### ISSUE TITLE
FAST-Documentation: extra line is showing on right side of preview area on documentation tab.

### ISSUE THREAD

**Issue by Falkicon** [Microsoft/fast-dna#537]
Remove the right line from the preview area. Also, bottom border should be #CCC.

**Desired:**
![image.png](https://images.zenhubusercontent.com/5a85d50c4b5806bc2bc7186b/fc58d051-dde1-43e2-b226-2f09206c5633)

Bottom border: #CCC

**Current:**
![image.png](https://images.zenhubusercontent.com/5a85d50c4b5806bc2bc7186b/a0d7a295-1b2f-44aa-875a-00348093054a)

Bottom border: #E2E2E2

**Comment by eljefe223** [comment]
in progress
