### ISSUE TITLE
Update Dev tools to allow resize on FAST documentation site 

### ISSUE THREAD

**Issue by Falkicon** [Microsoft/fast-dna#540]
### **User benefit**
User will benefit from being able to show more or less of the dev tools pane depending on their needs and circumstances such as monitor size.

### **Problem statement**
There is no way to adjust the dev tools area and each pane changes the size of the window.

### **Preferred solution**
Let the user adjust the dev tools pane in the same way that they can adjust the size of the configure pane. Min size should be 100px and max size should leave 100px of the above pane exposed. Size should be retained inside the session with a future task to retain the users size preference between sessions.

**Comment by eljefe223** [comment]
@janechu not sure how we want to go about this. It looks like the <Pane/> component only supports resizing left to right so we would either need to add vertical resizing support to that or just one off it for the Dev tools.

**Comment by chrisdholt** [comment]
@eljefe223 dev tools doesn't currently support resizing in any direction. Pane supports resizing, but the dev tools section isn't a pane, and I don't think we want to conflate the two. I think the resize behavior will need to be a feature addition to dev tools to support resize. We can use the Pane component as a guide for how that should be added, but I don't think we want to use Pane to accomplish this as the requirements are different.

cc: @janechu

**Comment by eljefe223** [comment]
Talked to @nicholasrice and he recommended adding vertical resize capability to our row component.
