### ISSUE TITLE
Update side panes to include shadows on FAST documentation site

### ISSUE THREAD

**Issue by Falkicon** [Microsoft/fast-dna#543]
### **User benefit**
Update will align with Fluent design language and elivation gudiance. 

### **Problem statement**
Current implementation does not match design.

### **Preferred solution**
Update to match design:
![image](https://user-images.githubusercontent.com/943328/41387600-9b10698c-6f3c-11e8-9775-d5a3c02f7240.png)

Shadows should appear on both left and right panes. Pane elevation shadow on app shell should be configurable to support multiple elevations. This might apply when there are more than one right or left panes. Shadows should be based on latest Fluent guidance.

Design file:
https://www.figma.com/file/0MUSNF4N5VnE4Mmo0qX0GYtE/FAST-Application?node-id=137%3A12

**Comment by nicholasrice** [comment]
This has all changed signficantly, so closing.
