### ISSUE TITLE
Update select style components with new select component on FAST apps

### ISSUE THREAD

**Issue by Falkicon** [microsoft/fast-dna#546]

**Comment by chrisdholt** [comment]
@nicholasrice is currently building out the fast select component. I think there will be a couple of dependencies to get the select into the development site and form generator.

We don't want to take a dependency on fast components for someone to use either of these packages, but we have talked about allowing users to pass their own components for use in the form generator pane. 

@janechu likely has more information on what this will take.

**Comment by chrisdholt** [comment]
related to #551

**Comment by chrisdholt** [comment]
closing this in favor of #2338
