### ISSUE TITLE
Capitalize tab strings and update spacing for Dev tools

### ISSUE THREAD

**Issue by Falkicon** [Microsoft/fast-dna#547]
Tabs for FAST documentation "Dev tools" should have a capitalized first letter and incorrect spacing.

**Current:**

![image.png](https://images.zenhubusercontent.com/5a85d50c4b5806bc2bc7186b/71fb95e0-af69-4c29-9e0d-0bdcab8ebb88)

**Desired:**

![image.png](https://images.zenhubusercontent.com/5a85d50c4b5806bc2bc7186b/88097df3-7b9b-43d5-bb52-2161ad206bf2)

**Comment by eljefe223** [comment]
In Progress
