### ISSUE TITLE
Extra space is being added at the top of the component code preview

### ISSUE THREAD

**Issue by Falkicon** [Microsoft/fast-dna#550]
On the FAST Documentation site, there is extra space being added above the code preview text. The margin is also missing on the left. Some of the margin issues appear on the Schema view as well.

Current: 
![image.png](https://images.zenhubusercontent.com/5a85d50c4b5806bc2bc7186b/809a3b00-79ef-498d-a22b-b8a2fe8f1611)

Desired:
![image.png](https://images.zenhubusercontent.com/5a85d50c4b5806bc2bc7186b/ddf206d1-002a-4090-96a5-672cd68227f6)

Design file: 
https://www.figma.com/file/0MUSNF4N5VnE4Mmo0qX0GYtE/FAST-Application

**Comment by chrisdholt** [comment]
@eljefe223 We should check with Jane on the long term styling of the code preview as that may end up taking care of this.

For an interim solution, this is likely the result of default browser styling being applied to the <pre> element. We can avoid this by explicitly adding styles for the element. For instance, if the browser is adding a default margin, we can explicitly set margin to keep it from being applied by the browser. If other browsers add padding by default, we can set padding to 0 to ensure that we negate that browser default as well.
