### ISSUE TITLE
Add Discord Widget too Fast-dna marketing website

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#576]
looking at https://luna-lang.org/ reveals a Discord Widget in the bottom right corner.  I like how engaging this is and think it would be a good idea for us to implement.

<img width="401" alt="screen shot 2018-06-22 at 9 13 29 am" src="https://user-images.githubusercontent.com/16669785/41787235-94d47baa-75fc-11e8-9d9f-08f45151f8c2.png">

**Comment by chrisdholt** [comment]
Issue moved to [Microsoft/fast-tracking #88](https://github.com/Microsoft/fast-tracking/issues/88) via [**ZenHub**](https://www.zenhub.com/)
