### ISSUE TITLE
Disable auto creation of issues when TODO's are found in code climate

### ISSUE THREAD

**Issue by chrisdholt** [Microsoft/fast-dna#586]
Currently if a TODO is added to the codebase, a bot from code climate automatically creates an issue to resolve that TODO. In principle, any TODO's checked-in to the repo should reference an existing issue or bug. When the code climate bot finds a TODO and creates an issue, we now have two issues to fix/resolve. 

The scenario could be something such as:
- Something requires a TODO
- If an issue doesn't exist, create the issue in Github to track the TODO. Reference the place the TODO exists in the codebase so the person doing the work can update/fix and complete the task
- If an issue already exists in Github, add a note to the issue you have referenced with the place the TODO exists in the codebase so the person doing the work can update/fix and complete the task

If each TODO requires an issue to be referenced upon check-in, creating an issue because we found a TODO becomes redundant.

NOTE: _Code climate should still catch on TODO's in order for us to **verify** that an issue has been created. Once the issue has been created, we can approve the code climate coverage regarding the TODO. As an FYI, this doesn't mean that the TODO becomes invalid or a won't fix. It's valid (new or confirmed), but we can approve from a high level and continue tracking those for quality._

**Definition of Done:**
- Code climate bot that automatically creates issue for TODO's is disabled.
- Documentation is added to the WIKI regarding adding TODO's to the codebase

**Comment by awentzel** [comment]
Code climate can be configured using the .codeclimate.yml file.  Investigate, if we can simply remove `-- todo` to quickly fix.  Then update wiki after a solution is found.

```
plugins:
  fixme:
    enabled: true
    config:
      strings:
      - HACK
      - TODO
```

**Comment by awentzel** [comment]
Additional links to details: 
- https://docs.codeclimate.com/docs/fixme 
- https://docs.codeclimate.com/docs/issues#section-issue-severity
