### ISSUE TITLE
Create documentation for how to create a component and update on the wiki.

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#588]
**Is your feature request related to a problem? Please describe.**
Need to provide guidance on how to create a new component.

**Describe the solution you'd like**
This should be added to the create a component page on the Wiki that already exists.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by awentzel** [comment]
Not sure if this is still required, but, it's your call.

**Comment by chrisdholt** [comment]
closing in favor of #1228
