### ISSUE TITLE
Create code coverage for fast-components-styles-msft with minimum thresholds

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#609]
**Is your feature request related to a problem? Please describe.**
Code coverage should be used for every package
aiming for 50% code coverage and 100% business logic coverage.

**Comment by chrisdholt** [comment]
@awentzel can you provide information on what would be tested in this package? I think our goal of every package having code coverage is good, but I wonder if it is necessary for this package.

cc: @nicholasrice if you have ideas on how we would test the styles packages.

**Comment by awentzel** [comment]
If there is no need for Jest or code coverage then I guess that's fine. Just feels weird that we don't have any unit testing on this project and also no code coverage.

**Comment by awentzel** [comment]
Not needed per standup / Nick.
