### ISSUE TITLE
create code coverage for fast-jss-manager

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#613]
**Is your feature request related to a problem? Please describe.**
Code coverage should be used for every package
aiming for 50% code coverage and 100% business logic coverage.

**Comment by chrisdholt** [comment]
@nicholasrice Is there any work to do in adding tests and setting coverage here since this for the most part only exports interfaces?

If not, I propose closing this issue as "by-design" or "obsolete".

**Comment by chrisdholt** [comment]
@nicholasrice & @awentzel I propose closing this as "obsolete" as there is no logic to test in this package.

**Comment by awentzel** [comment]
Per @chrisdholt closing as obsolete as not necessary for this package.
