### ISSUE TITLE
Do not show the examples tab if there are no examples

### ISSUE THREAD

**Issue by janechu** [microsoft/fast-dna#616]
The user should not see a tab for the examples page if there are no examples.

The development site currently shows the examples view tab even if no examples exist, it should not be possible to switch to an empty tab.

The examples tab should not be visible if there are no examples given. This should be indicated by presence of at least one `SiteCategoryItem` which is passing the slot prop with the value "canvas-example-view".

**Comment by chrisdholt** [comment]
Closing this as the fast-development-site package has been deprecated
