### ISSUE TITLE
Do not display the dev tools if it has no content

### ISSUE THREAD

**Issue by janechu** [microsoft/fast-dna#619]
The user should see the dev tools when it has content available.

1. The user should not be able to open and view the dev tools if the schema and code preview are both not visible
2. The dev tools should not remain open or be able to toggled open between routes if there is no content for it on another route. Example: there is no schema and there is only data for the detail view. If the user selects the examples view which has no data, it should close automatically and the button to activate the dev tools should disappear.

**Comment by chrisdholt** [comment]
Closing this as the fast-development-site package has been deprecated
