### ISSUE TITLE
Fix "method_complexity" issue in checkbox styles

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#635]
The `styles` function has a Cognitive Complexity of 6 (exceeds 5 allowed).

For the time being, this is acceptable in contrast to the potential duplication of styles throughout the function. Reduce the cognitive complexity in `packages/fast-components-styles-msft/src/checkbox/index.ts ` from 6 to 5.

Code Climate reference:
https://codeclimate.com/github/Microsoft/fast-dna/packages/fast-components-styles-msft/src/checkbox/index.ts#issue_5b3c10ac71c5fb00010002a1

**Comment by Ayush-Rawal** [comment]
The code climate link shows now problems, Should this issue be closed? Or is it still relevant?
