### ISSUE TITLE
[foundation] slider readonly deviates from native range control

### ISSUE THREAD

**Issue by yinonov** [Microsoft/fast-dna#6484]
`slider` component doesn't align with native input of type range, readonly property is not supported in the native control, thus, is redundant in the slider component.

should these lines be removed?

https://github.com/microsoft/fast/blob/9220e20045ad0e29ecb1d62028d137d8fc779b52/packages/web-components/fast-foundation/src/slider/slider.ts#L35-L48

https://user-images.githubusercontent.com/15140652/198672962-bfbb488b-b4ab-48bd-beee-77e5f711b199.mov

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955. The documentation site is being updated to showcase projects that may fill the need for a similar functionality.
