### ISSUE TITLE
fix: DesignToken derived values cannot be enums in Fast Foundation

### ISSUE THREAD

**Issue by rajsite** [Microsoft/fast-dna#6529]
# 🐛 Bug Report

When setting a `DerivedDesignTokenValue` on any of the `DesignToken` apis, the type configuration causes enum values to not work as expected and result in a TypeScript type error. [Stackblitz](https://stackblitz.com/edit/fast-enum-design-tokens).

Found that the issue does not reproduce in master, see comments in #6530.

## 💻 Repro or Code Sample

For the enum:

```ts
const Animal = {
  cat: 'cat',
  dog: 'dog',
} as const;
type Animal = typeof Animal[keyof typeof Animal];
```

The following `DesignToken` with a `DerivedDesignTokenValue` :

```ts
DesignToken.create<Animal>({
  name: 'awesome',
  cssCustomPropertyName: null,
}).withDefault((): Animal => Animal.cats);
```

Results in an error:

```shell
Argument of type '() => Animal' is not assignable to parameter of type 'DesignToken<Animal> | DesignTokenValue<Animal>'.
  Type '() => Animal' is not assignable to type '(target: HTMLElement) => "cat"'.
    Type 'Animal' is not assignable to type '"cat"'.
      Type '"dog"' is not assignable to type '"cat"'.(2345)
```

## 🤔 Expected Behavior

I expect the above code to pass type checking as written.

## 😯 Current Behavior

It looks like as written with type is accidentally relying on the default behavior of [distributive conditional types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html#distributive-conditional-types).

## 💁 Possible Solution

Opt-out of the distributive conditional type behavior.

## 🔦 Context

We have a theme design token that all our other tokens derive from, i.e,.:

```ts
export const Theme = {
    light: 'light',
    dark: 'dark',
    color: 'color'
} as const;
export type Theme = typeof Theme[keyof typeof Theme];
```

We are changing from a static default (which avoids the type error) to a derived default based on the users `prefers-color-scheme` configuration which caused us to run into the type error. Currently we workaround the issue using a `@ts-expect-error`.

## 🌍 Your Environment

`fast-foundation@2.47.0`

**Comment by janechu** [comment]
Unfortunately `@microsoft/fast-foundation` is being deprecated, refer to #6955.
