### ISSUE TITLE
Create specific helpers to make it easier to create localizable JSS properties

### ISSUE THREAD

**Issue by prabashn** [Microsoft/fast-dna#654]
**Is your feature request related to a problem? Please describe.**
Currently we have to do things like this in the code:
[applyLocalizedProperty("paddingRight", "paddingLeft", config.direction)]: toPx(10)

This is rather lengthy to write out, and could benefit from some helpers to make it easier to write these sorts of localizable properties out.

**Describe the solution you'd like**
My proposal was to introduce something like the following, so that the left/right will be induced based on the direction passed in.
paddingLeft(config.direction).toPx(10)

Or even better if we could just do the following
paddingLeft().toPx(10)

So that the config.direction is accessible via some global prop (not sure if this is possible). Since a page is likely only in one direction, it should be ok to have it at a global level instead of having to pass it around all over the place.

**Describe alternatives you've considered**
Chris did mention that we can already do stuff like this for spacing related stuff:
padding: localizeSpacing(direction)("2px 3px 4px 5px`)

If this can be modified to be able to omit top/bottom values when you only want to add left/right values, I think it can serve the same purpose.

Another alternative that might even more generic, and results in terser code may be simply:
[`padding-${left}`] = (10).toPx();

Where the 'left' is a dynamic value depending on the page locale direction ('left' for LTR or 'right' for RTL)

**Additional context**

**Comment by nicholasrice** [comment]
Thanks @prabashn! I agree - it is a long and difficult statement to read/write.

I think something that aligns with your first suggestion is the most viable. The below would be easy to achieve with the existing infrastructure for stylesheets defined as functions:
```
{
    [paddingLeft(config.direction)]: toPx(10)
}
```

Are there any other functions besides the ones listed below that you would like to see added?
- `paddingLeft`
- `paddingRight`
- `marginLeft`
- `marginRight`

**Comment by prabashn** [comment]
Any thoughts on the last approach?
['padding-${left}'] = (10).toPx();

Seems a lot more flexible than having whole lot of helper functions that we may need more of later. This would require exposing a 'left' or 'right' property in the design system so that it changes based on the locale's "directionality".

**Comment by nicholasrice** [comment]
I agree we should try to minimize the number of helper functions. That is the goal of the `applyLocalizedProperty` function.

I'm conflicted on exposing `left` and `right` properties on the config object. I understand the goal but I think `direction` is a more concise way to capture the underlying information. To me, `left` and `right` values are derivatives of direction and I would rather use a single value to capture a single idea than two values. On the other hand, I do like the ergonomics of `left` and `right`.

I think the actual syntax of your proposal would shake out to the following:
```
{
    [`padding-${config.left}`]: toPx(10);
}
```

We could introduce methods instead, for the following syntax:

```
{
    [`padding-${left(config.direction)}`]: toPx(10);
}
```
