### ISSUE TITLE
Design system not working in fast-development-site-react

### ISSUE THREAD

**Issue by nalogiudice** [Microsoft/fast-dna#694]
Design system values showing as undefined.

See screenshot:
<img width="622" alt="screen shot 2018-07-13 at 5 32 27 pm" src="https://user-images.githubusercontent.com/22480660/42718881-bab2460a-86c2-11e8-9fd3-0688e1f3e8ba.png">

**Comment by chrisdholt** [comment]
@nalogiudice Is this some values or are all values showing up as undefined? Is this scoped to a specific file or does the design system not work whatsoever?

Any more detail you can add here would be helpful.

**Comment by nicholasrice** [comment]
Closing this because it is very stale. We can re-open if we're still seeing this behavior.
