### ISSUE TITLE
msft-docs.azurewebsites.net not working under IE 11

### ISSUE THREAD

**Issue by raymondduan** [microsoft/fast-dna#713]
**Describe the bug**
fast-dna supposed to support IE 11, however currently the demo site msft-docs.azurewebsites.net errors out under IE 11 (Syntax error in main.js (10, 27699)). Probably due to bundling issue.

**To Reproduce**
Open https://msft-docs.azurewebsites.net/ under IE 11.

**Expected behavior**
The page should render without error.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: IE 11
 - Version 11.0.75

**Comment by nicholasrice** [comment]
Thanks for reporting this @raymondduan

**Comment by awentzel** [comment]
Worst than this not a single thing on the page loads.  We should investigate this at higher priority.

**Comment by chrisdholt** [comment]
@awentzel we should discuss this and re-evaluate priority and impact first. I think the cause is relatively simple. We're likely exporting and delivering a version of JS that IE11 can't handle. It's not that the code is broken, it's that the browser doesn't support what's being delivered to it. Babel can fix this, but we should discuss prior to making any changes here.

**Comment by awentzel** [comment]
My only problem is the if a user looks at the tool in IE it’s doesn’t look good for our product or what we build and could impact the perception of a great product teams should want to use.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by awentzel** [comment]
https://msft-docs.azurewebsites.net has been deprecated and the replacement, now called "Component Explorer" is now on https://explore.fastdna.net. Also, it too does not run on IE11.  If we say our components support IE11 should our websites also support this and thus would require transpiling into ES5, currently we're transpiling to ES6.
