### ISSUE TITLE
Update cursor for non interactable areas in the UI

### ISSUE THREAD

**Issue by eljefe223** [Microsoft/fast-dna#714]
Update cursor for non interactable areas in the UI. 

Update areas of UI that are not interactable that currently show the text insert cursor to be the white arrow cursor.

The areas are "FAST Documentation title".

"Building blocks" heading.

"Component: …" and "Beta" text.

![image](https://user-images.githubusercontent.com/37851214/42953538-85e3c5ae-8b2f-11e8-9706-b31432edfa95.png)

**Comment by chrisdholt** [comment]
Can you update the title and description of this to mention that this is specific to the fast-development-site-react package?
