### ISSUE TITLE
Evaluate Cypress for Web deliverables

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#716]
Cypress provides a comprehensive testing suite with CLI/App/Dashboard that allows testing functional UI components.  The thought here is that with this we can wire up functional testing with ease easy to maintain and review issues with the team from the portal.  Applitools, may also still be used on top to test Visual UI scenarios or sites.

1. Learn and implement a sample Cypress implementation and get feedback from Collaborators

Deliverables:
Include a remote branch with example implementation for packages that have a UI/UX.
1. Discuss with team the folder structure
2. Discuss with team the pros/cons
3. Discuss with team if there are other requirements we should consider.

**Comment by awentzel** [comment]
** Folder Structure **  
[Recommended default](https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests.html#) though, this does not take into account a mono-repository.  Will determine the proposed structure once get into the code to try this out.

**Pros** 
1. [Key Features](https://www.cypress.io/features/)
2. [Why cypress](https://docs.cypress.io/guides/overview/why-cypress.html#Features)
3. [Key Differences](https://docs.cypress.io/guides/overview/key-differences.html#)
4. [Trade offs](https://docs.cypress.io/guides/references/trade-offs.html#)
6. [Best practices](https://docs.cypress.io/guides/references/best-practices.html)

**Cons**
1. No current support, but, planned for Edge/Safari/Firefox browsers [refer](https://docs.cypress.io/guides/guides/launching-browsers.html#)


**Unknowns**
1. Possible integration concerns with Jest. Can be integrated side-by-side
2. We don't use Mocha how does this impact code reporting
3. How does integrate into CircleCI?
4. How can be executed nightly for site/page bases regression testing launched from CI
5. Is Sauce labs/Applitools still needed?

**Comment by awentzel** [comment]
**Example Implementations**
[Cypress, React, Jest, Babel, Webpack](https://github.com/kentcdodds/jest-cypress-react-babel-webpack)

**Comment by awentzel** [comment]
**Wiki**

To install locally
```bash
$ npm install cypress --save-dev
```
To Open Cypress
```bash
$ node_modules/.bin/cypress open
```

**Comment by awentzel** [comment]
Ready for review @chrisdholt, @nicholasrice , @janechu

**Comment by chrisdholt** [comment]
A few questions:

1. What determines the project Id? Is there a way that it can be more intuitive and project based?
2. Can you share some of the purpose for running two webpack dev servers simultaneously?
3. On the script definitions side of things, does `build:test` actually build the test or does it functionally run? I would suggest naming the npm task specific to what is happening. Typically when we use build it is packaging it up and not executing the file with webpack. Want to be sure I understand what is happening so we can be consistent.

**Comment by awentzel** [comment]
@chrisdholt  
1. Project ID is created by the dashboard on Cypress upon initial sign-up, which I've already done.
2. The first Webpack dev server is to run the application (msft-docs, for example). The second is to run Cypress integration tests against that first server.  It may be possible to combine, but, it depends on what we're planning on testing against.  For example, we could test against development site or an already hosted production website.
3. build:test has been removed to bring inline with other tests.  Code updated for package.json above.

**Comment by chrisdholt** [comment]
@awentzel I notice that Cypress stores video files in the repo locally. Is that correct? That would add a ton of weight to the repo itself. Can we store it outside the repo as an alternative? If we want the video functionality and the only way to have it is stored in the repo - I'm not sure we want to include it.

**Comment by awentzel** [comment]
@chrisdholt  It does store when it runs locally during development testing run and so would be included in the source.  It does delete all of these files at the start of execution so it's doesn't yet do visual regressing diff testing.  When running on the CI it would be available and stored on the CI with the history of that job.  While these tend to be large files, the way GitHub is architected this is not a huge perf cost when uploading and downloading.  The benefits I believe would outweigh the cost.  There is a feature to to turn off video feature for local testing and only use that in CI.

More details https://docs.cypress.io/guides/guides/screenshots-and-videos.html

**Comment by awentzel** [comment]
@janechu @chrisdholt @nicholasrice last chance to provide thoughts on this Proposal before it's approved.  Thanks

**Comment by chrisdholt** [comment]
Don't we need approvals in order for this to be approved?

**Comment by chrisdholt** [comment]
Still curious if we need two webpack servers. Could we use one of the preprocessors instead?
 https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/preprocessors__typescript-webpack

**Comment by chrisdholt** [comment]
@awentzel does Cypress support multiple frameworks (angular, vue, polymer)? More of a question for future proofing. I think a great thing about our unit testing with Jest and Enzyme is that it supports multiple frameworks. If Cypress supports multiple frameworks I think that's a solid in support of it.

Were there any alternatives that seemed to compete with Cypress outside of the Applitools investigation? Anything you can provide in terms of trade-offs, etc?

**Comment by awentzel** [comment]
@chrisdholt We're already using the preprocessor.  Cypress is 100% JavaScript and no Selenium/WebDriver required.  There is a link above for trade-offs.  I reviewed the top 10 equivalents.  This was the best.

During implementation, it can be investigated if 2 webpacks are really required.  Cypress performs better than all the other frameworks which is one of its key selling points.

**Comment by awentzel** [comment]
TestCAFE is probably the closest competitor.  The documentation, API, and gui isn't quite as good as /cypress.  which literally has some of the best documentation I've seen.  Very well done project.  It's performance is outstanding with clear fairly straightforward implementation that doesn't require a lot of code.  It's my recommendation.

**Comment by janechu** [comment]
I'm a little late jumping on here but I feel like it's a big miss to go with an E2E testing solution that misses the ability to check on safari and firefox. It's more of a E2ChromiumBasedBrowsers.

I think we need to go for a solution that doesn't box us into an API but provides more flexibility. There are too many trade-offs for me with missing these browsers.

**Comment by awentzel** [comment]
Ability to support multiple browsers is in the pipeline and was a link I provided a while back to upvote the feature.  If you haven't yet done so, you should.  This is by far the best framework, most flexible, most robust, and most performant of anything on the market today. It's new, a non-selenium webdriver solution that allows us to test anything in the browser, even the network itself.  We can still test other browsers using Applitools during the visual regression testing until then.  This is a stepping stone and we should be focused on functional regression testing which we don't have today. This steps us into a future framework that is very well supported, outstanding documentation and is as close as anything gets to E2E.  No other framework comes anywhere near this close to E2E.  And knowing that E2E is in the works it puts us in a place where we can have a stable API for a while to come.

**Comment by awentzel** [comment]
https://github.com/cypress-io/cypress/issues/310 to upvote cross-browser functionality.

**Comment by janechu** [comment]
@awentzel so that issue has been open since Nov 2016. If/when they get to it is hazy at best, at the bottom of their [issue on the topic](https://github.com/cypress-io/cypress/issues/310) it has been deemed not a priority.

They have the edge in performance and ease of use, but that does not override what I consider to be a core requirement of actual cross browser testing.

**Comment by awentzel** [comment]
I did discover Chroma which sounds about as great as Cypress.  Though it's Selenium based and takes a dependency on Storybook.  We investigated Storybook and wouldn't fit into our architecture or philosophy for testing components.  That said, i'm discussing with Chroma a partnership where they might build an SDK for us so we don't have to take a dependency on Storybook.  Waiting to hear back from Chroma as the sales team is meeting with the engineering team to discuss further details.

**Comment by awentzel** [comment]
Recent email exchanges with Cypress have let to a discussion they that are working on an engine for FireFox and IE.  I requested Edge as well.  

Chroma has updated an API for us to use their platform without the dependency on Chroma.  So I'll be investigating Chroma against Cypress.io.  Both are JavaScript driven not Selenium.
