### ISSUE TITLE
Create a horizontal overflow component

### ISSUE THREAD

**Issue by janechu** [Microsoft/fast-dna#725]
There should be a new component in `fast-layouts-react` for scrolling through multiple items.

User stories:
- Tony is looking for a new computer game to buy for his daughter Amy for her birthday. He goes onto his computer and navigates the browser to a site that sells games. He sees a list of games but not the one his daughter wants so he clicks an arrow button to show more games. He sees the game his daughter would be interested in and clicks on it which directs him to a purchase page.
- Bobby is a blind man, he's searching on the internet for a refrigerator. He visits a site and using keyboard controls he finds a list of refrigerators. He tabs through the list and finds one with the brand he likes and selects it. This redirects him to another page with the full list of information about that refrigerator.
- Julia is a woman who is waiting at a bus stop after dealing with her overbearing boss. She starts browsing the internet and searches for articles about comfort food. She reads an article about healthy eating being stress relieving and at the bottom of the article there is a caption entitled "recipes high in antioxidants" and below is a list of images of food. She does not see food she is interested in so she swipes across to see more. she finds an image of food she is interested in after she has swiped to the next image set and selects it which navigates her to a page with a recipe for that food.

Functional requirements:
- Multiple items are shown depending on the width of the component
- Two buttons which will allow next/previous movement of items, these should show up on the left/right sides as dictated by the LTR of the page. When clicked they will have an animated scrolling behavior, they will scroll the items in the direction indicated until the next set of items is visible. The next set should be the next or previous set that includes the last item that was previously hidden or partially viewable
- Scrolling through items via touch
- Scrolling through items via tab

Technical spec:
- Scrolling distance is calculated when the next/previous buttons are clicked. It will calculate this by determining the last item that is partially visible or if none is partially visible use the next item that is hidden and moving the items until that item is moved all the way to the other side of the carousel while remaining in view.

Implementation example:
```jsx
<HorizontalOverflow>
    <button slot="previous">Previous</button>
    <img src="https://placehold.it/300x300" />
    <img src="https://placehold.it/300x300" />
    <img src="https://placehold.it/300x300" />
    <img src="https://placehold.it/300x300" />
    <img src="https://placehold.it/300x300" />
    <button slot="next">Next</button>
</HorizontalOverflow>
```

Scenarios:
- previous button is not passed
    - do not show previous button
- next button is not passed
    - do not show next button
- no items are passed
    - do not show the component, throw a warning in the console that items must be passed for the component

**Comment by janechu** [comment]
@chrisdholt @nicholasrice do either of you have any thoughts about this spec for the new layout component horizontal overflow?

**Comment by nicholasrice** [comment]
Regarding the "no items are passed" scenario:
I don't think we should log to the console when no items are passed. I think the reality is that _no items_ isn't really a valid user story we need to provide a design solution for. The component shouldn't error, but not having items is likely a bug from another part of the app. It is also inconsistent - why would we log if no items are present but not when next/prev button props are not supplied?

Can you clarify what you mean by "do not show the component"? Do you mean we will not render any HTML? Or simply that there will be no visible elements?

**Comment by chrisdholt** [comment]
Just a couple of questions/thoughts:

- Should we consider including default next/previous "flippers" if none are passed? 
- I noticed that we call out that the items will have an animated scrolling behavior. Is this a "default" and could we support the ability to change/override it?
- Along the no-items instance that @nicholasrice mentioned, my assumption is that if there is no overflow, the flippers wouldn't show as well; which would be the same if there are no items. Correct?

**Comment by janechu** [comment]
@nicholasrice sure, we can skip the warning I thought it might be nice in a development environment, we would not render any HTML in the event there are no elements passed

@chrisdholt 
- This is a layout, so no styles are theoretically present, would we just use unstyled HTML buttons?
- Sure, are you thinking speed/acceleration/decceleration?
- Yes

**Comment by awentzel** [comment]
For accessibility, I recall the desire to count how many items and then speak to that through aria-label or some other component method.  Is this something we should consider here or would that be too prescribed?  Also, the screen reader would want to know about the next button in the top of the markup so it's read right away versus at the end?  Mentioned this just because you had code examples. I could see this as spoken too in documentation instead of markup.

**Comment by chrisdholt** [comment]
@awentzel I think detailing the number of items is too prescribed and making some assumptions. I recall questions from developers around that, but our conversations from accessibility contacts actually mentioned that it's not "expected" and not "required". If it's a list, the browser should share the number of items available.

Regarding next/previous buttons; I think our guidance here would be that in most cases these should be hidden from screen readers (IE, the instance of a list, a user will simply move through them). Either way, those details are best left to those implementing the flippers. We should be fairly hands off in my opinion since they are providing their own components for those purposes. In my opinion we should only attach the additional behaviors required.

**Comment by nicholasrice** [comment]
I'm good with those changes.
