### ISSUE TITLE
Improve color system for MSFT packages

### ISSUE THREAD

**Issue by nicholasrice** [Microsoft/fast-dna#728]
# FAST design color system proposal

What follows is a proposal for how color values can be defined, accessed, manipulated and applied to stylesheets. The `fast-colors` library will export all utilities and color tools. The configuration values and style applications will be applied to any system using the MSFT design system.

Stated goals of the color system additions are to:

- facilitate theme switching through adjustments to foreground and background colors
- automatically ensure contrast ratios between text elements and their backgrounds when that background is known
- prevent significant arbitrary color use by using color stops in a palette

## Design System & `fast-components-styles-msft`

~~The MSFT design system will introduce five configuration inputs that will be used to derive color palettes. All color values should be hexadecimal colors.~~
The MSFT design system will introduce five configuration inputs. These inputs will be defined as a color palette. A MSFT color palette will consist of 11 color values with the following interface:
```ts
interface ColorPalette {
    0: string; // <-- lightest
    1: string;
    2: string;
    3: string;
    4: string;
    5: string;
    6: string;
    7: string;
    8: string;
    9: string;
    10: string;
    11: string; // <-- darkest
}
```

- *accent*: The accent colors will be used to apply attention-drawing highlights to UI elements such as primary actions.
- *foreground*: The foreground colors will generally be used to assign color to foreground elements such as text.
- *background*: Background colors will generally be used to as a source for background elements such as back-plates and backgrounds.
- *light*: Light colors will be used when an element should be light irrespective of foreground and background colors.
- *dark*: Dark colors will be used when an element should be dark irrespective of foreground and background colors.

Below is an example of using config color values in a StyleSheet:

```js
const styles = {
    color: (config) => config.foreground[0], // #FFF
    background: (config) => config.background[3]; // #E6E6E6
}
```

The `fast-components-styles-msft` package will also export commonly used Microsoft colors such as brand colors and neutral grays.

### ~~Alternative~~
~~Alternatively, the design system inputs could be palettes themselves (a fixed-length array of colors) and not a source color for a palette. This would provide more flexibility and opportunity for customization. On the other hand, it complicates the design system by adding a complex data structure. Our MSFT stylesheets will make an assumption about the number of colors available in a palette and that information would need to be communicated to developers.~~

~~If this strategy were taken, clear documentation on best practices for assigning these color palettes would be supplied. The default theme used by `fast-components-styles-msft` would utilize light background / dark foreground palettes.~~
*The alternative described above is now the POR*

### Contrast helpers

The `fast-colors` library will expose several new functions intended to adjust a color to a specific contrast ratio against another color. This will allow us to ensure that, given some background color, our foreground color will meet contrast ratios.

#### `function contrast(target: number, foreground: Color; background: Color;)`

**Arguments**

1. **target**: The target contrast ratio of foreground over background
2. **foreground**: The return value will be this color augmented with any necessary contrast adjustments
3. **Background**: The color to which the foreground's contrast will be evaluated against

If the color already exceeds the provided contrast ratio, the color will be returned unchanged.
Otherwise the color will be adjusted to increase contrast until either:

- Contrast is reached, at which point the color will be returned
- Contrast cannot be increased, at which point the color with the most contrast will be returned. In development builds, a console warning will be emitted so that the developer knows that contrast is not being met.

Contrast will be adjusted in the direction of the foreground color relative to the background color. I.e, if foreground is lighter than the background, foreground will be lighted to adjust contrast. If foreground is darker than the background, foreground will be darkened to adjust contrast. If both foreground and background are the same, the relative luminescence of the color will determine if the color is *light* or *dark*. If the color is *light*, the foreground will be darkened. If the color is *dark*, the foreground will be lightened.

```js
    const styles = {
        color: (config) => contrast(4.5, config.foreground, config.background[3]),
        background: (config) => config.background[3]
    }
```

#### `function [lightContrast, mediumContrast](foreground: Color, background: Color)`
Two additional functions will be exposed: `lightContrast` and `mediumContrast`. These will be light wrappers over the `contrast` function that assign target contrast ratios of 3 and 4.5 respectively:

**Arguments**

1. **foreground**: The return value will be this color augmented with any necessary contrast adjustments
2. **Background**: The color to which the foreground's contrast will be evaluated against

```js
const styles = {
    color: (config) => mediumContrast(config.foreground[3], config.background[3]),
    background: (config) => config.background[3]
}
```

## ~~FAST MSFT colors~~

~~A new package (`fast-colors-msft`) will be added to export commonly used Microsoft color values. This would include commonly used brand colors and neutral grays.~~

**Comment by chrisdholt** [comment]
@nicholasrice Do we need a package specifically for MSFT colors? If all we are exporting as color values, is there a reason we can't export those from the MSFT package itself?

**Comment by nicholasrice** [comment]
@chrisdholt which MSFT package are you proposing would export the colors?

Regarding caching - any new combination of arguments would create a new palette. The goal is to not generate the same palette twice. If the inputs are the same, we can safely return a cached output because range is a pure function.

**Comment by chrisdholt** [comment]
Solid on caching, thanks for detailing.

Proposal would be `fast-components-styles-msft` for exporting color constants.

**Comment by nicholasrice** [comment]
Yea I considered that. My reasoning for creating a new package is that `fast-components-styles-msft` is a set of stylesheets and that we'd set the precedent of breaking out colors. I'm open to doing that though - I'm not a huge fan of adding another packages just for MSFT colors but it seemed the most consistent with our current architecture.

**Comment by chrisdholt** [comment]
I'm open to the idea, but agree that I'm not a huge fan of adding a package just for constants that have a direct relation to the msft styles package.

For myself, based on the current architecture, I would expect `fast-colors-msft` to extend upon the `fast-colors` package. While the package would directly relate to the concept of colors, It doesn't seem to directly relate or extend the purpose of the `fast-colors` package.

**Comment by nicholasrice** [comment]
Yea that's why I didn't propose extending `fast-colors`.

I'm good with adjusting the proposal so that colors get exported from `fast-components-styles-msft`.

**Comment by janechu** [comment]
I'm good with the new package for MSFT, I think the alternative is looking more flexible (array of colors) I would suggest at least 10 colors in an array be added to the design system so that we can have a wide enough range to select from.

**Comment by awentzel** [comment]
I'm not good with yet another package.  I think `fast-components-react-msft` is the design language for MSFT as such, this is the best place for the design system colors to be defined.  I think other packages then also would have their own definitions.  For example, if there was a `fast-components-react-fabric`.  This package then would depend on `fast-colors`, but, could define it's own values.

I understand the complexity, but, really like the idea of just having `fast-colors` and being able to pass in a JSON configuration to define the colors.

I also, really liked our initial color system for MWF where it was based on tints, shades, etc which came in very useful for styling aspects of components. It feels like this will be needed at some point.

When using decimals i believe it's more maintainable to preprend `0.` so `.65` would be `0.65`.

**Comment by awentzel** [comment]
@nicholasrice I agree, that's more intuitive. 

One thing I thought about on the function naming between LightContrast, MediumContrast, DarkContrast is that it might be more flexible to simply have Contrast() and then pass in an enumeration for the level of contrast.  This way if we need to add more contrast levels it's easy, less functions, and more maintainable.

Otherwise, I like how this is shaping up.

**Comment by nicholasrice** [comment]
@awentzel That is accounted for - see the "contrast" helper.

Based on conversations with @Falkicon I think this is going to change significantly - I'm going to create a new proposal and close this one.
