### ISSUE TITLE
Create a "Dialog" component

### ISSUE THREAD

**Issue by chrisdholt** [Microsoft/fast-dna#729]
"Dialog" should be added as a new component in `fast-components-react-base`.

**User stories:**
* Joanna has some friends coming over and is searching online for some adult beverage ideas. She visits a website of a local distillery and a form overlays the screen asking her to confirm she is over 21 years of age by entering her birthday.
* Harold is in the process of removing old data sets from his company's content management system. He selects a group of data and clicks delete. A popup appears asking him to confirm that he wants to delete the selected files permanently.
* Meredith is browsing news articles online and clicks a link to a local newspaper story about an upcoming heat wave in the region. She is informed that she has read through an allotted number of free articles for the month and must either login or become a subscriber of the news site to continue. Meredith tries to continue interacting with the web page, but she's unable to. Meredith decides to subscribe to the online newspaper because they are running a special.

**Functional Requirements:**
- A user should be prevented from interacting with content outside the dialog when the modal behavior is present.
- A user should be able to interact with elements of the page when modal behavior is not present.
- A user should be able to configure the width and height
- A user should be able to add arbitrary markup or components to the content region of the dialog.

**Technical Requirements:**
- The component consumes 100% of the width and height of it's parent container.
- The component should require a first-class prop to manage the component's visible state as well as a first class prop to support opt-in of "modal" behavior to address any required first-class accessibility support for these component scenarios. 
- Content region width and height are variable and therefore should be set explicitly via props. These props should be set as a string to support any valid CSS values (percentage, pixel, vh, vw, etc).

**Implementation Example:**

```jsx
<Dialog modal={true} width={500px} height={80vh}>
     <MyHeading />
     <MyParagraph />
     <MyButton text={close} onClick={this.handleDialogClose} />
</Dialog>
```

**Comment by janechu** [comment]
I would split this into two sections, the functional requirements (requirements from the users perspective) and the technical requirements (code requirements).

This can make it more clear as to what the user is expecting when they interact with the component and what the developer who is working on the item expects to implement (from a high level, I wouldn't expect this to cover everything).

An implementation section for how this would look to implement would also be welcome so that we can know if it is intuitive.

**Comment by awentzel** [comment]
I'd like to dive a little deeper as well to include Accessibility Requirements or at least link to where the a11y spec lives.  One thing I really love about the proposal process is that it acts as the starting point for documentation.  

**Requirements**
for consideration...
- What about ability to include one or more buttons depending on modal modes?
- What about ability to include any markup? What sub-components can become part of the modal or is it completely open canvas?
- Would it make sense for Dialog to share functionality with Alerts? Perhaps a Dialog could Pop or Not?   By definition, does a Dialog pop? 
- Are there any interaction requirements or guidance we should include? 
- What would be the behavior on mobile devices or small screens?  Scrolling content within dialog?

**Comment by chrisdholt** [comment]
@awentzel I think a lot of this is going to be documentation and education for this component. Inline below:

- What about ability to include one or more buttons depending on modal modes? -> I don't think the buttons directly correlate to either of these. My question on this is "why do we care". From a spec standpoint, these require at least one focusable element. I don't think we care too much what that element is, but we should inform about it in the accessibility requirements section.
- What about ability to include any markup? What sub-components can become part of the modal or is it completely open canvas? -> I think this is included within the spec. This component just takes children.
- Would it make sense for Dialog to share functionality with Alerts? Perhaps a Dialog could Pop or Not? By definition, does a Dialog pop? -> Again I don't know that we want to be prescriptive in this from a base component scenario. The component is different from what triggers it. It can be triggered by a component like a button, or it could be rendered onload as a paywall or auth.
- Are there any interaction requirements or guidance we should include? -> We'll include only required instances for an accessibility standpoint on the base side. We can be more prescriptive with the MSFT instance.
- What would be the behavior on mobile devices or small screens? Scrolling content within dialog? -> I think this depends on each scenario. We can be more prescriptive in the MSFT instance.
