### ISSUE TITLE
Update schemas to check for dependencies

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#73]
if a schema has dependencies, check to see if required exists.

See price component - if a dependency needs the required array, this should be checked, if it does not exist add it

Note: Dependencies have an array which, if it exists should be creating schema variations. These variations should have a modified required array to account for the array of dependencies.

**Comment by janechu** [comment]
This is not a priority for now, leaving it in the backlog until it is re-prioritized.

**Comment by awentzel** [comment]
I've assigned this to @janechu, please close if you feel this work is no longer needed.  Thx

**Comment by janechu** [comment]
This is no longer valid as permutator has been deprecated and removed from the repository.
