### ISSUE TITLE
Layout columns are not displaying properly in firefox

### ISSUE THREAD

**Issue by janechu** [Microsoft/fast-dna#737]
Tested in MacOS firefox latest:

![Screen Shot 2018-07-26 at 6.52.26 PM.png](https://images.zenhubusercontent.com/59557d9061b4ca3b0a72c253/57253228-f40f-46bf-abae-97c31ae33474)

It would appear the number of columns is not correctly showing.

**Comment by chrisdholt** [comment]
I’ll grab this @janechu

**Comment by chrisdholt** [comment]
Synced with @janechu who provided repro steps by adding an <img /> inside the grid item that is larger than the grid area. This does repro, but I believe this repro is actually by design. Following up for a repro that matches the above image.

**Comment by chrisdholt** [comment]
Just repro'd the above by creating the same layout. Issue seems to be with how "auto" is handled by different browsers. Pushing a fix.
