### ISSUE TITLE
Create tabs as a composable set of components

### ISSUE THREAD

**Issue by janechu** [Microsoft/fast-dna#749]
There should be a ~~tab panel~ tabs component in `fast-components-react-base` that implements the tab ~~panel~~ interface.

User stories:
- Wanda has come back from a long day at work and is trying to order some food online. The restaurant she's looking at offers drinks, main courses and deserts. Not wanting to spend the extra premium on drinks which are currently shown, she clicks on main courses and makes a selection from the items that show up. She completes her order and her food is delivered.
- Amy is trying to find book a flight, she sees the current deals for today and next to it is another section for booking. She clicks the section for booking and the current deals are replaced with a form for her to fill out booking information. She completes the form and her flight has been booked.

Functional requirements:

**Initial view**:
- Multiple selectable items appear next to each other, one item has an "active" state
- Below the selectable items is content that corresponds to the currently selected "active" item

**Selecting an inactive item**:
- When an inactive item is selected, it's state is changed to "active" and the previous "active" item is changed to inactive
- Content changes corresponding to the tab selected
- Items can be set to an active state by mouse click or by left/right arrow keys once the selectable items are in focus

Technical spec:
- Content is swapped when a different tab is selected by the user
- An optional callback is used to inform the user what uuid is for activation

Implementation:
Note: updated to reflect @chrisdholt notes relating to https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel where:
- **Tabs** - the containing component for the tab elements and tab panels
- **TabItem** - the container for both the tab element and the tab panel it controls
- **Tab** - the controlling element
- **TabPanel** - the tab panel containing content relating to the controlling tab element

```diff
-<TabPanels selected="id01">
-    <TabPanel id="id01" slot="tab-panel">
-        <Tab slot="tab">
-            Tab 1
-        </Tab>
-        <TabContent slot="tab-content">
-            Tab 1 content
-        </TabContent>
-    </TabPanel>
-</TabPanels>

-<Tabs selected="id01">
+<Tabs activeId="id01">
+    <TabItem id="id01" slot="tab-item">
+        <Tab slot="tab">
+            Tab 1
+        </Tab>
+        <TabPanel slot="tab-panel">
+            Tab panel content
+        </TabPanel>
+    </TabItem>
+</Tabs>
```

Naming clarification: The HTML attribute role of *tabpanel* although one word is, according to spec, two words "tab panel" and as such we will use this as the basis for naming for the tab panel component when implementing the component name and slot.

Scenarios:
- No ~~TabPanel~~ `TabItem` is passed
    - Do not show ~~TabPanels~~ `Tabs`
- A ~~TabPanel~~ `TabItem` is missing `Tab` or ~~TabContent~~ `TabPanel`
    - Do not show the ~~TabPanel~~ `TabItem`

**Comment by chrisdholt** [comment]
Overall I think this looks good. A few thoughts on implementation as I think there are a few things to make sure we consider regarding accessibility and the interaction model.

The recommended implementation is for tabs to become active when they receive focus, and I think this is the most common pattern, so my suggestions are based on following this recommendation from the W3C (https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel). While these can be constructed in a way that utilizes enter/space to activate the tabpanel, that seems to be currently recommended only when the content is not already available on the page.

I know we've had some internal conversations regarding using the <button> element for the tabs. I think this is fine, but we will need to manage a few things. We'll need to remove any non-active tabs from the tab order as well as prevent default on enter or space as the tabs will already be active when they've received focus.

I've seen some people in the past advocate for supporting users to tab through these elements as well as use the arrows to move/manage focus. The spec I noted above presents a clear interaction model that doesn't support or detail tabbing through the tabs, and I think there is likely good reason for that. Consider a common scenario where there are elements within the tabpanel which are active and focusable. If tabbing allows a user to move between the items as well, you would need to move through all tabs to reach the focusable content that is currently active within the tabpanel. I think the fact that the interaction model doesn't support it as well as the confusion that could be provided to users is enough to not support tabbing through the tabs fo the tabpanel.

One last thing with the implementation as noted above is that all tabs must be contained within a tablist. If we can slot things above and still render all tabs passed into a tablist I think we are ok. A rough structure that would be expected with limited markup would be below.

```
<div class="my-tabpanel">
    <div role="tablist">
        <button role="tab" />
        <button role="tab" />
    </div>
    <div role="tabpanel" />
    <div role="tabpanel" />
</div>
```

**Comment by nalogiudice** [comment]
Additional thoughts - do we want to allow elements other than buttons to control the tabpanels? We have all seen cases of this in the past, so I believe it is important to think about.

I have used the above resource that @chrisdholt has linked to build-out accessible tap/tabpanels in the past and it worked well. Arrowing through the list (tabs) while tabbing through any actionable items (in tabpanel) makes the most functional sense.

**Comment by chrisdholt** [comment]
@nalogiudice I would expect that buttons can take content such as images or text, but so long as the accessibility and interaction model are valid, it doesn't matter whether we use buttons or list items, etc. I would suggest that the tabs within the tablist would be buttons where we manage focus. In the example below, we just need to remove non-active buttons from the tabindex, the active button is still in there. As long as the button itself takes children, I think we are good.

```jsx
<div role="tablist">
    <button role="tab" />
    <button role="tab" tabindex="-1" />
    <button role="tab" tabindex="-1" />
</div>
```

**Comment by janechu** [comment]
@nalogiudice for now I don't think so, we are choosing a common pattern and following the assumption that implementations can style and inject whatever necessary children they decide on.

I think we're all agreed on the interaction model, I'm marking this as accepted.
