### ISSUE TITLE
Update grammar used in unit testing output

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#75]
Some of these output statements do not make sense and should be written with better grammar. 

For example,
"should the correct number schema IDs" It's clear what's being tested.

Reference IDs
    ✓ should the correct number schema IDs
    ✓ should return the correct schema IDs

  Deep reference IDs
    ✓ should the correct number schema IDs

  Locations of properties
    ✓ should the correct number of locations

  Reference resolver
    ✓ should generate correct number of references

  Schema permutator
    ✓ should generate correct number of schemas

  Property resolver
    ✓ should not find any $ref or allOf properties

  Get an example
    ✓ should return a single example from the required data available

  Get an example of an array
    ✓ should return a single example from the required data available

  Get an example of nested arrays
    ✓ should return a single example from the required data available

  Resolve a recursive reference
    ✓ should not throw a circular reference error

  11 passing (282ms)

**Comment by awentzel** [comment]
Someone would need to run the tests to verify.  I'm not aware if they have been updated or not.

**Comment by nalogiudice** [comment]
Which tests? I looked into this a little bit and could not repo
