### ISSUE TITLE
Allow FormItemSelect to return a number instead of string only

### ISSUE THREAD

**Issue by brandonthomas** [Microsoft/fast-dna#753]
When handling enums it's sometimes necessary to do so using the underlying type (number/int). It would be great if, when specifying enum, I could set the type on the field to number and have a number returned instead of the string value. I think a mapping strategy would need to be thought out since not all enums are computed.

Existing:
`enum: [
  "large",
  "medium"
]`

Future?
`enum: {
  "large": 1,
  "medium": 4
}`

**Comment by nicholasrice** [comment]
Thanks Brandon,

I don't think I fully understand the issue. In your code sample, are you refering to enumerating a number JSON schema?

**Comment by brandonthomas** [comment]
The issue I’m having here is basically that when I pass an enum I only get a string back when a selection is made. Since most languages use an int/number as the underlying type of enum I’d expect to get that back instead. The reason for this is that at runtime the component I’m feeding the data into needs an int. A string not associated with anything doesn’t work. To mitigate this I have to do the conversion in runtime on my side in my Redux reducers and in my render method (neither are ideal). If I could just get an int/number back I could remove all that code and just use the raw data.

Brandon

**Comment by nicholasrice** [comment]
I think this is really a limitation with JSON schema itself. To my knowledge, there is no way to associate a value to an enum key in the schema. If you know of relevant examples though I'd love to take a look at them and see how it was accomplished. 

To solve this issue in our own projects we've made use almost exclusively of [TypeScript's string enum](https://www.typescriptlang.org/docs/handbook/enums.html#string-enums) capabilities. It has worked well for our purposes, though I recognize that won't necessarily work for all use cases.

**Comment by brandonthomas** [comment]
Ya my main issue is that I don’t own the card piece so I have to do the conversion on my side and pass the number enum value to get it to work and do the conversion back again to display meaningful info. I could talk to the team about using a string enum but ya…I’m limited here. My thought would be to solve this by making the consumer pass a mapping so that the form doesn’t have to make any assumptions.

Something like
enum : {
  value: 1,
  anotherMeaningfulValue: 2
}

**Comment by janechu** [comment]
Unfortunately we are mapping to the JSON schema spec as closely as possible so the data and the schema should be 1:1 or too many complexities will arise.

We may be open to some kind of conversion utility if this turns out to be a widespread issue but the form generator itself should not have to re-interpret the data.

**Comment by brandonthomas** [comment]
Understood. I'm not using selectors at the moment so I can probably make thus a bit simpler by doing so on my end. Thanks for looking into it!
