### ISSUE TITLE
Inconsistent naming guidelines in package name

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#763]
**Describe the bug**
In other packages `react` always proceeds the name of the design language. however, in this package it's reversed so we're not following the same naming standards and it's not consistent.

**Expected behavior**
Rename from `fast-markdown-msft-react` to `fast-markdown-react-msft`

**Comment by awentzel** [comment]
Assigning to @chrisdholt  as this has publishing ramifications, but, should be fixed for consistency.

**Comment by awentzel** [comment]
@nicholasrice We will want to be extra careful going forward that new packages are created to the same naming standards as others or it's going to get increasingly difficult to recognize patterns for groups of packages that work together to accomplish tasks.  

It feels to me like we should make this change.  Otherwise we are accruing debt.  Not many people if any are using now.  But, in the future this is likely an impossible change to make.

**Comment by chrisdholt** [comment]
> Not many people if any are using now.

We can't really know that, so I don't know that it should factor into our decision making process for this

**Comment by nicholasrice** [comment]
I don't think this warrants changing the package name because this has already been published to npm. Closing this.
