### ISSUE TITLE
Element.getBoundingClientRect return value is read-only

### ISSUE THREAD

**Issue by brzho** [Microsoft/fast-dna#764]
It looks like this is the offending line:
https://github.com/Microsoft/fast-dna/blob/master/packages/fast-components-react-base/src/horizontal-overflow/horizontal-overflow.tsx#L116

**Comment by chrisdholt** [comment]
@brzho what line specifically is giving you the error? Is this an issue with the typings?

**Comment by brzho** [comment]
I updated the issue title since I'm not 100% what's causing Edge to throw an error

**Comment by chrisdholt** [comment]
@brzho can you provide the full repro so that we can look into this? I think you mentioned that this was happening in strict mode. Anything else?

**Comment by brzho** [comment]
Adding HorizontalOverflow in the dev site and attempting to render it in Edge throws an error.


To verify run this code in the Edge console:

```js
function test() {
    'use strict';
    var e = document.body.firstElementChild.getBoundingClientRect();
    e.width += "test";
}
 
test();
```

This error gets thrown in console.

>  Assignment to read-only properties is not allowed in strict mode
> 
>  SCRIPT5045: Assignment to read-only properties is not allowed in strict mode

Horizontal overflow is referencing this:
https://github.com/Microsoft/fast-dna/blob/0f8f9f29ef5312e1d1eeee37c30a1475371a0589/packages/fast-web-utilities/src/html.ts#L12

**Comment by chrisdholt** [comment]
PR is up here: https://github.com/Microsoft/fast-dna/pull/767
