### ISSUE TITLE
JSON schemas should be referenceable from other JSON schemas

### ISSUE THREAD

**Issue by prabashn** [Microsoft/fast-dna#772]
**Is your feature request related to a problem? Please describe.**
Currently when you create a prop schema, which contains props from other complex components, you need to copy/paste those schema content from those components to your component schema. This is not maintainable nor does it scale. This also makes it hard to understand schemas that just contains duplications of the same schema (for example, image, link, button, etc.) over and over again. Also imagine what happens if you add a new property to a core schema, which then needs to be propagated to all other components that use that sub-component? Without the schema update I would imagine the tools simply would not work to pick up the new fields, updates, etc.

**Describe the solution you'd like**
I want to be able to reference existing schemas from other schemas so the duplication is removed and an update to a core schema reflects on all other referenced schemas automatically. This way any update to a core schema does not need to be updated everywhere it is copy/pasted, and can be updated at a single place. This should be easily achievable if the JSON schema was to be generated via an actual JS script instead of a dumb .json file. For example we can easily add methods to load and cross-apply schemas. I would imagine it can work very similarly to how we import/export modules in TS.

**Describe alternatives you've considered**
Another alternative could be some convention driven approach where you reference an existing JSON schema using some convention, which then gets interpreted by tools. However this will require preprocessing of JSON, while the initial JS based technique will just work, and would be readily consumable by any tool without pre-processing. It would also likely not violate the JSON schema standard.

**Additional context**

**Comment by nicholasrice** [comment]
Thanks @prabashn -

JSON schemas actually do support a referencing syntax. Does this request mainly speak to the `fast-form-generator-react` being able to support referenced schemas, or is the scope greater than that? What use-case or scenario are you trying to light up?

**Comment by prabashn** [comment]
@chrisdholt, should have background on what I'm referring to. Here's an example file from the experiences repo: https://microsoft.visualstudio.com/DefaultCollection/ICE/_git/ICE.Web.Client.Experiences?path=%2Fsrc%2Ftop-sites%2FTopSites.schema.json&version=GBmaster

**Comment by chrisdholt** [comment]
@nicholasrice Yes, this mainly speaks to `fast-form-generator-react` being able to support referenced schemas. Consider the scenario below:

A user is creating a design system and wants to leverage FAST-DNA components and use the development site as a way of testing. While our components are "composable", they choose to build out components that include more complex objects due to their goals. Each time they create a component that includes a FAST component like `<Typography />` or `<Image />`, they must duplicate the schema for it within the new component they are creating. If at any time a change happens upstream to one of the FAST components, they would need to find and update every instance of it. Outside of the duplication and maintenance issues, this seems like a common ask that we should likely support in a utility that is intended to support flexibility.

**Comment by prabashn** [comment]
Can you actually cross reference schemas across repros? One of the reason why we should think about a potential JS oriented solution so it works even x-repos (unless there's a way to do this automagically, of course! :))

**Comment by nicholasrice** [comment]
You can reference schemas outside of the repo: http://json-schema.org/learn/getting-started-step-by-step.html#references - it's really just a URL.

@janechu does the form generator support resolving referenced schemas (if provided as props)? I thought it did but I could be mistaken.

What is everyone's thoughts on the `form-generator` trying to resolve external references itself? I think I'm of the camp that it should just expect all dependent schemas as props and not make HTTP requests for externally located resources. This keeps the `form-generator` *stupid* and leaves the side-effects to the integrating app.

**Comment by janechu** [comment]
@nicholasrice This is not supported by the form generator, we have another package `fast-permutator` which has an export that resolves references named `resolveReferences`. This can be run first and then the resulting schema with resolved references can be passed to the `fast-form-generator-react`.
