### ISSUE TITLE
Documentation is incomplete for Hypertext

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#777]
On `fast-components-react-base` the very last section discusses
```md
Component documentation

Each component comes with a README.md for implementation and other usage details, a JSON schema for the properties that can be used and additional TypeScript definition files.
```
As instructed, when visiting the readme for Hypertext there are no implementation details.

**Describe the solution you'd like**
We either need to update the wording on the root readme or ideally, update the implementation details for each individual component.

**Additional context**
Also, I noticed that the format on this main markdown file is using `import React from "react"` though in code we're using `import * as React from "react"`.  I'd recommend reconciling the approaches we document to use best practice approach we'd recommend.  If this is different than what is being done on prototypes, those should be reconciled to come in line as well.

**Comment by nalogiudice** [comment]
So, my thoughts are that the component README.md should define the component and enumerate accessibility, and the code preview should cover the general implementation. It seems unnecessary to include a separate implementation file (or section in the MD) when the code preview covers everything except the import line.

**Comment by nicholasrice** [comment]
@awentzel The necessity of the format of `* as React` vs *import React` will depend on each individual TS project, so folks still may get inconsistency here. That said, I've updated this to be consistent with our own project in #784

**Comment by awentzel** [comment]
@nicholasrice  consistency within our own project is how we should move forward.  Assuming, also that our own project is built on best practices.  

@nalogiudice  What your saying sounds reasonable if someone knows how to get code preview up and running and use it.  Currently, this is not documented.  So at a minimum, this should be described in the root then I'm on board with what you're suggesting.

**Comment by chrisdholt** [comment]
+1 for scoping any basic implementation details to the root. Keeping an additional MD file up to date to document one possible implementation for each component seems unnecessary and difficult to maintain.

**Comment by awentzel** [comment]
Assigning to @chrisdholt as he's leading the charge on finalizing components.

**Comment by chrisdholt** [comment]
Opened #921 based on comments here regarding the root readme. The Base package is correct, the MSFT package needs to be updated. Closing this in favor of that issue.
