### ISSUE TITLE
When building a component on a webpage using the basic implementation an error occurs

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#778]
**Describe the bug**
This error 
```typescript 
IntrinsicClassAttributes<Hypertext> & Readonly<{ children?: ReactNode; }> &...'.   Type '{ href: "/"; children: Element; }' is not assignable to type 'Readonly<IHypertextHandledProps & IManagedClasses<IHypertextClassNameContract> & AnchorHTMLAttrib...'.     Property 'managedClasses' is missing in type '{ href: "/"; children: Element; }'."
``` 
occurs when following the documentation as outlined for basic implementation as noted on `fast-components-base-components` [here](https://github.com/Microsoft/fast-dna/tree/master/packages/fast-components-react-base)

**To Reproduce**
Documentation should be accurate and if followed should result in success.  In this case, it looks like it's not possible to implement just the base component.  Or at least, it's not possible if you plan on using `https://msft-docs.fast-dna.net`

**Expected behavior**
It's possible that when using our documentation site because it's built using the msft-components this is why it's required.  If true, we could just update the documentation to be a little more clear on what's required to implement a basic base component or a basic msft component.

**Comment by nicholasrice** [comment]
@awentzel The implied context of https://msft-docs.fast-dna.net is that all components are imported from the MSFT package. We don't illustrate that though, so maybe we should add the import statement at the beginning of the code sample to better show that?

**Comment by chrisdholt** [comment]
+1 for @nicholasrice's note that the implied context of MSFT documentation site is that you are implementing MSFT components. I would not recommend conflating base implementation with MSFT specific implementation. I think we could add an import statement at the beginning of the code sample, but I don't really think it's required. I think confusion might be more mitigated by having the documentation site title specify that these are the MSFT components, or by having an actual landing page that can detail more about the documentation site and what it represents.
