### ISSUE TITLE
The ISnapshotTestSuite interface contains required properties that are not required for snapshot testing

### ISSUE THREAD

**Issue by nicholasrice** [Microsoft/fast-dna#785]
**Is your feature request related to a problem? Please describe.**
The `ISnapshotTestSuite` interface contains required props that are irrelevant to snapshot testing. `schema`, `detailData`, and `documentation` props are requirements of our development-site but not the snapshot testing utilities.

**Describe the solution you'd like**
The requirements of the `ISnapshotTestStuite` interface should only contain properties required for generating snapshots - these include `name`, `component`, and `data` - all other properties should be removed. The documentation site should expand on these props with any necessary additions.

**Comment by chrisdholt** [comment]
closed by #788
