### ISSUE TITLE
Add documentation to fast-development-site

### ISSUE THREAD

**Issue by nicholasrice** [Microsoft/fast-dna#8]
How would someone use this package?

**Comment by eljefe223** [comment]
Hey @janechu this is what I wrote for status.

## Component Status
Each component can have a status of Alpha, Beta or Release. The default is always set to Beta. As the component becomes more stable or is release ready the status can be updated on ISiteCategory props by setting status `Status.alpha`,`Status.beta` or `Status.release`.

**Comment by janechu** [comment]
A more comprehensive documentation task has been written #580 for all packages currently missing information in their README.md files.
