### ISSUE TITLE
applyAcrylic causes an error thrown when used to style a base component

### ISSUE THREAD

**Issue by brzho** [Microsoft/fast-dna#801]
When I try to use `applyAcrylic` on a component rendered in the dev site an error is thrown:

>
> Something went wrong.
> TypeError: Unable to get property 'size' of undefined or null reference
> 

It looks it's because `applyAcrylic` can return the property `background: null`: https://github.com/Microsoft/fast-dna/blob/9ce9a561e7b7a9750027a2c14f318a8fb3fdd8f6/packages/fast-jss-utilities/src/acrylic.ts#L44

Changing it to undefined seems to do the trick. But this might be an issue of how design system handles `background: null`

**Comment by chrisdholt** [comment]
@brzho We'll take a look at this.

As an FYI, if you are looking to apply the MSFT recipe for acrylic, consider using the function within `fast-components-styles-msft` -> `utilities` -> `acrylic`.

**Comment by brzho** [comment]
Thanks! I wasn't aware of that one; it looks like it always a background value so it would work in place of applyAcrylic
