### ISSUE TITLE
Correct fast-animation typings

### ISSUE THREAD

**Issue by nicholasrice** [microsoft/fast-dna#815]
fast-animation implements a `Partial` of the `Keyframe` interface when it should implement the `Keyframe` interface directly. This is due to an outstanding issue in TypeScript that incorrectly defined `Keyframe` to require all CSS properties: https://github.com/Microsoft/TypeScript/issues/26073

**Comment by nicholasrice** [comment]
Blocked by Microsoft/TypeScript#26073

**Comment by awentzel** [comment]
Submitted a comment on the Typescript PR to let them know we're also waiting on this fix.

**Comment by chrisdholt** [comment]
@awentzel I know you pinged on this to the TS folks - has there been any update?

**Comment by awentzel** [comment]
@chrisdholt the link in the top description says still an open issue.
