### ISSUE TITLE
Update tutorials to fine tune performance

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#82]
Implment the HTTP/2 Server Push implementation based on what's in this article. 

https://www.filamentgroup.com/lab/modernizing-delivery.html 

This should always be used for each PWA site and part of our boilerplate. 
----
Pronounced Purple 

https://www.youtube.com/watch?v=7vUs5yOuv-o 

minutes 13-15 minutes 

server workers and lazy loading different parts
----
https://www.youtube.com/watch?v=7vUs5yOuv-o 

11-13 minutes 
implement on all pwa sites

preload-webpack-plugin 
by Addy Osmani
---
Implment the HTTP/2 Server Push implementation based on what's in this article. 

https://www.filamentgroup.com/lab/modernizing-delivery.html 

This should always be used for each PWA site and part of our boilerplate. 

Also update notes in one note as you go to consolidate and focus in on how we should document this to educate those using our boiler plate.

**Comment by Falkicon** [comment]
Issue moved to [Microsoft/fast-tracking #12](https://github.com/Microsoft/fast-tracking/issues/12) via [**ZenHub**](https://www.zenhub.com/)
