### ISSUE TITLE
Update to replace .tmp folder with dist to be more consistent with other packages

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#844]
**Is your feature request related to a problem? Please describe.**
I think any generated files that are used for deployment should go in a `dist` or `www` folder if one of those is already present. my preference is dist since it's more common. Also, prefer to have `www` inside that if there is an accompanying website. But, this can be a future change and has no bearing on this PR.

**Describe the solution you'd like**
All packed files should go into a `dist` folder consistently applied across all project packages.

**Describe alternatives you've considered**
Website files should go into `dist/www`.
Documentation files maybe could go into `dist/docs` folder

**Comment by chrisdholt** [comment]
@awentzel `dist` is actually distributed and in the MSFT package those are primarily for components. I don't think we want to distribute the compiled code for the dev/doc site for these and I would expect that anything we didn't want distributed as part of the NPM package to not be included in that file. If we include things we don't want to distribute, we will have to ignore parts of the folder for npm which would increase maintenance.

I think the ask to unify where non-distributed generated files go is valid, but would recommend against using dist for this purpose.

**Comment by awentzel** [comment]
@chrisdholt @nicholasrice : 
I think we should stick with what the industry is doing.  From my experience this matches   https://stackoverflow.com/questions/23730882/what-is-the-role-of-src-and-dist-Folders 

For publishing packages, I think we should create a different folder `/publish` which is intuitive.  Not sure what is industry norm for publishing.

**Comment by chrisdholt** [comment]
@awentzel to me, distribution aligns more with a product which is essentially what our npm packages are. Publish seems like it could also denote publishing a site. Considering `publish/` could go either way, I don't know that it is actually any more intuitive than `dist/` is.

Here we see the primary as `dist/`: https://stackoverflow.com/questions/22842691/what-is-the-meaning-of-the-dist-directory-in-open-source-projects

**Comment by awentzel** [comment]
.tmp is for automatically generating documentation from readme's.

update documentation regarding how we use the different folders for definition.
