### ISSUE TITLE
Toggle should be after Text field on documentation site

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#852]
**Describe the bug**
If the left navigation is intended to be alphabetical order then text field should come before toggle.

**Screenshots**

[
![screen shot 2018-09-05 at 1 40 37 pm](https://user-images.githubusercontent.com/16669785/45119854-6614ce00-b111-11e8-844e-7821a1cb9cb2.png)
](url)

**To Reproduce**
visit https://msft-docs.azurewebsites.net and look at left nav

**Desktop (please complete the following information):**
all browsers and os's

**Comment by nicholasrice** [comment]
We just need to make sure we sort the examples prior to adding them - this would be a good first-issue.
