### ISSUE TITLE
Replace placeholder service

### ISSUE THREAD

**Issue by janechu** [microsoft/fast-dna#857]
Due to placehold.it adding a watermark it should be replaced with a non-watermarked placeholder service. 

The suggested alternative is: https://imgplaceholder.com/

This placeholder site has the most features, other options to consider include:
https://fakeimg.pl/
https://dummyimage.com/

**Comment by nicholasrice** [comment]
Setting the foreground and background to the same color feels like a work-around. It makes the placeholder look like an empty box and not an image.

**Comment by chrisdholt** [comment]
@nicholasrice I just went and investigated and saw the addition of a new watermark which is not the size or text that was previously marked by placehold.it which clarifies this for me. I think the wording of the task and the lack of an image caused me to see this as needing an image without the sizes which led to the confusion.

**Comment by austin94** [comment]
I can take this one if it's still necessary to remove the attribution.

I've used https://imgplaceholder.com/ before and it's always worked well. The URL structure is almost identical to https://placehold.it

Is there a package or area for common utilities? Might be useful to create a utility similar to

```ts
getPlaceholderImage({ 
    width?: number, 
    height?: number, 
    color?: string, 
    backgroundColor?: string 
}): string
```

Might be overkill for a simple URL, but could be helpful. There are some areas that aren't using `https` (`~/fast-dna/packages/fast-components-react-msft/app/components/carousel-dark-image-content.tsx`) and this could help enforce that.

Let me know whichever is the correct path and I can open a PR for it.
