### ISSUE TITLE
Routing URLs are overly specific

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#858]
**Describe the bug**
Navigating to `https://msft-docs.azurewebsites.net/components/button` page **will not** be found.
Navigating to `https://msft-docs.azurewebsites.net/components/button/` page **will** be found.

Notice it's a difference of a single trailing `/`.

This occurs for every single component page.  Now for the component pages for examples this is not an issue.  

**Expected behavior**
I'd expect pages to be found when entered with and without a trailing slash

**Screenshots**
![screen shot 2018-09-07 at 12 28 33 pm](https://user-images.githubusercontent.com/16669785/45239288-912a2980-b299-11e8-8842-75c988a9f322.png)

**Desktop (please complete the following information):**
indifferent

**Smartphone (please complete the following information):**
indifferent

**Comment by aswathkk** [comment]
How this bug is related to this repo?
Where is the source code for that documentation?

**Comment by awentzel** [comment]
@aswathkk the `./packages/fast-components-react-msft` is deployable as a website on `https://msft-docs.azurewebsites.net` and there should be documentation on that package how to package and deploy.  I don't see this, but, under the `package.json` scripts section you can run `npm run start` to build as development or `npm run build` to build for production.

**Comment by awentzel** [comment]
This has been resolved by installing on production special packages. `npm install express serve-static express-history-api-fallback`
