### ISSUE TITLE
Soft dismiss callback on Dialog

### ISSUE THREAD

**Issue by brzho** [Microsoft/fast-dna#861]
Often times "dialogs" or "lightboxes" have soft-dismiss options. I'd like to request a similar feature for Dialog. A new prop, "onDismiss" could be passed in that gets called when a user clicks on the modal overlay. Or a similar functionality that gives the consuming component a way to know when a user has clicked outside the content.

**Comment by chrisdholt** [comment]
Thanks @brzho! We discussed this functionality when adding the dialog and decided it would be better added upon request. We'll consider this the official request for the feature. 👍
