### ISSUE TITLE
Update all references to @ms-fw/fw-animation to @microsoft/fast-animation

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#87]
Deprecate as much as we can on VSTS and update all projects to point to the OSS version of fast-animation

**Comment by chrisdholt** [comment]
@awentzel can we move this to fast-tracking? I don't think this is related directly to this repo.

**Comment by chrisdholt** [comment]
Issue moved to [Microsoft/fast-tracking #7](https://github.com/Microsoft/fast-tracking/issues/7) via [**ZenHub**](https://www.zenhub.com/)
