### ISSUE TITLE
Styles Button does not take custom className

### ISSUE THREAD

**Issue by prabashn** [Microsoft/fast-dna#879]
**Describe the bug**
Attempting to specify className with the MSFT style [Button](https://github.com/Microsoft/fast-dna/blob/master/packages/fast-components-react-msft/src/button/button.tsx) results in a no-op. Likely because it also creates it's own class names which I guess get applied internally?

**To Reproduce**
'''js
import { Button } from "@microsoft/fast-components-react-msft";
...
<Button className={managedClasses.addButton}/>
'''

**Expected behavior**
The externally specified className should probably be respected, or used in combination with any internally used class names instead of ignoring it.

I'm not sure if my expectation above is incorrect. Basically the className works fine for any of the MSFT styled components such as Label, TextField, Dialog, etc. but apparently does not work the same way for Button. We should expose a unified API so that it works in an expected way when devs attempt to use it.

Currently I'm using a raw <button> element to achieve what I need.

**Comment by chrisdholt** [comment]
@prabashn I think I see this bug. Are you including any of the `ButtonAppearance` enums with your code? I am assuming you are not.

**Comment by chrisdholt** [comment]
@prabashn assuming you are using the default button styles (the one that shows up here: https://msft-docs.azurewebsites.net/), then I was successfully to repro this issue. Working on a fix now.

**Comment by chrisdholt** [comment]
Fix is up at #880
