### ISSUE TITLE
Toggle does not switch on the multi-preview page of the doc site.

### ISSUE THREAD

**Issue by Falkicon** [Microsoft/fast-dna#900]
When clicking the toggle button on the multi-preview page, the toggle does not change state.

Expected: The toggle works.

Note: Toggle seems to be working on the first tab single example.

**Comment by chrisdholt** [comment]
This looks to be related to #561. These components are currently controlled, but there is no way to notify a user that this is a "controlled" component, so the experience seems broken. 

I would suggest that if nothing else, we have at least one uncontrolled instance on the examples page.

**Comment by janechu** [comment]
This will be resolved with #560 where a controlled items will be able to be reset to uncontrolled.
