### ISSUE TITLE
Button no longer renders divider when added as a child

### ISSUE THREAD

**Issue by Falkicon** [Microsoft/fast-dna#902]
**Describe the bug**
When adding a divider as a child of button, nothing shows up.

**To Reproduce**
1. Add divider to button.
2. Notice you don't see a divider.

**Expected behavior**
I expect to see a divider.

**Comment by janechu** [comment]
This is due to the secondary button being the same color as divider, you can see if it you hover over it or if you change it to any of the other appearances. It is working as intended.
