### ISSUE TITLE
Should components create DesignSystemProviders?

### ISSUE THREAD

**Issue by nicholasrice** [Microsoft/fast-dna#915]
Take the following scenario:

A MSFT button is created and text added to it - color is applied via CSS and in this case does not use design-system values directly because MSFT button text is always white. Now when a sub-component is added that uses the designSystem to apply color, there is a mismatch between a button's text and the text of a sub-component.

This problem can manifest in any component that applies a color that isn't a direct implementation of the design system and expects children.

**Comment by chrisdholt** [comment]
Closing as we have resolved the specific issue as it currently stands with new color work included in v4.0
