### ISSUE TITLE
Making IManagedClasses<T>.managedClasses optional

### ISSUE THREAD

**Issue by prabashn** [Microsoft/fast-dna#917]
**What is your feature request? Please describe.**
Whenever I have a child component from FAST, I like to use the prop contract types FAST defines. For example for a text field, I would use TextFieldProps, which look like this:

    export declare type TextFieldProps = ITextFieldHandledProps & ITextFieldUnhandledProps & ITextFieldManagedClasses;

Notice this type is composed of 3 types:
1) ITextFieldHandledProps - all partial props
2) ITextFieldUnhandledProps  - all partial props
3) ITextFieldManagedClasses - not a partial. managedClasses is a required property.

**Describe the solution you'd like**
Making IManagedClasses<T>.managedClasses optional so that when I need to create the prop object for a component, I don't need to keep passing in managedClasses: undefined (this is really problematic in unit tests for example).

**Describe alternatives you've considered**
As a work-around I'm passing 'managedClasses: undefined' everywhere this crops up (usually in unit tests), but would love to clean up the code by removing that unnecessary part.

**Additional context**
N/A

**Comment by nicholasrice** [comment]
Thanks for filing @prabashn - I noticed yesterday also, we need to omit the managedClasses prop from the styled components.

**Comment by chrisdholt** [comment]
@nicholasrice - I think this is regarding the base component. In the base component, this behavior is by design.

**Comment by prabashn** [comment]
.

**Comment by nicholasrice** [comment]
I can see both sides here - at one level these are simply class-names and I shouldn't have to provide them if I don't want to.

There are a few ways this could play out - the prop itself could be optional, but if set, would require all keys. We could also make each key optional, meaning you could selectively apply class names or none at all.

I worry a bit about type safety in doing this - I like when the compiler tells us we're breaking something and I think we would lose some of that safety if we made these optional on the base.

**Comment by nicholasrice** [comment]
Yep - I think I'm on board. I think the original goal was to prevent stylesheets from falling out of sync with class contracts, but I think that goal is actually moot. To your point, a dev shouldn't be required to use a class-name if it isn't necessary for their implementation.

**Comment by prabashn** [comment]
Currently I see us using IXXXHandledProps & IXXXUnhandledProps in a lot of places and one great thing by making it optional is you can stop doing this and just use IXXXProps. It's a lot easier to read, easier to type, and lot more meaningful (mostly because it's simply saying this is the full button contract). By making managedClasses optional, it makes this type a *lot* easier to use :)

**Comment by chrisdholt** [comment]
Some of ^^^^ is just implementation though. For instance, I think in a `manageJss` component instance, XXXXProps will work and not throw an error even if managedClasses is not passed as a prop. It's in base when you want to exclude that it creates issues, right?

What you're advocating for above makes it seem like the change is not within the className contract, but not requiring managedClasses in a union type. Is that accurate?

**Comment by chrisdholt** [comment]
I should've been more clear, sorry to confuse. I confused myself while typing it and again now reading it.
```
Base component = <Component managedClasses={required} />

Styled component = <Component />
```

The above aside though - as I don't think it matters much to the actual asks...

I think we have two asks on this:

1. In IManagedClasses<T>, don't require all classes/contracts
2. In Union Type, don't include/require managed classes.

Can you confirm?

**Comment by prabashn** [comment]
1. Yeah. Basically managedClasses is the only required field here. Making this optional is the main request.

This becomes especially handy when you have a <Button> child component (for example), and you don't have to do IHandledButtonProps & IUnhandledButtonProps anymore in you parent prop contract anymore. You can just use the straight ButtonProps. You no longer need to pass in things like managedClasses: undefined anymore to fill the IManagedClasses required prop.


2. In Union type I don't think it really matters after #1 is done. I do believe though IManagedClasses belongs under the IHandledProps interface/type as it falls under the 'handled props' category. So having the IManagedClasses interface tied to the handled props is probably something good to do. At that point, you just have two types: 1) handled (base props + managed classes) 2) unhandled props.

i.e.,
`
interface IHandledProps extends IManagedClasses<...> {
  ... other handled prop types ...
}

type Props = IHandledProps & IUhandledProps;
`
So when you declare your `Component<H,U,S>`, you can just say:
`Component<IHandledProps, IUnhandledProps, S>`

After that `manageJss(classes)(component)` would just work because your <H> includes the IManagedClasses thing already.

We can talk offline if I'm not making sense, or you have a better alternative.

**Comment by nicholasrice** [comment]
@prabashn Thanks for the detail here. I think we're all on the same page now. This issue is getting cluttered so I've filed a task to do this work: #951.

I think I've distilled down the required work in that issue but please chime in if I've missed something.
