### ISSUE TITLE
Remove fast-animation GitHub repository

### ISSUE THREAD

**Issue by awentzel** [Microsoft/fast-dna#94]
One we go public on fast-dna, update the readme on https://github.com/Microsoft/fast-animation to inform all followers, stars, and forks that the repository has moved. Lock the project and then move after a month.

**Comment by chrisdholt** [comment]
Issue moved to [Microsoft/fast-tracking #6](https://github.com/Microsoft/fast-tracking/issues/6) via [**ZenHub**](https://www.zenhub.com/)
