### ISSUE TITLE
proposal: Gitbook for documentation

### ISSUE THREAD

**Issue by chrisdholt** [Microsoft/fast-dna#941]
There have been some internal conversations recently regarding ways to improve our documentation, as well as external feedback and requests. Some of those are gathered below into feedback regarding the documentation itself as well as potential gaps, and functional requirements of a new documentation "site".

**Documentation specific feedback:**
- Where can I find out the best ways I can leverage packages together?
- More robust guidance/tutorials (creating components, styling components, overriding styles, patterns, etc)
- API documentation
- Would be great to have everything in a single place that is searchable (don't have to dig through the repo, across packages, or in the wiki)

**Functional requirements:**
- Documentation should be managed from the repository
- Should support publishing to an external platform
- Searchable
- Markdown support
- Analytics/usage data
- Embedded content
- **New**: Ability to move content and pages around easily.
- **New**: Unlimited versioning

Enter [gitbook](https://docs.gitbook.com/).

> GitBook is a modern documentation platform where teams can document everything from products, to APIs and internal knowledge-bases.

**Benefits of GitBook**:
- Github integration which allows documentation to live in source control and leverages webhooks to auto-update the documentation site
- Supports [Embedded content](https://docs.gitbook.com/content-editing/embeds)
- Supports [rich content](https://docs.gitbook.com/content-editing/rich-content)
- Supports limited custom theming/branding
- Supports searching
- Strong community (700 plugins): https://plugins.gitbook.com/
- Supports source code updates and online updates with 2-way auto-syncing

**Downsides of GitBook**:
- Non-Active community seems to have died off as of July
- 96 open PRs with no collaborator comments
- Multiple email requests have gone unanswered
- Request to join [Open Source program](https://gitbook.typeform.com/to/LOJytd) has been 2 months unanswered and new submission also no luck.
- Microsoft OSS team is concerned about it's future given issues they found
- Infers directory structure in navigation doesn't actually work. You have to maintain navigation in summary.md
- `docs/` folder must have a readme (not a problem just a note)

**Example**:
Redux is a great example of how documentation is maintained within a repository, but represented and searchable in a separate site.

- Repo structure for docs: https://github.com/reduxjs/redux/tree/master/docs
- Site: https://redux.js.org/

**Possible IA for the documentation:**

```
- What is FAST-DNA
- Concepts
    - Base components
    - Design System
    - Slots
    - Etc.
- Guides (we can bucket these over time)
    - Creating a simple app
    - Creating a base component
    - Styling a base component
    - Theming
        - Basic
        - Advanced
    - Etc…
- Contributing
- Packages
    - JSS Manager
        - About
        - Typedoc / API docs
        - Glossary
    - Base Components
        - About
        - Typedoc / API docs
        - Glossary
    - MSFT Components
        - About
        - Typedoc / API docs
        - Glossary
- Changelog
    - Not the actual changeling, but about our versioning and where to find them.
- Contact
    - Discord
    - Github issues
    - Etc
```

**Resources to implementing:**
* https://github.com/GitbookIO/gitbook/blob/master/docs/setup.md
`gitbook init ./docs`
* when using this command it will read the summary file at the root of .docs and autogenerate the content files.
`gitbook build ./docs --log=debug --debug` to build with detail logs
* Editing and serving locally https://github.com/GitbookIO/gitbook/blob/master/docs/setup.md 
* Configuring content: https://docs.gitbook.com/integrations/github/content-configuration

**Comment by nicholasrice** [comment]
Looks pretty solid to me.

One topic I think we should put a little thought into is **slots**. It's not a standard React convention at this point so I think it will take some specific documentation. We also need a plant for documenting slots that a component supports. Because slots aren't enumerated in a prop API, it can't really be captured in a TypeDoc output

**Comment by chrisdholt** [comment]
> One topic I think we should put a little thought into is **slots**. It's not a standard React convention at this point so I think it will take some specific documentation. We also need a plant for documenting slots that a component supports. Because slots aren't enumerated in a prop API, it can't really be captured in a TypeDoc output

100% agree. This will definitely take some thought but I think it will be worth it.

**Comment by chrisdholt** [comment]
@Microsoft/fast-dna-collaborators we are currently investigating using Docusaurus instead of gitbook, primarily due to some of the removal of previously supported things in their v3 change.

Docusaurus is similar, has a good asthetic, supports markdowown, and is built on React which allows us to extend with our own React code/components: https://docusaurus.io/en/

**Comment by awentzel** [comment]
@chrisdholt can you update this with pros/cons of docusaurus versus gitbook.  What is the latest status on this investigation?  Where did you leave off?

**Comment by awentzel** [comment]
Sounds like we're waiting on GitBook as the copy/move feature may be a bug.  If it turns out this can be back on the top list.

**Comment by awentzel** [comment]
Talking with https://github.com/AaronO in email and hopefully on phone to get additional clarity.

**Comment by awentzel** [comment]
The team has opted to use Docusaurus since it's Open Source and planning to stay this way.  Refer to #1174 and #1172
