### ISSUE TITLE
proposal: add "prettier" for code formatting

### ISSUE THREAD

**Issue by chrisdholt** [Microsoft/fast-dna#950]
**What is "Prettier"**
Prettier is an opinionated code formatter with support for many languages, and in our case, support for TypeScript.

**Why do we need "Prettier"? Don't we have linters?**
From prettier's website:
> Linters have two categories of rules:
>
> Formatting rules: eg: max-len, no-mixed-spaces-and-tabs, keyword-spacing, comma-style...
>
> Prettier alleviates the need for this whole category of rules! Prettier is going to reprint the entire program from scratch in a consistent way, so it's not possible for the programmer to make a mistake there anymore :)
>
> Code-quality rules: eg no-unused-vars, no-extra-bind, no-implicit-globals, prefer-promise-reject-errors...
>
> Prettier does nothing to help with those kind of rules. They are also the most important ones provided by linters as they are likely to catch real bugs with your code!

Prettier handles formatting of code to our specification, which will allow us to spend less mental energy when writing code or reviewing PR's.

**Can we use it with tslint?**
Yes, tslint can still be used to catch code-quality errors. From an implementation standpoint, there is a [package](https://github.com/alexjoverm/tslint-config-prettier) that helps prevent conflicts between the two.

**Can we configure prettier?**
Kind of. 
> Prettier is not a kitchen-sink code formatter that attempts to print your code in any way you wish. It is opinionated.

Prettier's primary goal is to stop all the on-going debates over styles. In their own words:

> The more options Prettier has, the further from the above goal it gets. The debates over styles just turn into debates over which Prettier options to use.

Prettier still supports options. Here is their [philosophy](https://prettier.io/docs/en/option-philosophy.html). Here are the [options](https://prettier.io/docs/en/options.html)

**Implementation**
I suggest we implement this using some sort of pre-commit hook. This way users don't need to worry about running it themselves, it will run as part of the normal dev process. https://prettier.io/docs/en/precommit.html

**Comment by nicholasrice** [comment]
[I'm on board.](https://prettier.io/docs/en/vim.html)

I think we should add it as a git-hook *but also* on the CI because git hooks aren't fool-proof. We would need to diff the result on the CI and fail if diffs are found (automate a commit to the branch)

**Comment by awentzel** [comment]
To my knowledge this has not been a problem.  So why is this necessary and a priority?  I understand what it does.  But, I do t see what problem fast-dna has that we need this.  

Also, what is the cost to run this on the CI (time).  After you add diff and commit on your he CI what is the cost?  How long will it take to implement?  If we haven’t been able to automate bumping on master branch how are we going to automate this on master branch if there is a diff?  How can you just autoapprove a restyle?  What if there is an issue?

**Comment by janechu** [comment]
This looks good, I think this would be a good change and help new contributors.

**Comment by awentzel** [comment]
I think we would all agree the rule for 140 characters is ridiculous.  Why not just change this one linter rule?  I'm also an advocate of learning better coding standards as opposed to having a tool do it for you which then just becomes a crutch you can't live without.  I do understand some of these linter rules just differ depending your editor. 

Either way, you all are in the code more so if this is a change you all agree to great.  But, I'd prefer the impact to be kept at the local developer machine and not on the CI.  It's important to keep build times on the CI at a minimum.  

Has anyone tested how long this takes to run locally?  Why does git pre-push not consistently work?  Is this something that can be fixed?

**Comment by chrisdholt** [comment]
> I think we would all agree the rule for 140 characters is ridiculous. Why not just change this one linter rule?

I think there is a lot to say in regards to readability

> I'm also an advocate of learning better coding standards as opposed to having a tool do it for you which then just becomes a crutch you can't live without. I do understand some of these linter rules just differ depending your editor.

These aren't really related to standards as much as they are to format and style preference. Linters should check for standards issues not style issues.

> But, I'd prefer the impact to be kept at the local developer machine and not on the CI. It's important to keep build times on the CI at a minimum.

I would say that if this causes a markedly significant increase in build times we can address that. I firmly believe that PR's will go through quicker. For instance. Two style issues caused a contributor to push up two changes. That's two more times the build has to run IN FULL due to style issues. That's technically doubling the build time, instead of using a hook to style and then a quick diff as part of the build.

> Has anyone tested how long this takes to run locally?

I plan on snapping a branch but want to ensure we are aligned in **principle** first. Otherwise, it's a time waster to test this. The first time will likely be the longest for whoever does the initial commit since we're doing ALL the code.

> Why does git pre-push not consistently work? Is this something that can be fixed?

@nicholasrice who brought this up

**Comment by awentzel** [comment]
Talked offline and we are all approved but so want to know time in build cost for tracking purposes.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by awentzel** [comment]
Sounds like this can be implemented and enforced using git pre-commit hook instead which is stable.  @chrisdholt is this correct?  If so, I'm approved.

**Comment by chrisdholt** [comment]
@awentzel - yes, primary gold right now is merging all feature branches to limit a massive amount of merge conflicts due to formatting. This will go in once we merge the branch for v3 into master
