### ISSUE TITLE
Remove snapshots from component libraries

### ISSUE THREAD

**Issue by janechu** [Microsoft/fast-dna#956]
Snapshots are not providing useful feedback for components in the `fast-components-base-react` or `fast-components-msft-react` libraries. Too many bugs have gotten through because they are not purposeful enough and require an understanding of HTML/WCAG, the data structure provided and the component they are testing which makes deciphering snapshots both cumbersome and prone to mistakes. It is also not clear when a snapshot needs to be updated whether this was intentional or not as the reviewer then has to crawl back through a component to understand all of the above. They also provide "test coverage" by rendering the react component, but without being precise on what should be rendered this promotes a false narrative on true test coverage.

A few examples of uncaught issues:
- Some typography components not changing markup when tags were being passed
- There was an issue in progress where slot components would repeat the first passed component for that slot instead of passing all components

Unit tests via Jest would be more purposeful and test the actual input/output of components. User passed in prop A, B was rendered. Or accessibility A pattern should be followed, this pattern is tested.

This will be a more mindful approach and should encourage more TDD.

The snapshot package is still very useful for applications/pages as it will aid in the testing of any changes coming from outside an application/page and should be used for those purposes.

**Comment by awentzel** [comment]
Approved.

**Comment by janechu** [comment]
Closing this as resolved.
