### ISSUE TITLE
fast-components-react-msft flipper index.ts does not export all classes

### ISSUE THREAD

**Issue by donaldmcn** [Microsoft/fast-dna#983]
The index.ts file in the flipper component needs to export everything from the project.
It should have
export * from "./flipper"; 

This way IFlipperUnhandledProps (etc.) can be imported from @microsoft/fast-components-react-msft

**Comment by chrisdholt** [comment]
@donaldmcn Thanks for filing this. I think this was just closed with #978 which was merged into our v3 releases branch.
