### ISSUE TITLE
Fix component explorer (all of them) errors and warnings as discovered by WebHint.io

### ISSUE THREAD

**Issue by awentzel** [microsoft/fast-dna#99]
### Expected behavior 
There should not be any errors or warnings when scanned.

### Actual behavior
There are roughly 50 errors that should be resolved. 

### Steps to reproduce the problem
Visit https://sonarwhal.com and select to scan your website. In this case fluentweb.com.  Also, this link was the report i created after scanning.

Ignore fluentweb.com it no longer needs supported.  Rather test on msft-docs.azurewebsites.net

https://sonarwhal.com/scanner/d7bfb186-1729-4a0c-b844-637d51542679

![screen shot 2018-03-16 at 11 18 00 am](https://user-images.githubusercontent.com/16669785/37537758-bfdb9de4-290b-11e8-96e1-3d35b35ad113.png)

**Comment by nicholasrice** [comment]
Task repurposed to audit and fix fast-dna.net if any issues are found.

**Comment by awentzel** [comment]
URL is now https://explore.fastdna.net and this is the first site that should be error/warning free and optimized from PWA/Images/etc
